#version 150
/// BEGIN AUTOGENERATED HEADER
#define CONC(a,b) a##b

#define IF(c, t, e) CONC(IF_, c)(t, e)

#define IF_UNDEF(t, e) e
#define IF_0(t, e) t
#define IF_1(t, e) t
#define IF_2(t, e) t
#define IF_3(t, e) t
#define IF_4(t, e) t
#define IF_5(t, e) t
#define IF_6(t, e) t
#define IF_7(t, e) t
#define IF_8(t, e) t
#define IF_9(t, e) t
#define IF_10(t, e) t
#define IF_11(t, e) t
#define IF_12(t, e) t
#define IF_13(t, e) t
#define IF_14(t, e) t
#define IF_15(t, e) t
#define IF_16(t, e) t
// Workaround for intel HD:
#define IF_00(t, e) t
#ifdef UG_COMPILE_SPIRV
	#define gl_VertexID gl_VertexIndex

	#define LAYOUT_SAMPLER2(s, b) layout(set = s, binding = b)
	#define LAYOUT_SAMPLER(s, b) layout(set = s, binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, set = s, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(push_constant, std140)
	#define LAYOUT_STORAGE(s, b) layout(std140, set = s, binding = b) readonly restrict buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) IF(loc, layout (location = loc) mod in type name, const type name = defaultValue)
		
	#define INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)

	#define OUTPUT(loc, type, name) IF(loc, layout (location = loc) out type name, type name)
	
	#define OUTPUT_MOD(loc, mod, type, name) IF(loc, layout (location = loc) mod out type name, type name)
	
	#define WINDING ccw

	#define LOCATION(loc) layout(location = loc) 
#else
	#extension GL_ARB_separate_shader_objects : require
	#extension GL_ARB_explicit_attrib_location : require
	#extension GL_ARB_shading_language_420pack : require

#ifdef USE_SAMPLER2
	#define LAYOUT_SAMPLER2(s, b)
#else
	#define LAYOUT_SAMPLER2(s, b) layout(binding = b)
#endif

	#define LAYOUT_SAMPLER(s, b) layout(binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(std140, binding = 2)
	#define LAYOUT_STORAGE(s, b) layout(std140, binding = b) buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) mod in type name
		
	#define INPUT(loc, type, name, defaultValue) in type name

	#define OUTPUT(loc, type, name) out type name
	
	#define OUTPUT_MOD(loc, mod, type, name) mod out type name
	
	#define WINDING ccw

	#define LOCATION(loc)
#endif
/// END AUTOGENERATED HEADER

LAYOUT_SAMPLER(1, 0) uniform sampler2D tex;

LAYOUT_PUSH_CONSTANT() uniform PushConstant {
	mat4 projView;
	float alphaScale;
	vec4 colorMix;
} u_const;

INPUT(TC_LOC, vec4, texCoord, vec4(1.0));

OUTPUT(OUT_0, vec4, color);

vec3 decodeNormal(vec3 color);

vec3 invLerp(vec3 x, vec3 a, vec3 b) {
	return (x - a) / (b - a);
}

vec3 map(vec3 x, vec3 a, vec3 b, vec3 c, vec3 d) {
	return mix(c, d, invLerp(x, a, b));
}

void main() {
	vec4 col = texture(tex, texCoord.xy);

	int mode = int(u_const.colorMix.x);

	if (mode == 0) {
		color = vec4(pow(col.rgb, vec3(1.0 / 2.2)), 1.0);
	} else if (mode == 1) {
		color = vec4(col.rrr, 1.0);
	} else if (mode == 2) {
		color = vec4(col.ggg, 1.0);
	} else if (mode == 3) {
		color = vec4(col.bbb, 1.0);
	} else if (mode == 4) {
		color = vec4(col.aaa, 1.0);
	} else if (mode == 5) {
		vec3 nrml = decodeNormal(col.rgb);
		color = vec4(.5 * nrml + vec3(.5), 1.0);
	} else if (mode == 6) {
		vec3 nrml = decodeNormal(vec3(col.rg, .0));
		color = vec4(.5 * nrml + vec3(.5), 1.0);
	} else if (mode == 7) {
		vec3 nrml = col.rgb;
		color = vec4(.5 * nrml + vec3(.5), 1.0);
	} else if (mode == 8) {
		color = vec4(col.rrr, 1.0);
		//color = vec4(pow(col.r, 8.0));
		//color = col.r == 1.0 ? vec4(1.0) : vec4(.0);
	} else {
		color = vec4(1.0);
	} 

	if (u_const.colorMix.z <= u_const.colorMix.w) {
		color.rgb = map(color.rgb, vec3(u_const.colorMix.z), vec3(u_const.colorMix.w), vec3(0.0), vec3(1.0));
	} else {
		color.rgb = map(color.rgb, vec3(u_const.colorMix.w), vec3(u_const.colorMix.z), vec3(0.0), vec3(1.0));
	}
}
