#version 150
/// BEGIN AUTOGENERATED HEADER
#define CONC(a,b) a##b

#define IF(c, t, e) CONC(IF_, c)(t, e)

#define IF_UNDEF(t, e) e
#define IF_0(t, e) t
#define IF_1(t, e) t
#define IF_2(t, e) t
#define IF_3(t, e) t
#define IF_4(t, e) t
#define IF_5(t, e) t
#define IF_6(t, e) t
#define IF_7(t, e) t
#define IF_8(t, e) t
#define IF_9(t, e) t
#define IF_10(t, e) t
#define IF_11(t, e) t
#define IF_12(t, e) t
#define IF_13(t, e) t
#define IF_14(t, e) t
#define IF_15(t, e) t
#define IF_16(t, e) t
// Workaround for intel HD:
#define IF_00(t, e) t
#ifdef UG_COMPILE_SPIRV
	#define gl_VertexID gl_VertexIndex

	#define LAYOUT_SAMPLER2(s, b) layout(set = s, binding = b)
	#define LAYOUT_SAMPLER(s, b) layout(set = s, binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, set = s, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(push_constant, std140)
	#define LAYOUT_STORAGE(s, b) layout(std140, set = s, binding = b) readonly restrict buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) IF(loc, layout (location = loc) mod in type name, const type name = defaultValue)
		
	#define INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)

	#define OUTPUT(loc, type, name) IF(loc, layout (location = loc) out type name, type name)
	
	#define OUTPUT_MOD(loc, mod, type, name) IF(loc, layout (location = loc) mod out type name, type name)
	
	#define WINDING ccw

	#define LOCATION(loc) layout(location = loc) 
#else
	#extension GL_ARB_separate_shader_objects : require
	#extension GL_ARB_explicit_attrib_location : require
	#extension GL_ARB_shading_language_420pack : require

#ifdef USE_SAMPLER2
	#define LAYOUT_SAMPLER2(s, b)
#else
	#define LAYOUT_SAMPLER2(s, b) layout(binding = b)
#endif

	#define LAYOUT_SAMPLER(s, b) layout(binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(std140, binding = 2)
	#define LAYOUT_STORAGE(s, b) layout(std140, binding = b) buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) mod in type name
		
	#define INPUT(loc, type, name, defaultValue) in type name

	#define OUTPUT(loc, type, name) out type name
	
	#define OUTPUT_MOD(loc, mod, type, name) mod out type name
	
	#define WINDING ccw

	#define LOCATION(loc)
#endif
/// END AUTOGENERATED HEADER
#ifndef UG_COMPILE_SPIRV
#extension GL_ARB_tessellation_shader : require
#endif

#ifdef UG_COMPILE_SPIRV
#	define WINDING2 cw
#else
	#define WINDING2 ccw
#endif

layout(quads, equal_spacing, WINDING2) in;

LAYOUT_UBO(0, 10) uniform View {
	mat4 projView;
	mat4 projViewInverse;
	mat4 proj;
	mat4 projInverse;
	mat4 view;
	mat4 viewInverse;
	vec3 camPos;
	float lodFactor;
	float near;
	float far;
} u_view;

LOCATION(0) in VertexDataIn {
	vec4 posAlpha;
	vec4 colorSize;
	vec4 normalRand_;
	vec3 tangent_;
	vec3 binormal_;
	float fogFactor;
	vec3 extFactor;
	vec3 inScatt;
} inData[];

OUTPUT(POS_LOC, vec3, pos);
OUTPUT(NRML_LOC, vec3, normal_);
OUTPUT(TNGT_LOC, vec3, tangent_);
OUTPUT(BNRML_LOC, vec3, binormal_);
OUTPUT(TC_LOC, vec2, texCoord);
OUTPUT(COL_LOC, vec3, color);
OUTPUT(ALPHA_LOC, float, alpha);
OUTPUT(RAND_LOC, float, rand);
OUTPUT(VPOS_LOC, vec3, vpos);
OUTPUT(FOGFACT_LOC, float, fogFactor);
OUTPUT(EXTFACT_LOC, vec3, extFactor);
OUTPUT(INSCATT_LOC, vec3, inScatt);

void main() {
	color = inData[0].colorSize.xyz;
	alpha = inData[0].posAlpha.w;
	rand = inData[0].normalRand_.w;
	normal_ = inData[0].normalRand_.xyz;
	tangent_ = inData[0].tangent_;
	binormal_ = inData[0].binormal_;

	fogFactor = inData[0].fogFactor;
	extFactor = inData[0].extFactor;
	inScatt = inData[0].inScatt;

	float size = inData[0].colorSize.w;
	vec3 center = inData[0].posAlpha.xyz;
	vec3 dxworld = size * tangent_;
	vec3 dyworld = size * binormal_;

	pos = center + (gl_TessCoord.x - 0.5) * dxworld + (gl_TessCoord.y - 0.5) * dyworld;
	vpos = pos;
	gl_Position = u_view.projView * vec4(pos, 1.0);
#ifdef RESCALE_Z_POS
	gl_Position.z = (.5 * gl_Position.z + .5 * gl_Position.w);
#endif
#ifdef INVERT_Y
	gl_Position.y = -gl_Position.y;
#endif
	texCoord = gl_TessCoord.xy;
}
