#version 150
/// BEGIN AUTOGENERATED HEADER
#define CONC(a,b) a##b

#define IF(c, t, e) CONC(IF_, c)(t, e)

#define IF_UNDEF(t, e) e
#define IF_0(t, e) t
#define IF_1(t, e) t
#define IF_2(t, e) t
#define IF_3(t, e) t
#define IF_4(t, e) t
#define IF_5(t, e) t
#define IF_6(t, e) t
#define IF_7(t, e) t
#define IF_8(t, e) t
#define IF_9(t, e) t
#define IF_10(t, e) t
#define IF_11(t, e) t
#define IF_12(t, e) t
#define IF_13(t, e) t
#define IF_14(t, e) t
#define IF_15(t, e) t
#define IF_16(t, e) t
// Workaround for intel HD:
#define IF_00(t, e) t
#ifdef UG_COMPILE_SPIRV
	#define gl_VertexID gl_VertexIndex

	#define LAYOUT_SAMPLER2(s, b) layout(set = s, binding = b)
	#define LAYOUT_SAMPLER(s, b) layout(set = s, binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, set = s, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(push_constant, std140)
	#define LAYOUT_STORAGE(s, b) layout(std140, set = s, binding = b) readonly restrict buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) IF(loc, layout (location = loc) mod in type name, const type name = defaultValue)
		
	#define INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)

	#define OUTPUT(loc, type, name) IF(loc, layout (location = loc) out type name, type name)
	
	#define OUTPUT_MOD(loc, mod, type, name) IF(loc, layout (location = loc) mod out type name, type name)
	
	#define WINDING ccw

	#define LOCATION(loc) layout(location = loc) 
#else
	#extension GL_ARB_separate_shader_objects : require
	#extension GL_ARB_explicit_attrib_location : require
	#extension GL_ARB_shading_language_420pack : require

#ifdef USE_SAMPLER2
	#define LAYOUT_SAMPLER2(s, b)
#else
	#define LAYOUT_SAMPLER2(s, b) layout(binding = b)
#endif

	#define LAYOUT_SAMPLER(s, b) layout(binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(std140, binding = 2)
	#define LAYOUT_STORAGE(s, b) layout(std140, binding = b) buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) mod in type name
		
	#define INPUT(loc, type, name, defaultValue) in type name

	#define OUTPUT(loc, type, name) out type name
	
	#define OUTPUT_MOD(loc, mod, type, name) mod out type name
	
	#define WINDING ccw

	#define LOCATION(loc)
#endif
/// END AUTOGENERATED HEADER

LAYOUT_UBO(0, 10) uniform View {
	mat4 projView;
	mat4 projViewInverse;
	mat4 proj;
	mat4 projInverse;
	mat4 view;
	mat4 viewInverse;
	vec3 camPos;
	float lodFactor;
	float near;
	float far;
} u_view;

LAYOUT_PUSH_CONSTANT() uniform PushConstant {
	float time;
} u_push;

VERTEX_INPUT(ATTR_POS_LOC, vec4, attrPosAlpha, vec4(1.0));
VERTEX_INPUT(ATTR_COL_LOC, vec4, attrColorSizeRot, vec4(1.0));

LOCATION(0) out vsdata {
	vec3 pos;
	vec3 color;
	float size;
	float alpha;
	float rand;
	vec3 normal_;
	vec3 tangent_;
	vec3 binormal_;
} d;

void calcFogFactor(vec3 pos);

void main() {
	d.pos = attrPosAlpha.xyz;
	d.color = vec3(attrColorSizeRot.x);
	d.size = attrColorSizeRot.y;
	d.alpha = attrPosAlpha.w;

	vec3 vertexToCam = u_view.viewInverse[3].xyz - d.pos;
	d.normal_ = normalize(vertexToCam);

	d.rand = attrColorSizeRot.z;
	float rot = d.rand;
	rot += (rot < 0.0 ? -1.0 : 1.0) * u_push.time * 0.02;

	float angle = 2.0 * 3.141592654 * rot;
	float c = cos(angle);
	float s = sin(angle);

	vec3 t0 = (u_view.viewInverse * vec4(1.0, 0.0, 0.0, 0.0)).xyz;//normalize(vec3(-d.normal_.y, d.normal_.x, .0));
	vec3 b0 = cross(d.normal_, t0);

	vec3 t1 = cos(angle) * t0 + sin(angle) * b0;
	vec3 b1 = cross(d.normal_, t1);

	d.tangent_ = t1;
	d.binormal_ = b1;
	
	calcFogFactor(attrPosAlpha.xyz);
}
