#version 150
/// BEGIN AUTOGENERATED HEADER
#define CONC(a,b) a##b

#define IF(c, t, e) CONC(IF_, c)(t, e)

#define IF_UNDEF(t, e) e
#define IF_0(t, e) t
#define IF_1(t, e) t
#define IF_2(t, e) t
#define IF_3(t, e) t
#define IF_4(t, e) t
#define IF_5(t, e) t
#define IF_6(t, e) t
#define IF_7(t, e) t
#define IF_8(t, e) t
#define IF_9(t, e) t
#define IF_10(t, e) t
#define IF_11(t, e) t
#define IF_12(t, e) t
#define IF_13(t, e) t
#define IF_14(t, e) t
#define IF_15(t, e) t
#define IF_16(t, e) t
// Workaround for intel HD:
#define IF_00(t, e) t
#ifdef UG_COMPILE_SPIRV
	#define gl_VertexID gl_VertexIndex

	#define LAYOUT_SAMPLER2(s, b) layout(set = s, binding = b)
	#define LAYOUT_SAMPLER(s, b) layout(set = s, binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, set = s, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(push_constant, std140)
	#define LAYOUT_STORAGE(s, b) layout(std140, set = s, binding = b) readonly restrict buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) IF(loc, layout (location = loc) mod in type name, const type name = defaultValue)
		
	#define INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)

	#define OUTPUT(loc, type, name) IF(loc, layout (location = loc) out type name, type name)
	
	#define OUTPUT_MOD(loc, mod, type, name) IF(loc, layout (location = loc) mod out type name, type name)
	
	#define WINDING ccw

	#define LOCATION(loc) layout(location = loc) 
#else
	#extension GL_ARB_separate_shader_objects : require
	#extension GL_ARB_explicit_attrib_location : require
	#extension GL_ARB_shading_language_420pack : require

#ifdef USE_SAMPLER2
	#define LAYOUT_SAMPLER2(s, b)
#else
	#define LAYOUT_SAMPLER2(s, b) layout(binding = b)
#endif

	#define LAYOUT_SAMPLER(s, b) layout(binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(std140, binding = 2)
	#define LAYOUT_STORAGE(s, b) layout(std140, binding = b) buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) mod in type name
		
	#define INPUT(loc, type, name, defaultValue) in type name

	#define OUTPUT(loc, type, name) out type name
	
	#define OUTPUT_MOD(loc, mod, type, name) mod out type name
	
	#define WINDING ccw

	#define LOCATION(loc)
#endif
/// END AUTOGENERATED HEADER

layout (points) in;
layout (triangle_strip, max_vertices = 4) out;

LAYOUT_UBO(0, 10) uniform View {
	mat4 projView;
	mat4 projViewInverse;
	mat4 proj;
	mat4 projInverse;
	mat4 view;
	mat4 viewInverse;
	vec3 camPos;
	float lodFactor;
	float near;
	float far;
} u_view;

LOCATION(0) in vsdata {
	vec3 pos;
	vec3 color;
	float size;
	float alpha;
	float rand;
	vec3 normal_;
	vec3 tangent_;
	vec3 binormal_;
} d[];

OUTPUT(POS_LOC, vec3, pos);
OUTPUT(NRML_LOC, vec3, normal_);
OUTPUT(TNGT_LOC, vec3, tangent_);
OUTPUT(BNRML_LOC, vec3, binormal_);
OUTPUT(TC_LOC, vec2, texCoord);
OUTPUT(COL_LOC, vec3, color);
OUTPUT(ALPHA_LOC, float, alpha);
OUTPUT(RAND_LOC, float, rand);

void calcFogFactor(vec3 pos);

void main() {
	color = d[0].color;
	alpha = d[0].alpha;
	rand = d[0].rand;
	normal_ = d[0].normal_;
	tangent_ = d[0].tangent_;
	binormal_ = d[0].binormal_;

	float s = d[0].size / 2.0;
	vec3 p = d[0].pos;
	vec3 dxworld = s * tangent_;
	vec3 dyworld = s * binormal_;
	
	calcFogFactor(p);

	pos = p - dxworld - dyworld;
	gl_Position = u_view.projView * vec4(pos, 1.0);
#ifdef RESCALE_Z_POS
	gl_Position.z = (.5 * gl_Position.z + .5 * gl_Position.w);
#endif
#ifdef INVERT_Y
	gl_Position.y = -gl_Position.y;
#endif
	texCoord = vec2(0.0, 0.0);
	EmitVertex();

	pos = p + dxworld - dyworld;
	gl_Position = u_view.projView * vec4(pos, 1.0);
#ifdef RESCALE_Z_POS
	gl_Position.z = (.5 * gl_Position.z + .5 * gl_Position.w);
#endif
#ifdef INVERT_Y
	gl_Position.y = -gl_Position.y;
#endif
	texCoord = vec2(1.0, 0.0);
	EmitVertex();

	pos = p - dxworld + dyworld;
	gl_Position = u_view.projView * vec4(pos, 1.0);
#ifdef RESCALE_Z_POS
	gl_Position.z = (.5 * gl_Position.z + .5 * gl_Position.w);
#endif
#ifdef INVERT_Y
	gl_Position.y = -gl_Position.y;
#endif
	texCoord = vec2(0.0, 1.0);
	EmitVertex();

	pos = p + dxworld + dyworld;
	gl_Position = u_view.projView * vec4(pos, 1.0);
#ifdef RESCALE_Z_POS
	gl_Position.z = (.5 * gl_Position.z + .5 * gl_Position.w);
#endif
#ifdef INVERT_Y
	gl_Position.y = -gl_Position.y;
#endif
	texCoord = vec2(1.0, 1.0);
	EmitVertex();

	EndPrimitive();
}
