#version 150
/// BEGIN AUTOGENERATED HEADER
#define CONC(a,b) a##b

#define IF(c, t, e) CONC(IF_, c)(t, e)

#define IF_UNDEF(t, e) e
#define IF_0(t, e) t
#define IF_1(t, e) t
#define IF_2(t, e) t
#define IF_3(t, e) t
#define IF_4(t, e) t
#define IF_5(t, e) t
#define IF_6(t, e) t
#define IF_7(t, e) t
#define IF_8(t, e) t
#define IF_9(t, e) t
#define IF_10(t, e) t
#define IF_11(t, e) t
#define IF_12(t, e) t
#define IF_13(t, e) t
#define IF_14(t, e) t
#define IF_15(t, e) t
#define IF_16(t, e) t
// Workaround for intel HD:
#define IF_00(t, e) t
#ifdef UG_COMPILE_SPIRV
	#define gl_VertexID gl_VertexIndex

	#define LAYOUT_SAMPLER2(s, b) layout(set = s, binding = b)
	#define LAYOUT_SAMPLER(s, b) layout(set = s, binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, set = s, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(push_constant, std140)
	#define LAYOUT_STORAGE(s, b) layout(std140, set = s, binding = b) readonly restrict buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) IF(loc, layout (location = loc) mod in type name, const type name = defaultValue)
		
	#define INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)

	#define OUTPUT(loc, type, name) IF(loc, layout (location = loc) out type name, type name)
	
	#define OUTPUT_MOD(loc, mod, type, name) IF(loc, layout (location = loc) mod out type name, type name)
	
	#define WINDING ccw

	#define LOCATION(loc) layout(location = loc) 
#else
	#extension GL_ARB_separate_shader_objects : require
	#extension GL_ARB_explicit_attrib_location : require
	#extension GL_ARB_shading_language_420pack : require

#ifdef USE_SAMPLER2
	#define LAYOUT_SAMPLER2(s, b)
#else
	#define LAYOUT_SAMPLER2(s, b) layout(binding = b)
#endif

	#define LAYOUT_SAMPLER(s, b) layout(binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(std140, binding = 2)
	#define LAYOUT_STORAGE(s, b) layout(std140, binding = b) buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) mod in type name
		
	#define INPUT(loc, type, name, defaultValue) in type name

	#define OUTPUT(loc, type, name) out type name
	
	#define OUTPUT_MOD(loc, mod, type, name) mod out type name
	
	#define WINDING ccw

	#define LOCATION(loc)
#endif
/// END AUTOGENERATED HEADER

LAYOUT_UBO(0, 10) uniform View {
	mat4 projView;
	mat4 projViewInverse;
	mat4 proj;
	mat4 projInverse;
	mat4 view;
	mat4 viewInverse;
	vec3 camPos;
	float lodFactor;
	float near;
	float far;
} u_view;

LAYOUT_PUSH_CONSTANT() uniform PushConstant {
	float time;
} u_push;

VERTEX_INPUT(ATTR_POS_LOC, vec4, attrPosAlpha, vec4(1.0));
VERTEX_INPUT(ATTR_COL_LOC, vec4, attrColorSizeRot, vec3(1.0));

layout (location = 0) out vec4 posAlpha;
layout (location = 1) out vec4 colorSize;
layout (location = 2) out vec4 normalRand_;
layout (location = 3) out vec3 tangent_;
layout (location = 4) out vec3 binormal_;
layout(location = 5) out float fogFactor;
layout(location = 6) out vec3 extFactor;
layout(location = 7) out vec3 inScatt;
	
void calcFogFactor(vec3 pos, out float fogFactor, out vec3 extFactor, out vec3 inScatt);

void main() {
	posAlpha.xyz = attrPosAlpha.xyz;
	colorSize.xyz = vec3(attrColorSizeRot.x);
	colorSize.w = attrColorSizeRot.y;
	posAlpha.w = attrPosAlpha.w;

	vec3 vertexToCam = u_view.viewInverse[3].xyz - posAlpha.xyz;
	normalRand_.xyz = normalize(vertexToCam);

	normalRand_.w = attrColorSizeRot.z;
	float rot = normalRand_.w;
	rot += (rot < 0.0 ? -1.0 : 1.0) * u_push.time * 0.02;

	float angle = 2.0 * 3.141592654 * rot;
	float c = cos(angle);
	float s = sin(angle);

	vec3 t0 = (u_view.viewInverse * vec4(1.0, 0.0, 0.0, 0.0)).xyz;//normalize(vec3(-outData.normal_.y, outData.normal_.x, .0));
	vec3 b0 = cross(normalRand_.xyz, t0);

	vec3 t1 = cos(angle) * t0 + sin(angle) * b0;
	vec3 b1 = cross(normalRand_.xyz, t1);

	tangent_ = t1;
	binormal_ = b1;
	
	calcFogFactor(attrPosAlpha.xyz, fogFactor, extFactor, inScatt);
}
