#version 150
/// BEGIN AUTOGENERATED HEADER
#define CONC(a,b) a##b

#define IF(c, t, e) CONC(IF_, c)(t, e)

#define IF_UNDEF(t, e) e
#define IF_0(t, e) t
#define IF_1(t, e) t
#define IF_2(t, e) t
#define IF_3(t, e) t
#define IF_4(t, e) t
#define IF_5(t, e) t
#define IF_6(t, e) t
#define IF_7(t, e) t
#define IF_8(t, e) t
#define IF_9(t, e) t
#define IF_10(t, e) t
#define IF_11(t, e) t
#define IF_12(t, e) t
#define IF_13(t, e) t
#define IF_14(t, e) t
#define IF_15(t, e) t
#define IF_16(t, e) t
// Workaround for intel HD:
#define IF_00(t, e) t
#ifdef UG_COMPILE_SPIRV
	#define gl_VertexID gl_VertexIndex

	#define LAYOUT_SAMPLER2(s, b) layout(set = s, binding = b)
	#define LAYOUT_SAMPLER(s, b) layout(set = s, binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, set = s, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(push_constant, std140)
	#define LAYOUT_STORAGE(s, b) layout(std140, set = s, binding = b) readonly restrict buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) IF(loc, layout (location = loc) mod in type name, const type name = defaultValue)
		
	#define INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)

	#define OUTPUT(loc, type, name) IF(loc, layout (location = loc) out type name, type name)
	
	#define OUTPUT_MOD(loc, mod, type, name) IF(loc, layout (location = loc) mod out type name, type name)
	
	#define WINDING ccw

	#define LOCATION(loc) layout(location = loc) 
#else
	#extension GL_ARB_separate_shader_objects : require
	#extension GL_ARB_explicit_attrib_location : require
	#extension GL_ARB_shading_language_420pack : require

#ifdef USE_SAMPLER2
	#define LAYOUT_SAMPLER2(s, b)
#else
	#define LAYOUT_SAMPLER2(s, b) layout(binding = b)
#endif

	#define LAYOUT_SAMPLER(s, b) layout(binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(std140, binding = 2)
	#define LAYOUT_STORAGE(s, b) layout(std140, binding = b) buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) mod in type name
		
	#define INPUT(loc, type, name, defaultValue) in type name

	#define OUTPUT(loc, type, name) out type name
	
	#define OUTPUT_MOD(loc, mod, type, name) mod out type name
	
	#define WINDING ccw

	#define LOCATION(loc)
#endif
/// END AUTOGENERATED HEADER

LAYOUT_SAMPLER(1, 14) uniform sampler2D tex;
LAYOUT_SAMPLER(1, 15) uniform sampler2D normalTex;
LAYOUT_SAMPLER(1, 16) uniform sampler2D noise0Tex;
LAYOUT_SAMPLER(1, 17) uniform sampler2D noise1Tex;

LAYOUT_PUSH_CONSTANT() uniform PushConstant {
	float time;
} u_push;

INPUT(POS_LOC, vec3, pos, vec3(1.0));
INPUT(NRML_LOC, vec3, normal_, vec3(1.0));
INPUT(TNGT_LOC, vec3, tangent_, vec3(1.0));
INPUT(BNRML_LOC, vec3, binormal_, vec3(1.0));
INPUT(TC_LOC, vec2, texCoord, vec2(1.0));
INPUT(COL_LOC, vec3, color, vec3(1.0));
INPUT(ALPHA_LOC, float, alpha, float(1.0));
INPUT(RAND_LOC, float, rand, float(1.0));

OUTPUT(OUT_0, vec4, color0);

vec4 applyFog(vec4 color);
vec3 decodeNormal(vec3 color);
vec3 getNormalMapped(vec3 texNormal, vec3 normal_, vec3 binormal_, vec3 tangent_, bool flip);
vec4 lightPhysLinear(vec3 pos, float ambient, vec3 normal, vec3 albedo, float metalness, float glossiness, float alpha);

void main() {
	vec2 tc = texCoord;

	float scaledTime = u_push.time * 0.10 * rand + rand;
	vec2 tcn0 = texCoord + vec2(rand) + vec2(scaledTime, 2.0 * scaledTime);
	vec2 tcn1 = texCoord + vec2(rand) + vec2(scaledTime, 2.0 * scaledTime);

	float ambient = 1.0 - pow(alpha, 5.0);

	vec3 lincolor = pow(color, vec3(2.2));
	vec3 normal = getNormalMapped(decodeNormal(texture(normalTex, tc).rgb), normal_, binormal_, tangent_, false);

	float mk = texture(tex, tc).r;
	float texZoom = 0.1;
	float n0 = texture(noise0Tex, texZoom * tcn0).r;
	float n1 = texture(noise1Tex, texZoom * 0.5 * tcn1).r;
	float a0 = ((n0 * n1) * 4.0) * mk * alpha;
	float a1 = mk * alpha;

	color0 = applyFog(lightPhysLinear(pos, ambient, normal, lincolor, .0, .08, alpha * a1 + (1.0 - alpha) * a0));
}
