#version 150
/// BEGIN AUTOGENERATED HEADER
#define CONC(a,b) a##b

#define IF(c, t, e) CONC(IF_, c)(t, e)

#define IF_UNDEF(t, e) e
#define IF_0(t, e) t
#define IF_1(t, e) t
#define IF_2(t, e) t
#define IF_3(t, e) t
#define IF_4(t, e) t
#define IF_5(t, e) t
#define IF_6(t, e) t
#define IF_7(t, e) t
#define IF_8(t, e) t
#define IF_9(t, e) t
#define IF_10(t, e) t
#define IF_11(t, e) t
#define IF_12(t, e) t
#define IF_13(t, e) t
#define IF_14(t, e) t
#define IF_15(t, e) t
#define IF_16(t, e) t
// Workaround for intel HD:
#define IF_00(t, e) t
#ifdef UG_COMPILE_SPIRV
	#define gl_VertexID gl_VertexIndex

	#define LAYOUT_SAMPLER2(s, b) layout(set = s, binding = b)
	#define LAYOUT_SAMPLER(s, b) layout(set = s, binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, set = s, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(push_constant, std140)
	#define LAYOUT_STORAGE(s, b) layout(std140, set = s, binding = b) readonly restrict buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) IF(loc, layout (location = loc) mod in type name, const type name = defaultValue)
		
	#define INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)

	#define OUTPUT(loc, type, name) IF(loc, layout (location = loc) out type name, type name)
	
	#define OUTPUT_MOD(loc, mod, type, name) IF(loc, layout (location = loc) mod out type name, type name)
	
	#define WINDING ccw

	#define LOCATION(loc) layout(location = loc) 
#else
	#extension GL_ARB_separate_shader_objects : require
	#extension GL_ARB_explicit_attrib_location : require
	#extension GL_ARB_shading_language_420pack : require

#ifdef USE_SAMPLER2
	#define LAYOUT_SAMPLER2(s, b)
#else
	#define LAYOUT_SAMPLER2(s, b) layout(binding = b)
#endif

	#define LAYOUT_SAMPLER(s, b) layout(binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(std140, binding = 2)
	#define LAYOUT_STORAGE(s, b) layout(std140, binding = b) buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) mod in type name
		
	#define INPUT(loc, type, name, defaultValue) in type name

	#define OUTPUT(loc, type, name) out type name
	
	#define OUTPUT_MOD(loc, mod, type, name) mod out type name
	
	#define WINDING ccw

	#define LOCATION(loc)
#endif
/// END AUTOGENERATED HEADER

LAYOUT_SAMPLER(0, 25) uniform sampler2D normalTex;
LAYOUT_SAMPLER(0, 26) uniform sampler2D depthBufTex;
LAYOUT_SAMPLER(0, 27) uniform sampler2D rnm;			// Random vectors to randomize the sampling kernel

LAYOUT_UBO(0, 4) uniform Ssao {
	mat4 invViewMat;

	vec2 normalMapRes1;

	int samples;
	vec4 randSphereVector[16];

	vec2 tcScale;

	vec2 nearPlaneHalfSize;
	vec2 nearFar; 
} u_ssao;

INPUT(TC_LOC, vec2, texCoord, vec2(1.0));

OUTPUT(OUT_0, vec4, color0);

float compShadow(vec3 vpos);
vec3 rgbToNormal(vec3 rgb);

float calcEyeZ(float depth) {
	float near = u_ssao.nearFar.x;
	float far = u_ssao.nearFar.y;
	float d = 2.0 * depth - 1.0;
	return -2.0 * near * far / (far + near - d * (far - near));
}

float getDepth(vec2 uv) {
#ifdef INVERT_FRAMEBUFFER_READ_Y
	uv.y = 1 - uv.y;
#endif
	float z = calcEyeZ(texture(depthBufTex, uv).r);
	return (-z - u_ssao.nearFar.x) / (u_ssao.nearFar.y - u_ssao.nearFar.x);
}

vec3 getNormal(vec2 uv) {
#ifdef INVERT_FRAMEBUFFER_READ_Y
	uv.y = 1 - uv.y;
#endif
	return rgbToNormal(texture(normalTex, uv).rgb);
}


vec2 matchPixelCenter(vec2 uv) {
	vec2 ij = floor(uv / u_ssao.normalMapRes1);
	return (vec2(.5) + ij) * u_ssao.normalMapRes1; 
}

vec3 depth2Position(vec2 uv, float depth) {
	vec2 xyOnNearPlane = (uv - .5) * 2.0 * u_ssao.nearPlaneHalfSize;
	vec3 xyzOnNearPlane = vec3(xyOnNearPlane.x, xyOnNearPlane.y, -u_ssao.nearFar.x);
	float scale = mix(u_ssao.nearFar.x, u_ssao.nearFar.y, depth) / u_ssao.nearFar.x;
	return xyzOnNearPlane * scale;
}

float sampleFun(vec3 srcPosition, vec3 srcNormal, vec2 uv, float radius) {
	float dstDepth = getDepth(uv);
	vec3 dstPosition = depth2Position(uv, dstDepth);	

	vec3 positionVec = dstPosition - srcPosition;
	float dist = length(positionVec);
	if (dist < .01) return .0;
	
	float intensity = max(dot(positionVec / dist, srcNormal) - .05, .0);
	
	float attenuation = max(1.0 - .25 * dist / radius, .0);
	
	return intensity * attenuation;
}

void main () {
	vec2 texCoordC = matchPixelCenter(texCoord);

	float srcDepth = getDepth(texCoordC);
	vec3 srcPosition = depth2Position(texCoordC, srcDepth);
	vec3 srcNormal = getNormal(texCoordC);

	vec3 randVec = normalize(texture(rnm, texCoordC * u_ssao.tcScale).xyz * 2.0 - 1.0);
		
	float occlusion = 0.0;
	
	float minRadius = .75;
	float usualRadius = 1.25;	
	float radius = mix(minRadius, usualRadius, clamp(-srcPosition.z * .025, .0, 1.0)); 
	
	const int maxSSAOSamples = 8;
	for (int i = 0; i < min(u_ssao.samples, maxSSAOSamples); ++i) {
		vec3 rsv = reflect(u_ssao.randSphereVector[i].xyz * radius, randVec);
		
		vec3 samplePos = srcPosition + rsv;
		
		vec2 uv = .5 + .5 * (samplePos.xy / -samplePos.z * u_ssao.nearFar.x) / u_ssao.nearPlaneHalfSize;
		if (abs(uv.x - texCoord.x) < u_ssao.normalMapRes1.x && abs(uv.y - texCoord.y) < u_ssao.normalMapRes1.y) {
			continue;
		}
		
		uv = matchPixelCenter(uv);
		 
		occlusion += sampleFun(srcPosition, srcNormal, uv, radius);
	}
	
	occlusion /= float(u_ssao.samples);		
	
	occlusion = clamp(3.0 * occlusion, 0.0, 1.0);

	vec3 worldPos = vec3(u_ssao.invViewMat * vec4(srcPosition, 1.0));
	occlusion *= mix(1.0, .65, compShadow(worldPos));

	color0 = vec4(1.0);
	color0.r = 1.0 - occlusion;
}
