#version 150
/// BEGIN AUTOGENERATED HEADER
#define CONC(a,b) a##b

#define IF(c, t, e) CONC(IF_, c)(t, e)

#define IF_UNDEF(t, e) e
#define IF_0(t, e) t
#define IF_1(t, e) t
#define IF_2(t, e) t
#define IF_3(t, e) t
#define IF_4(t, e) t
#define IF_5(t, e) t
#define IF_6(t, e) t
#define IF_7(t, e) t
#define IF_8(t, e) t
#define IF_9(t, e) t
#define IF_10(t, e) t
#define IF_11(t, e) t
#define IF_12(t, e) t
#define IF_13(t, e) t
#define IF_14(t, e) t
#define IF_15(t, e) t
#define IF_16(t, e) t
// Workaround for intel HD:
#define IF_00(t, e) t
#ifdef UG_COMPILE_SPIRV
	#define gl_VertexID gl_VertexIndex

	#define LAYOUT_SAMPLER2(s, b) layout(set = s, binding = b)
	#define LAYOUT_SAMPLER(s, b) layout(set = s, binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, set = s, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(push_constant, std140)
	#define LAYOUT_STORAGE(s, b) layout(std140, set = s, binding = b) readonly restrict buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) IF(loc, layout (location = loc) mod in type name, const type name = defaultValue)
		
	#define INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)

	#define OUTPUT(loc, type, name) IF(loc, layout (location = loc) out type name, type name)
	
	#define OUTPUT_MOD(loc, mod, type, name) IF(loc, layout (location = loc) mod out type name, type name)
	
	#define WINDING ccw

	#define LOCATION(loc) layout(location = loc) 
#else
	#extension GL_ARB_separate_shader_objects : require
	#extension GL_ARB_explicit_attrib_location : require
	#extension GL_ARB_shading_language_420pack : require

#ifdef USE_SAMPLER2
	#define LAYOUT_SAMPLER2(s, b)
#else
	#define LAYOUT_SAMPLER2(s, b) layout(binding = b)
#endif

	#define LAYOUT_SAMPLER(s, b) layout(binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(std140, binding = 2)
	#define LAYOUT_STORAGE(s, b) layout(std140, binding = b) buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) mod in type name
		
	#define INPUT(loc, type, name, defaultValue) in type name

	#define OUTPUT(loc, type, name) out type name
	
	#define OUTPUT_MOD(loc, mod, type, name) mod out type name
	
	#define WINDING ccw

	#define LOCATION(loc)
#endif
/// END AUTOGENERATED HEADER

LAYOUT_SAMPLER(2, 23) uniform sampler2D albedoOpacityTex;
LAYOUT_SAMPLER(2, 25) uniform sampler2D normalTex;

LAYOUT_UBO(0, 6) uniform Light {
	vec3 lightDir;
	float lightScale;
	mat4 lightTransf;
	mat4 lightInvTransf;
	float ambientScale;
} u_light;

LAYOUT_UBO(1, 3) uniform Material {
	vec4 albedoScales[16];

	float alphaScales[16];

	float alphaThreshold;

	vec4 fakeShadows[16];
	float fakeShadowradii[16];

	float normalScale;

	bool flipNormal;
} u_mat;

INPUT(POS_LOC, vec4, posAmbient, vec4(1.0));
INPUT(NRML_LOC, vec3, normal_, vec3(1.0));
INPUT(TNGT_LOC, vec3, tangent_, vec3(1.0));
INPUT_MOD(TC_LOC, centroid, vec3, texCoordAlpha, vec3(1.0));
INPUT(OFFSET_LOC, vec3, offset, vec3(1.0));
INPUT_MOD(MATIDX_LOC, flat, int, matIndex, 0);

vec3 decodeNormalScale(vec3 color, float scale);
vec3 getNormalMapped(vec3 texNormal, vec3 normal_, vec3 binormal_, vec3 tangent_, bool flip);
float compShadow(vec3 vpos);
void fragmentOutput(vec3 pos, float ambient, vec3 normal, vec3 albedo, float metalness, float glossiness, float alpha, float shadow);

void main() {
	if (texCoordAlpha.z < u_mat.alphaThreshold) discard;

	vec3 binormal_ = cross(normal_, tangent_);

	vec3 texNormal = decodeNormalScale(texture(normalTex, texCoordAlpha.xy).rgb, u_mat.normalScale);
	vec3 normal = getNormalMapped(texNormal, normal_, binormal_, tangent_, u_mat.flipNormal);
	
	vec4 col = texture(albedoOpacityTex, texCoordAlpha.xy);
	if (col.a <= u_mat.alphaThreshold) discard;

	float alpha = min(u_mat.alphaScales[matIndex] * col.a, 1.0) * texCoordAlpha.z;

	// offset is texCoord.y relative to atlas (0 to 1)
	float shadow = compShadow(posAmbient.xyz);
	
	#define USE_FAKE_BILLBOARDS
	
#ifdef USE_FAKE_BILLBOARDS
	//vec3 offset =vec3(.0);
	vec3 n1;
	const float pi = 3.1415;
	float r = u_mat.fakeShadowradii[matIndex];
	if (normal_.z > .1) {
		float cz = cos(offset.z), sz = sin(offset.z);
		
		mat2 rotz = mat2(
			cz,  sz,
			-sz, cz
		);
		float oy = (offset.y - 0.5)*2/r;
		float ox = (offset.x - 0.5)*2/r;
		float h = sqrt(1 - min(ox * ox + oy * oy, 1.0));
		
		float eta = clamp(-pi*r, -pi, pi);
		float theta = clamp(pi*r, -pi, pi);
		//float theta = (offset.x - 0.5)*2*pi*r;
		//float eta = -(offset.y - 0.5)*2*pi*r;
		
		//float cy = cos(eta), sy = sin(eta);
		//float cx = cos(theta), sx = sin(theta);
		n1 = vec3(rotz * vec2(ox, oy), h);  // sz, .0, cz
	} else {
		float thr = u_mat.fakeShadows[matIndex].w;
		float theta = .0; // latitude
		if (offset.y > thr) {
			theta = mix(.0, pi / 2, (offset.y - thr) / (1.0 - thr));
		} else {
			theta = mix(-pi / 2, .0, offset.y / thr);
		}
		float eta = (offset.x - 0.5)*2*pi; // longitude
		
		float cz = cos(eta), sz = sin(eta);
		float cy = cos(theta), sy = sin(theta);
			
		mat2 rotz = mat2(
			cz,  sz,
			-sz, cz
		);
		n1 = vec3(rotz * cy * normal_.xy, sy);
		
	}
	float low = u_mat.fakeShadows[matIndex].x; // amount of light on shadow-facing side, 0 to 1 (full backlight)
	float high = u_mat.fakeShadows[matIndex].y; // amount of light of light-facing side, 0 to 1 (full frontlight)
	float contrast = u_mat.fakeShadows[matIndex].z;
	float dotP = clamp(dot(normalize(n1), u_light.lightDir), -1.0, .0) * 2.0 + 1.0;
	float shadowFactor = atan(contrast * 10 * dotP) * .31830988618 + .5;

	shadow *= clamp(mix(low, high, shadowFactor), .0, 1.0);
#endif

	vec3 albedo = col.rgb * u_mat.albedoScales[matIndex].xyz;
	fragmentOutput(posAmbient.xyz, 1.0, normal, albedo, .0, .0, alpha, shadow);

	//color.rgb = vec3(n1);
	//color.rgb = vec3(normal_);
	//color.rgb = vec3(n1.z * 0.5 + 0.5);
	//color.rgb = vec3(low);
	//color.rgb = vec3(ddd);
	//color.rgb =  vec3(dotP);
	//color.rgb = vec3(n1);
}
