#version 450

// layout(local_size_x_id = 0, local_size_y_id = 1, local_size_z_id = 2) in; // can use specialization constants when creating pipeline
layout(local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

layout(push_constant) uniform Parameters {
	int Width;
	int Height;
	float a;
} params;

layout(std430, binding = 0) buffer lay0 { float arr_x[]; };
layout(std430, binding = 1) buffer lay1 { float arr_y[]; };

void main() {
	if (params.Width <= gl_GlobalInvocationID.x || params.Height <= gl_GlobalInvocationID.y){
		return;
	}

	const int id = params.Width * gl_GlobalInvocationID.y + gl_GlobalInvocationID.x; // gl_WorkGroupID * gl_WorkGroupSize + gl_LocalInvocationID

	arr_y[id] += params.a * arr_x[id]; // saxpy
}
