#version 150
/// BEGIN AUTOGENERATED HEADER
#define CONC(a,b) a##b

#define IF(c, t, e) CONC(IF_, c)(t, e)

#define IF_UNDEF(t, e) e
#define IF_0(t, e) t
#define IF_1(t, e) t
#define IF_2(t, e) t
#define IF_3(t, e) t
#define IF_4(t, e) t
#define IF_5(t, e) t
#define IF_6(t, e) t
#define IF_7(t, e) t
#define IF_8(t, e) t
#define IF_9(t, e) t
#define IF_10(t, e) t
#define IF_11(t, e) t
#define IF_12(t, e) t
#define IF_13(t, e) t
#define IF_14(t, e) t
#define IF_15(t, e) t
#define IF_16(t, e) t
// Workaround for intel HD:
#define IF_00(t, e) t
#ifdef UG_COMPILE_SPIRV
	#define gl_VertexID gl_VertexIndex

	#define LAYOUT_SAMPLER2(s, b) layout(set = s, binding = b)
	#define LAYOUT_SAMPLER(s, b) layout(set = s, binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, set = s, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(push_constant, std140)
	#define LAYOUT_STORAGE(s, b) layout(std140, set = s, binding = b) readonly restrict buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) IF(loc, layout (location = loc) mod in type name, const type name = defaultValue)
		
	#define INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)

	#define OUTPUT(loc, type, name) IF(loc, layout (location = loc) out type name, type name)
	
	#define OUTPUT_MOD(loc, mod, type, name) IF(loc, layout (location = loc) mod out type name, type name)
	
	#define WINDING ccw

	#define LOCATION(loc) layout(location = loc) 
#else
	#extension GL_ARB_separate_shader_objects : require
	#extension GL_ARB_explicit_attrib_location : require
	#extension GL_ARB_shading_language_420pack : require

#ifdef USE_SAMPLER2
	#define LAYOUT_SAMPLER2(s, b)
#else
	#define LAYOUT_SAMPLER2(s, b) layout(binding = b)
#endif

	#define LAYOUT_SAMPLER(s, b) layout(binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(std140, binding = 2)
	#define LAYOUT_STORAGE(s, b) layout(std140, binding = b) buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) mod in type name
		
	#define INPUT(loc, type, name, defaultValue) in type name

	#define OUTPUT(loc, type, name) out type name
	
	#define OUTPUT_MOD(loc, mod, type, name) mod out type name
	
	#define WINDING ccw

	#define LOCATION(loc)
#endif
/// END AUTOGENERATED HEADER

LAYOUT_SAMPLER(0, 0) uniform sampler2D tex;

LAYOUT_UBO(0, 4) uniform Offset {
	float ofs;
} u_offset;

INPUT(TC_LOC, vec2, texCoord, vec2(1.0));

OUTPUT(OUT_0, vec4, color);

#ifndef SIZE
#	define SIZE 9
#endif
const int N1 = (SIZE - 1) / 2;

void main() {
#if SIZE == 7
	float weights[7] = float[7](0.006, 0.061, 0.242, 0.383, 0.242, 0.061, 0.006);
#elif SIZE == 9
	float weights[9] = float[9](1.0/256.0, 8.0/256.0, 28.0/256.0, 56.0/256.0, 70.0/256.0, 56.0/256.0, 28.0/256.0, 8.0/256.0, 1.0/256.0);
#elif SIZE == 12
	float weights[12] = float[12](
		1.0/4096, 12.0/4096, 66.0/4096, 220.0/4096, 
		495.0/4096, 792.0/4096, 924.0/4096, 792.0/4096, 495.0/4096, 
		220.0/4096, 66.0/4096, 12.0/4096, 1.0/4096
	);
#elif SIZE == 15
	float weights[15] = float[15](
		6.103515625e-05, 0.0008544921875, 0.00555419921875, 0.022216796875, 
		0.06109619140625, 0.1221923828125, 0.18328857421875, 0.20947265625, 
		0.18328857421875, 0.1221923828125, 0.06109619140625, 0.022216796875, 
		0.00555419921875, 0.0008544921875, 6.103515625e-05
	);
#elif SIZE == 29
	float weights[29] = float[29](
		3.725290298461914e-09, 1.043081283569336e-07, 1.4081597328186035e-06, 1.220405101776123e-05,
		7.627531886100769e-05, 0.0003661215305328369, 0.0014034658670425415, 0.004410892724990845, 
		0.011578593403100967, 0.025730207562446594, 0.04888739436864853, 0.07999755442142487, 
		0.11332986876368523, 0.13948291540145874, 0.14944598078727722, 0.13948291540145874, 
		0.11332986876368523, 0.07999755442142487, 0.04888739436864853, 0.025730207562446594, 
		0.011578593403100967, 0.004410892724990845, 0.0014034658670425415, 0.0003661215305328369, 
		7.627531886100769e-05, 1.220405101776123e-05, 1.4081597328186035e-06, 1.043081283569336e-07, 
		3.725290298461914e-09
	);
#endif

	vec2 texCoord2 = texCoord;
#ifdef INVERT_FRAMEBUFFER_READ_Y
	// TODO:
	texCoord2.y = 1 - texCoord.y;
#endif
	vec4 res = vec4(0.0);
	for (int i = 0; i < SIZE; ++i) {
#if VERTICAL == 0
		vec2 ofs2 = vec2(u_offset.ofs*(float(i)-float(N1)), .0);
#elif VERTICAL == 1
		vec2 ofs2 = vec2(0.0, u_offset.ofs*(float(i)-float(N1)));
#endif
		vec4 col = texture(tex, texCoord2 + ofs2);
		res += col*weights[i];
	}
	color = res;
}
