#version 150
/// BEGIN AUTOGENERATED HEADER
#define CONC(a,b) a##b

#define IF(c, t, e) CONC(IF_, c)(t, e)

#define IF_UNDEF(t, e) e
#define IF_0(t, e) t
#define IF_1(t, e) t
#define IF_2(t, e) t
#define IF_3(t, e) t
#define IF_4(t, e) t
#define IF_5(t, e) t
#define IF_6(t, e) t
#define IF_7(t, e) t
#define IF_8(t, e) t
#define IF_9(t, e) t
#define IF_10(t, e) t
#define IF_11(t, e) t
#define IF_12(t, e) t
#define IF_13(t, e) t
#define IF_14(t, e) t
#define IF_15(t, e) t
#define IF_16(t, e) t
#ifdef UG_COMPILE_SPIRV
#define LAYOUT_SAMPLER(s, b) layout(set = s, binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, set = s, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(push_constant, std140)

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) IF(loc, layout (location = loc) mod in type name, const type name = defaultValue)
		
	#define INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)

	#define OUTPUT(loc, type, name) IF(loc, layout (location = loc) out type name, type name)
	
	#define OUTPUT_MOD(loc, mod, type, name) IF(loc, layout (location = loc) mod out type name, type name)
	
	#define WINDING ccw

	#define LOCATION(loc) layout(location = loc) 
#else
	#extension GL_ARB_separate_shader_objects : require
	#extension GL_ARB_explicit_attrib_location : require
	#extension GL_ARB_shading_language_420pack : require

	#define LAYOUT_SAMPLER(s, b) layout(binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(std140, binding = 2)

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) mod in type name
		
	#define INPUT(loc, type, name, defaultValue) in type name

	#define OUTPUT(loc, type, name) out type name
	
	#define OUTPUT_MOD(loc, mod, type, name) mod out type name
	
	#define WINDING ccw

	#define LOCATION(loc)
#endif
/// END AUTOGENERATED HEADER

#ifndef UG_COMPILE_SPIRV
layout (triangle_strip, max_vertices = 8) out;
#endif

vec3[4] getVertices(vec2 dim, vec3 pos, vec3 tangent, vec3 binormal, vec3 scale) {
	return vec3[](
		pos + scale * (-.5 * dim.x * tangent),
		pos + scale * ( .5 * dim.x * tangent),
		pos + scale * (-.5 * dim.x * tangent + dim.y * binormal),
		pos + scale * ( .5 * dim.x * tangent + dim.y * binormal)
	);
}

vec3[4] getVertices(vec2 dim, vec3 pos, vec3 tangent, vec3 binormal, float scale) {
	return getVertices(dim, pos, tangent, binormal, vec3(scale));
}

vec3[4] getVerticesOH(vec4 coordsOH, float heightOH, vec3 pos, vec3 tangent, vec3 binormal, vec3 normal, vec3 scale) {
	return vec3[](
		pos + scale * (coordsOH[0] * tangent + coordsOH[1] * binormal + heightOH * normal),
		pos + scale * (coordsOH[2] * tangent + coordsOH[1] * binormal + heightOH * normal),
		pos + scale * (coordsOH[0] * tangent + coordsOH[3] * binormal + heightOH * normal),
		pos + scale * (coordsOH[2] * tangent + coordsOH[3] * binormal + heightOH * normal)
	);
}

vec3[4] getVerticesOH(vec4 coordsOH, float heightOH, vec3 pos, vec3 tangent, vec3 binormal, vec3 normal, float scale) {
	return getVerticesOH(coordsOH, heightOH, pos, tangent, binormal, normal, vec3(scale));
}

vec2[4] getTexCoords(vec4 texCoords[7], int faceIdx) {
	vec2 a = texCoords[faceIdx].xy;
	vec2 b = texCoords[faceIdx].zw;

	vec2 d = (a.x < b.x) == (a.y < b.y) ? vec2(b.x - a.x, .0) : vec2(.0, b.y - a.y);

	return vec2[](a, a + d, b - d, b);
}
