#version 150
/// BEGIN AUTOGENERATED HEADER
#define CONC(a,b) a##b

#define IF(c, t, e) CONC(IF_, c)(t, e)

#define IF_UNDEF(t, e) e
#define IF_0(t, e) t
#define IF_1(t, e) t
#define IF_2(t, e) t
#define IF_3(t, e) t
#define IF_4(t, e) t
#define IF_5(t, e) t
#define IF_6(t, e) t
#define IF_7(t, e) t
#define IF_8(t, e) t
#define IF_9(t, e) t
#define IF_10(t, e) t
#define IF_11(t, e) t
#define IF_12(t, e) t
#define IF_13(t, e) t
#define IF_14(t, e) t
#define IF_15(t, e) t
#define IF_16(t, e) t
// Workaround for intel HD:
#define IF_00(t, e) t
#ifdef UG_COMPILE_SPIRV
	#define gl_VertexID gl_VertexIndex

	#define LAYOUT_SAMPLER2(s, b) layout(set = s, binding = b)
	#define LAYOUT_SAMPLER(s, b) layout(set = s, binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, set = s, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(push_constant, std140)
	#define LAYOUT_STORAGE(s, b) layout(std140, set = s, binding = b) readonly restrict buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) IF(loc, layout (location = loc) mod in type name, const type name = defaultValue)
		
	#define INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)

	#define OUTPUT(loc, type, name) IF(loc, layout (location = loc) out type name, type name)
	
	#define OUTPUT_MOD(loc, mod, type, name) IF(loc, layout (location = loc) mod out type name, type name)
	
	#define WINDING ccw

	#define LOCATION(loc) layout(location = loc) 
#else
	#extension GL_ARB_separate_shader_objects : require
	#extension GL_ARB_explicit_attrib_location : require
	#extension GL_ARB_shading_language_420pack : require

#ifdef USE_SAMPLER2
	#define LAYOUT_SAMPLER2(s, b)
#else
	#define LAYOUT_SAMPLER2(s, b) layout(binding = b)
#endif

	#define LAYOUT_SAMPLER(s, b) layout(binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(std140, binding = 2)
	#define LAYOUT_STORAGE(s, b) layout(std140, binding = b) buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) mod in type name
		
	#define INPUT(loc, type, name, defaultValue) in type name

	#define OUTPUT(loc, type, name) out type name
	
	#define OUTPUT_MOD(loc, mod, type, name) mod out type name
	
	#define WINDING ccw

	#define LOCATION(loc)
#endif
/// END AUTOGENERATED HEADER
#ifndef UG_COMPILE_SPIRV
#extension GL_ARB_tessellation_shader : require
#endif

layout(quads, equal_spacing, cw) in;

LAYOUT_UBO(0, 10) uniform View {
	mat4 projView;
	mat4 projViewInverse;
	mat4 proj;
	mat4 projInverse;
	mat4 view;
	mat4 viewInverse;
	vec3 camPos;
	float lodFactor;
	float near;
	float far;
} u_view;

struct Billboard {
	vec4 texCoords[7];
	vec4 dimFadeIn;
	vec4 coordsOH;
	vec4 bbMinHeightOH;
	vec4 bbMax;
};

LAYOUT_UBO(1, 4) uniform VMaterial {
	Billboard billboards[16];
	vec2 fadeOutRanges[16];
	vec2 smoothLodRange;
} u_vmat;

LAYOUT_UBO(0, 6) uniform Light {
	vec3 lightDir;
	float lightScale;
	mat4 lightTransf;
	mat4 lightInvTransf;
	float ambientScale;
} u_light;

LOCATION(0) in VertexDataOut {
	vec3 position;
	vec4 normalScale;
	flat int index;
	float fadeOutAlpha;
	
	vec4 instColor;

	float fogFactor;
	vec3 extFactor;
	vec3 inScatt;
} inData[];

OUTPUT(DEPTH_LOC, float, depth);
OUTPUT_MOD(TC_LOC, centroid, vec3, texCoordAlpha);

void main() {
	vec3 vpos = inData[0].position.xyz;
	vec3 vnrml = inData[0].normalScale.xyz;
	float scale = inData[0].normalScale.w;
	int vindex = inData[0].index;
	float fadeOutAlpha = inData[0].fadeOutAlpha;

	vec2 dim = u_vmat.billboards[vindex].dimFadeIn.xy;
	vec2 fadeInAngle = u_vmat.billboards[vindex].dimFadeIn.zw;
	vec4 coordsOH = u_vmat.billboards[vindex].coordsOH;
	float heightOH = u_vmat.billboards[vindex].bbMinHeightOH.w;
	if (fadeOutAlpha <= .0) return;

	vec3 fadeScale = scale * vec3(fadeOutAlpha, fadeOutAlpha, 1.0);

	const float PI = 3.14159265;
	
	float offset = -dim.y * .05 * scale * u_view.projView[2][2];		// TODO coordsOH?

	float instanceRot = atan(vnrml.y, vnrml.x);

	bool thisTop = gl_TessCoord.y >= 2 / 3.0 - 0.01;
	bool thisFront = gl_TessCoord.y <= 1 / 3.0 + 0.01;

	vec3 binormal_ = vec3(.0, .0, 1.0);
	vec3 tangent_ = -normalize(cross(binormal_, u_light.lightDir));

	if (thisTop) {	
		vec2 coord = vec2(gl_TessCoord.x, 1-(gl_TessCoord.y - 2 / 3.0) * 3);	
		vec3 normal_ = vec3(.0, .0, 1.0);
		// vec3 tangent_ = vnrml;
		// vec3 binormal_ = cross(normal_, tangent_);

		binormal_ = tangent_;
		tangent_ = -normalize(u_light.lightDir);

		float xpos = (coordsOH[0] + coord.x * (coordsOH[2] - coordsOH[1]));
		float ypos = (coordsOH[1] + coord.y * (coordsOH[3] - coordsOH[1]));
		vec3 vertex = vpos + fadeScale * (xpos * tangent_ + ypos * binormal_ + heightOH * normal_); // coordOH
		
		vec4 texCoords = u_vmat.billboards[vindex].texCoords[6];
		vec2 a = texCoords.xy;
		vec2 b = texCoords.zw;
		vec2 coord2 = (a.x < b.x) == (a.y < b.y) ? coord : coord.yx;
		vec2 tc = a + coord2 * (b - a);

		texCoordAlpha = vec3(tc, 1.0);
		gl_Position = u_view.projView * vec4(vertex, 1.0);
		depth = gl_Position.z + offset;
		
#ifdef RESCALE_Z_POS
		gl_Position.z = (.5 * gl_Position.z + .5 * gl_Position.w);
#endif
#ifdef INVERT_Y
		gl_Position.y = -gl_Position.y;
#endif
	} else if (thisFront) {
		vec2 coord = vec2(gl_TessCoord.x, 1-gl_TessCoord.y * 3);

		float hAngle = atan(u_light.lightDir.y, u_light.lightDir.x) - instanceRot + PI / 6.0;		// [-pi, pi] - [0, 2*pi] + pi/6
		int j = int(12.0 + 3.0 * hAngle / PI) % 6;

		vec4 texCoords = u_vmat.billboards[vindex].texCoords[j];
		vec2 a = texCoords.xy;
		vec2 b = texCoords.zw;

		vec2 coord2 = (a.x < b.x) == (a.y < b.y) ? coord : coord.yx;
		vec3 vertex = vpos + fadeScale * ((coord.x - 0.5) * dim.x * tangent_ + coord.y * dim.y * binormal_);
		vec2 tc = a + coord2 * (b - a);

		texCoordAlpha = vec3(tc, 1.0);
		gl_Position = u_view.projView * vec4(vertex, 1.0);
		depth = gl_Position.z + offset;
		
#ifdef RESCALE_Z_POS
		gl_Position.z = (.5 * gl_Position.z + .5 * gl_Position.w);
#endif
#ifdef INVERT_Y
		gl_Position.y = -gl_Position.y;
#endif
	} else {
	
		gl_Position = u_view.projView * vec4(vpos, 1.0);
		gl_Position.z = -4.0;
		gl_Position.w = -4.0;
	}
}
