#version 150
/// BEGIN AUTOGENERATED HEADER
#define CONC(a,b) a##b

#define IF(c, t, e) CONC(IF_, c)(t, e)

#define IF_UNDEF(t, e) e
#define IF_0(t, e) t
#define IF_1(t, e) t
#define IF_2(t, e) t
#define IF_3(t, e) t
#define IF_4(t, e) t
#define IF_5(t, e) t
#define IF_6(t, e) t
#define IF_7(t, e) t
#define IF_8(t, e) t
#define IF_9(t, e) t
#define IF_10(t, e) t
#define IF_11(t, e) t
#define IF_12(t, e) t
#define IF_13(t, e) t
#define IF_14(t, e) t
#define IF_15(t, e) t
#define IF_16(t, e) t
// Workaround for intel HD:
#define IF_00(t, e) t
#ifdef UG_COMPILE_SPIRV
	#define gl_VertexID gl_VertexIndex

	#define LAYOUT_SAMPLER2(s, b) layout(set = s, binding = b)
	#define LAYOUT_SAMPLER(s, b) layout(set = s, binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, set = s, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(push_constant, std140)
	#define LAYOUT_STORAGE(s, b) layout(std140, set = s, binding = b) readonly restrict buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) IF(loc, layout (location = loc) mod in type name, const type name = defaultValue)
		
	#define INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)

	#define OUTPUT(loc, type, name) IF(loc, layout (location = loc) out type name, type name)
	
	#define OUTPUT_MOD(loc, mod, type, name) IF(loc, layout (location = loc) mod out type name, type name)
	
	#define WINDING ccw

	#define LOCATION(loc) layout(location = loc) 
#else
	#extension GL_ARB_separate_shader_objects : require
	#extension GL_ARB_explicit_attrib_location : require
	#extension GL_ARB_shading_language_420pack : require

#ifdef USE_SAMPLER2
	#define LAYOUT_SAMPLER2(s, b)
#else
	#define LAYOUT_SAMPLER2(s, b) layout(binding = b)
#endif

	#define LAYOUT_SAMPLER(s, b) layout(binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(std140, binding = 2)
	#define LAYOUT_STORAGE(s, b) layout(std140, binding = b) buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) mod in type name
		
	#define INPUT(loc, type, name, defaultValue) in type name

	#define OUTPUT(loc, type, name) out type name
	
	#define OUTPUT_MOD(loc, mod, type, name) mod out type name
	
	#define WINDING ccw

	#define LOCATION(loc)
#endif
/// END AUTOGENERATED HEADER
#ifndef UG_COMPILE_SPIRV
#extension GL_ARB_tessellation_shader : require
#endif

layout (vertices = 1) out;

layout(location = 0) in vec3 position[];
layout(location = 1) in vec4 normalScale[];
layout(location = 2) flat in int index[];
layout(location = 3) in float fadeOutAlpha[];
layout(location = 4) in vec4 instColor[];
layout(location = 5) in float fogFactor[];
layout(location = 6) in vec3 extFactor[];
layout(location = 7) in vec3 inScatt[];

LOCATION(0) out VertexDataOut {
	vec3 position;
	vec4 normalScale;
	flat int index;
	float fadeOutAlpha;
	
	vec4 instColor;

	float fogFactor;
	vec3 extFactor;
	vec3 inScatt;
} outData[];

void main() {
	gl_TessLevelInner[0] = 1.0;
	gl_TessLevelInner[1] = 3.0;
	gl_TessLevelOuter[0] = 3.0;
	gl_TessLevelOuter[1] = 1.0;
	gl_TessLevelOuter[2] = 3.0;
	gl_TessLevelOuter[3] = 1.0;
	if (fadeOutAlpha[gl_InvocationID] <= .0) {
		gl_TessLevelOuter[0] = 0.0; // Discard patch
		return;
	}

 	// gl_out[gl_InvocationID].gl_Position = gl_in[gl_InvocationID].gl_Position;

	outData[gl_InvocationID].position = position[gl_InvocationID];
	outData[gl_InvocationID].normalScale = normalScale[gl_InvocationID];
	outData[gl_InvocationID].index = index[gl_InvocationID];
	outData[gl_InvocationID].fadeOutAlpha = fadeOutAlpha[gl_InvocationID];
	outData[gl_InvocationID].instColor = instColor[gl_InvocationID];

	outData[gl_InvocationID].fogFactor = fogFactor[gl_InvocationID];
	outData[gl_InvocationID].extFactor = extFactor[gl_InvocationID];
	outData[gl_InvocationID].inScatt = inScatt[gl_InvocationID];
}
