#version 150
/// BEGIN AUTOGENERATED HEADER
#define CONC(a,b) a##b

#define IF(c, t, e) CONC(IF_, c)(t, e)

#define IF_UNDEF(t, e) e
#define IF_0(t, e) t
#define IF_1(t, e) t
#define IF_2(t, e) t
#define IF_3(t, e) t
#define IF_4(t, e) t
#define IF_5(t, e) t
#define IF_6(t, e) t
#define IF_7(t, e) t
#define IF_8(t, e) t
#define IF_9(t, e) t
#define IF_10(t, e) t
#define IF_11(t, e) t
#define IF_12(t, e) t
#define IF_13(t, e) t
#define IF_14(t, e) t
#define IF_15(t, e) t
#define IF_16(t, e) t
// Workaround for intel HD:
#define IF_00(t, e) t
#ifdef UG_COMPILE_SPIRV
	#define gl_VertexID gl_VertexIndex

	#define LAYOUT_SAMPLER2(s, b) layout(set = s, binding = b)
	#define LAYOUT_SAMPLER(s, b) layout(set = s, binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, set = s, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(push_constant, std140)
	#define LAYOUT_STORAGE(s, b) layout(std140, set = s, binding = b) readonly restrict buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) IF(loc, layout (location = loc) mod in type name, const type name = defaultValue)
		
	#define INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)

	#define OUTPUT(loc, type, name) IF(loc, layout (location = loc) out type name, type name)
	
	#define OUTPUT_MOD(loc, mod, type, name) IF(loc, layout (location = loc) mod out type name, type name)
	
	#define WINDING ccw

	#define LOCATION(loc) layout(location = loc) 
#else
	#extension GL_ARB_separate_shader_objects : require
	#extension GL_ARB_explicit_attrib_location : require
	#extension GL_ARB_shading_language_420pack : require

#ifdef USE_SAMPLER2
	#define LAYOUT_SAMPLER2(s, b)
#else
	#define LAYOUT_SAMPLER2(s, b) layout(binding = b)
#endif

	#define LAYOUT_SAMPLER(s, b) layout(binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(std140, binding = 2)
	#define LAYOUT_STORAGE(s, b) layout(std140, binding = b) buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) mod in type name
		
	#define INPUT(loc, type, name, defaultValue) in type name

	#define OUTPUT(loc, type, name) out type name
	
	#define OUTPUT_MOD(loc, mod, type, name) mod out type name
	
	#define WINDING ccw

	#define LOCATION(loc)
#endif
/// END AUTOGENERATED HEADER
// #extension GL_ARB_shader_draw_parameters : require

#ifndef UG_COMPILE_SPIRV
#	extension GL_ARB_shader_storage_buffer_object : require
#endif


#ifdef UG_COMPILE_SPIRV
#	define gl_VertexID gl_VertexIndex
#endif


struct Billboard {
	vec4 texCoords[7];
	vec4 dimFadeIn;
	vec4 coordsOH;
	vec4 bbMinHeightOH;
	vec4 bbMax;
};

LAYOUT_UBO(1, 4) uniform VMaterial {
	Billboard billboards[16];
	vec2 fadeOutRanges[16];
	vec2 smoothLodRange;
} u_vmat;

LAYOUT_UBO(0, 10) uniform View {
	mat4 projView;
	mat4 projViewInverse;
	mat4 proj;
	mat4 projInverse;
	mat4 view;
	mat4 viewInverse;
	vec3 camPos;
	float lodFactor;
	float near;
	float far;
} u_view;

LAYOUT_STORAGE(3, 0) Pos {
	vec4 positionIdx[];
} u_pos;

LAYOUT_STORAGE(3, 1) Normal {
	vec4 normalObjIdx[];
} u_normal;

VERTEX_INPUT(INSTATTR_MDL_LOC, mat4, instAttrModel, mat4());
VERTEX_INPUT(INSTATTR_COL_LOC, vec4, instAttrColor, vec4(1.0));

OUTPUT(POS_LOC, vec4, posAmbient);
OUTPUT(NRML_LOC, vec3, normal_);
OUTPUT(TNGT_LOC, vec3, tangent_);
OUTPUT(BINORM_LOC, vec3, binormal_);
OUTPUT_MOD(TC_LOC, centroid, vec3, texCoordAlpha);
OUTPUT(COL_LOC, vec4, color);
OUTPUT(OFFSET_LOC, vec3, offset);
OUTPUT_MOD(MATIDX_LOC, flat, int, matIndex);

const vec3[8] of = vec3[8](
	vec3(.0, .0, .0),
	vec3(1.0, .0, .0),
	vec3(.0, 1.0, .0),
	vec3(1.0, 1.0, .0),
	
	vec3(.0, .0, .0),
	vec3(1.0, .0, .0),
	vec3(.0, 1.0, .0),
	vec3(1.0, 1.0, .0)
);

float calcDistToBox(vec3 p, vec3 box[2]);
float compFadeOutAlpha(float distance, vec2 range);
void calcFogFactor(vec3 pos);
void getBufTexInstAttrsColor(inout vec4 color, float objIdx);
float calcDist(vec3 refPos, vec3 pos, vec3 nrml, float scale, vec3 box[2]);
vec3[4] getVertices(vec2 dim, vec3 pos, vec3 tangent, vec3 binormal, float scale);
vec3[4] getVerticesOH(vec4 coordsOH, float heightOH, vec3 pos, vec3 tangent, vec3 binormal, vec3 normal, float scale);
vec2[4] getTexCoords(vec4 texCoords[7], int faceIdx);

void main() {
	int id = gl_VertexID; // - gl_BaseVertexARB;
	int elem = id % 6;
	bool front = id % 12 < 6 ? true : false;
	int genInstance = id / 12;
	int vertex = elem; //indices[elem];

	vec3 nrml = vec3(instAttrModel * vec4(u_normal.normalObjIdx[genInstance].xyz, .0));
	int idx = 0; // outData.index = idx; // vindex

	vec3 vpos = vec3(instAttrModel * vec4(u_pos.positionIdx[genInstance].xyz, 1.0));
	vec4 normalScale = vec4(normalize(nrml), length(nrml));

	vec4 texCoords[7] = u_vmat.billboards[idx].texCoords;

	vec2 fadeInAngle = u_vmat.billboards[idx].dimFadeIn.zw;
	vec2 dim = u_vmat.billboards[idx].dimFadeIn.xy;
	vec4 coordsOH = u_vmat.billboards[idx].coordsOH;
	float heightOH = u_vmat.billboards[idx].bbMinHeightOH.w;

	vec3 bbMin = u_vmat.billboards[idx].bbMinHeightOH.xyz;
	vec3 bbMax = u_vmat.billboards[idx].bbMax.xyz;

	vec3 vnrml = normalScale.xyz;
	float scale = normalScale.w;

	float distToCam = calcDist(u_view.viewInverse[3].xyz, vpos, vnrml, scale, vec3[](bbMin, bbMax));
	float fadeOutAlpha = compFadeOutAlpha(distToCam, u_vmat.fadeOutRanges[idx]* vec2(u_view.lodFactor, 1.0 / u_view.lodFactor));
	if (fadeOutAlpha <= .0) {
		gl_Position = vec4(0.0, 0.0, 0.0, 0.0);
		return;
	}

	const float PI = 3.14159265;

	vec3 vertexToCam = u_view.viewInverse[3].xyz - vpos;

	float angle = atan(vertexToCam.z / length(vertexToCam.xy));
	float instanceRot = atan(vnrml.y, vnrml.x);

	color = instAttrColor;
	getBufTexInstAttrsColor(color, u_normal.normalObjIdx[genInstance].w);
	matIndex = idx;
	calcFogFactor(vpos);

	if (angle < fadeInAngle.x && front) {	
		binormal_ = vec3(.0, .0, 1.0);
		tangent_ = normalize(cross(binormal_, vertexToCam));
		normal_ = cross(tangent_, binormal_);

		float hAngle = atan(vertexToCam.y, vertexToCam.x) - instanceRot + PI / 6.0;		// [-pi, pi] - [0, 2*pi] + pi/6
		int j = int(12.0 + 3.0 * hAngle / PI) % 6;

		float s = clamp((angle - fadeInAngle.x) / (fadeInAngle.y - fadeInAngle.x), .0, 1.0);
		float finalAlpha = fadeOutAlpha * min(s * 2.0, 1.0);

		vec3[4] vertices = getVertices(dim, vpos, tangent_, binormal_, scale);
		vec2[4] tcs = getTexCoords(texCoords, j);


		posAmbient = vec4(vertices[vertex], /*attrModel[0][3][3]*/ 1.0);
		texCoordAlpha = vec3(tcs[vertex], finalAlpha);	
		//calcFogFactor(vertices[i]);
		offset = of[vertex];
		gl_Position = u_view.projView * vec4(vertices[vertex], 1.0);
#ifdef RESCALE_Z_POS
		gl_Position.z = (.5 * gl_Position.z + .5 * gl_Position.w);
#endif
#ifdef INVERT_Y
	gl_Position.y = -gl_Position.y;
#endif
	} else if (angle >= fadeInAngle.y && !front) {	
		normal_ = vec3(.0, .0, 1.0);
		tangent_ = vnrml;
		binormal_ = cross(normal_, tangent_);

		float s = clamp((angle - fadeInAngle.x) / (fadeInAngle.y - fadeInAngle.x), .0, 1.0);
		float finalAlpha = fadeOutAlpha * min(2.0 * (1.0 - s), 1.0);

		vec3[4] vertices = getVerticesOH(coordsOH, heightOH, vpos, tangent_, binormal_, normal_, scale);
		vec2[4] tcs = getTexCoords(texCoords, 6);

		posAmbient = vec4(vertices[vertex], /*attrModel[0][3][3]*/ 1.0);
		texCoordAlpha = vec3(tcs[vertex], finalAlpha);    
		//calcFogFactor(vertices[i]);
		offset = vec3(of[vertex + 4].xy, instanceRot);
		gl_Position = u_view.projView * vec4(vertices[vertex], 1.0);
#ifdef RESCALE_Z_POS
		gl_Position.z = (.5 * gl_Position.z + .5 * gl_Position.w);
#endif
#ifdef INVERT_Y
	gl_Position.y = -gl_Position.y;
#endif
	} else {
		gl_Position = vec4(0.0, 0.0, 0.0, 0.0);
	}
}
