#version 150
/// BEGIN AUTOGENERATED HEADER
#define CONC(a,b) a##b

#define IF(c, t, e) CONC(IF_, c)(t, e)

#define IF_UNDEF(t, e) e
#define IF_0(t, e) t
#define IF_1(t, e) t
#define IF_2(t, e) t
#define IF_3(t, e) t
#define IF_4(t, e) t
#define IF_5(t, e) t
#define IF_6(t, e) t
#define IF_7(t, e) t
#define IF_8(t, e) t
#define IF_9(t, e) t
#define IF_10(t, e) t
#define IF_11(t, e) t
#define IF_12(t, e) t
#define IF_13(t, e) t
#define IF_14(t, e) t
#define IF_15(t, e) t
#define IF_16(t, e) t
// Workaround for intel HD:
#define IF_00(t, e) t
#ifdef UG_COMPILE_SPIRV
	#define gl_VertexID gl_VertexIndex

	#define LAYOUT_SAMPLER2(s, b) layout(set = s, binding = b)
	#define LAYOUT_SAMPLER(s, b) layout(set = s, binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, set = s, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(push_constant, std140)
	#define LAYOUT_STORAGE(s, b) layout(std140, set = s, binding = b) readonly restrict buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) IF(loc, layout (location = loc) mod in type name, const type name = defaultValue)
		
	#define INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)

	#define OUTPUT(loc, type, name) IF(loc, layout (location = loc) out type name, type name)
	
	#define OUTPUT_MOD(loc, mod, type, name) IF(loc, layout (location = loc) mod out type name, type name)
	
	#define WINDING ccw

	#define LOCATION(loc) layout(location = loc) 
#else
	#extension GL_ARB_separate_shader_objects : require
	#extension GL_ARB_explicit_attrib_location : require
	#extension GL_ARB_shading_language_420pack : require

#ifdef USE_SAMPLER2
	#define LAYOUT_SAMPLER2(s, b)
#else
	#define LAYOUT_SAMPLER2(s, b) layout(binding = b)
#endif

	#define LAYOUT_SAMPLER(s, b) layout(binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(std140, binding = 2)
	#define LAYOUT_STORAGE(s, b) layout(std140, binding = b) buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) mod in type name
		
	#define INPUT(loc, type, name, defaultValue) in type name

	#define OUTPUT(loc, type, name) out type name
	
	#define OUTPUT_MOD(loc, mod, type, name) mod out type name
	
	#define WINDING ccw

	#define LOCATION(loc)
#endif
/// END AUTOGENERATED HEADER

layout (points) in;
layout (triangle_strip, max_vertices = 8) out;

LAYOUT_UBO(0, 10) uniform View {
	mat4 projView;
	mat4 projViewInverse;
	mat4 proj;
	mat4 projInverse;
	mat4 view;
	mat4 viewInverse;
	vec3 camPos;
	float lodFactor;
	float near;
	float far;
} u_view;

LAYOUT_UBO(0, 6) uniform Light {
	vec3 lightDir;
	float lightScale;
	mat4 lightTransf;
	mat4 lightInvTransf;
	float ambientScale;
} u_light;

struct Billboard {
	vec4 texCoords[7];
	vec4 dimFadeIn;
	vec4 coordsOH;
	vec4 bbMinHeightOH;
	vec4 bbMax;
};

LAYOUT_UBO(1, 4) uniform VMaterial {
	Billboard billboards[16];
	vec2 fadeOutRanges[16];
	vec2 smoothLodRange;
} u_vmat;

LOCATION(0) in VertexData {
	vec3 position;
	vec4 normalScale;
	flat int index;

	vec4 instColor;

	vec4 texCoords[7];
	vec4 dimFadeIn;
	vec4 coordsOH;
	float heightOH;

	vec3 bbMin;
	vec3 bbMax;
} inData[];

OUTPUT(DEPTH_LOC, float, depth);
OUTPUT_MOD(TC_LOC, centroid, vec3, texCoordAlpha);
OUTPUT_MOD(MATIDX_LOC, flat, int, matIndex);

float calcDist(vec3 refPos, vec3 pos, vec3 nrml, float scale, vec3 box[2]);
float compFadeOutAlpha(float distance, vec2 range);
vec3[4] getVertices(vec2 dim, vec3 pos, vec3 tangent, vec3 binormal, vec3 scale);
vec3[4] getVerticesOH(vec4 coordsOH, float heightOH, vec3 pos, vec3 tangent, vec3 binormal, vec3 normal, vec3 scale);
vec2[4] getTexCoords(vec4 texCoords[7], int faceIdx);

void main() {
	vec3 vpos = inData[0].position;
	vec3 vnrml = inData[0].normalScale.xyz;
	float scale = inData[0].normalScale.w;
	int vindex = inData[0].index;

	float distToCam = calcDist(u_view.camPos, vpos, vnrml, scale, vec3[](inData[0].bbMin, inData[0].bbMax));
	float fadeOutAlpha = compFadeOutAlpha(distToCam, u_vmat.fadeOutRanges[vindex] * vec2(u_view.lodFactor, 1.0 / u_view.lodFactor));
	if (fadeOutAlpha <= .0) return;

	vec3 fadeScale = scale * vec3(fadeOutAlpha, fadeOutAlpha, 1.0);

	vec4 texCoords[7] = inData[0].texCoords;
	vec2 dim = inData[0].dimFadeIn.xy;
	vec4 coordsOH = inData[0].coordsOH;
	float heightOH = inData[0].heightOH;

	const float PI = 3.14159265;

	float offset = -dim.y * .5 * scale * u_view.projView[2][2];		// TODO coordsOH?

	matIndex = vindex;

	vec3 binormal = vec3(.0, .0, 1.0);
	vec3 tangent = normalize(cross(binormal, u_light.lightDir));

	float instanceRot = atan(vnrml.y, vnrml.x);
	float hAngle = atan(u_light.lightDir.y, u_light.lightDir.x) - instanceRot + PI / 6.0;		// [-pi, pi] - [0, 2*pi] + pi/6
	int j = int(12.0 + 3.0 * hAngle / PI) % 6;

	vec3[4] vertices = getVertices(dim, vpos, tangent, binormal, fadeScale);
	vec2[4] tcs = getTexCoords(texCoords, j);

	for (int i = 0; i < 4; ++i) {
		texCoordAlpha = vec3(tcs[i], 1.0);
		gl_Position = u_view.projView * vec4(vertices[i], 1.0);
		depth = gl_Position.z + offset;
#ifdef UG_COMPILE_SPIRV
		matIndex = vindex;
#endif
#ifdef RESCALE_Z_POS // Standard says vertex outputs from geometry should be re-emitted for each vertex
		gl_Position.z = (.5 * gl_Position.z + .5 * gl_Position.w);
#endif
#ifdef INVERT_Y
		gl_Position.y = -gl_Position.y;
#endif
		EmitVertex();
	}
	EndPrimitive();

	vec3 normal = vec3(.0, .0, 1.0);
	tangent = vnrml;
	binormal = cross(normal, tangent);

	vertices = getVerticesOH(coordsOH, heightOH, vpos, tangent, binormal, normal, fadeScale);
	tcs = getTexCoords(texCoords, 6);

	for (int i = 0; i < 4; ++i) {	
		texCoordAlpha = vec3(tcs[i], 1.0);    
		gl_Position = u_view.projView * vec4(vertices[i], 1.0);
		depth = gl_Position.z + offset;
#ifdef UG_COMPILE_SPIRV
		matIndex = vindex;
#endif
#ifdef RESCALE_Z_POS
		gl_Position.z = (.5 * gl_Position.z + .5 * gl_Position.w);
#endif
#ifdef INVERT_Y
		gl_Position.y = -gl_Position.y;
#endif
		EmitVertex();
	}
	EndPrimitive();
}
