#version 150
/// BEGIN AUTOGENERATED HEADER
#define CONC(a,b) a##b

#define IF(c, t, e) CONC(IF_, c)(t, e)

#define IF_UNDEF(t, e) e
#define IF_0(t, e) t
#define IF_1(t, e) t
#define IF_2(t, e) t
#define IF_3(t, e) t
#define IF_4(t, e) t
#define IF_5(t, e) t
#define IF_6(t, e) t
#define IF_7(t, e) t
#define IF_8(t, e) t
#define IF_9(t, e) t
#define IF_10(t, e) t
#define IF_11(t, e) t
#define IF_12(t, e) t
#define IF_13(t, e) t
#define IF_14(t, e) t
#define IF_15(t, e) t
#define IF_16(t, e) t
// Workaround for intel HD:
#define IF_00(t, e) t
#ifdef UG_COMPILE_SPIRV
	#define gl_VertexID gl_VertexIndex

	#define LAYOUT_SAMPLER2(s, b) layout(set = s, binding = b)
	#define LAYOUT_SAMPLER(s, b) layout(set = s, binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, set = s, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(push_constant, std140)
	#define LAYOUT_STORAGE(s, b) layout(std140, set = s, binding = b) readonly restrict buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) IF(loc, layout (location = loc) mod in type name, const type name = defaultValue)
		
	#define INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)

	#define OUTPUT(loc, type, name) IF(loc, layout (location = loc) out type name, type name)
	
	#define OUTPUT_MOD(loc, mod, type, name) IF(loc, layout (location = loc) mod out type name, type name)
	
	#define WINDING ccw

	#define LOCATION(loc) layout(location = loc) 
#else
	#extension GL_ARB_separate_shader_objects : require
	#extension GL_ARB_explicit_attrib_location : require
	#extension GL_ARB_shading_language_420pack : require

#ifdef USE_SAMPLER2
	#define LAYOUT_SAMPLER2(s, b)
#else
	#define LAYOUT_SAMPLER2(s, b) layout(binding = b)
#endif

	#define LAYOUT_SAMPLER(s, b) layout(binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(std140, binding = 2)
	#define LAYOUT_STORAGE(s, b) layout(std140, binding = b) buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) mod in type name
		
	#define INPUT(loc, type, name, defaultValue) in type name

	#define OUTPUT(loc, type, name) out type name
	
	#define OUTPUT_MOD(loc, mod, type, name) mod out type name
	
	#define WINDING ccw

	#define LOCATION(loc)
#endif
/// END AUTOGENERATED HEADER
// #extension GL_ARB_shader_draw_parameters : require

#ifndef UG_COMPILE_SPIRV
#	extension GL_ARB_shader_storage_buffer_object : require
#endif


struct Billboard {
	vec4 texCoords[7];
	vec4 dimFadeIn;
	vec4 coordsOH;
	vec4 bbMinHeightOH;
	vec4 bbMax;
};

LAYOUT_UBO(1, 4) uniform VMaterial {
	Billboard billboards[16];
	vec2 fadeOutRanges[16];
	vec2 smoothLodRange;
} u_vmat;

LAYOUT_UBO(0, 6) uniform Light {
	vec3 lightDir;
	float lightScale;
	mat4 lightTransf;
	mat4 lightInvTransf;
	float ambientScale;
} u_light;

LAYOUT_UBO(0, 10) uniform View {
	mat4 projView;
	mat4 projViewInverse;
	mat4 proj;
	mat4 projInverse;
	mat4 view;
	mat4 viewInverse;
	vec3 camPos;
	float lodFactor;
	float near;
	float far;
} u_view;

LAYOUT_STORAGE(3, 0) Pos {
	vec4 positionIdx[];
} u_pos;

LAYOUT_STORAGE(3, 1) Normal {
	vec4 normal[];
} u_normal;

VERTEX_INPUT(INSTATTR_MDL_LOC, mat4, instAttrModel, mat4());

OUTPUT(DEPTH_LOC, float, depth);
OUTPUT_MOD(TC_LOC, centroid, vec3, texCoordAlpha);
OUTPUT_MOD(MATIDX_LOC, flat, int, matIndex);

const vec3[8] of = vec3[8](
	vec3(.0, .0, .0),
	vec3(1.0, .0, .0),
	vec3(.0, 1.0, .0),
	vec3(1.0, 1.0, .0),
	
	vec3(.0, .0, .0),
	vec3(1.0, .0, .0),
	vec3(.0, 1.0, .0),
	vec3(1.0, 1.0, .0)
);

float calcDistToBox(vec3 p, vec3 box[2]);
float compFadeOutAlpha(float distance, vec2 range);
void calcFogFactor(vec3 pos);
float calcDist(vec3 refPos, vec3 pos, vec3 nrml, float scale, vec3 box[2]);
vec3[4] getVertices(vec2 dim, vec3 pos, vec3 tangent, vec3 binormal, vec3 scale);
vec3[4] getVerticesOH(vec4 coordsOH, float heightOH, vec3 pos, vec3 tangent, vec3 binormal, vec3 normal, vec3 scale);
vec2[4] getTexCoords(vec4 texCoords[7], int faceIdx);

void main() {
	int id = gl_VertexID; // - gl_BaseVertexARB;
	int elem = id % 6;
	bool front = id % 12 < 6 ? true : false;
	int genInstance = id / 12;
	int vertex = elem; 

	vec3 nrml = vec3(instAttrModel * vec4(u_normal.normal[genInstance].xyz, .0));
	matIndex = 0; // outData.index = idx; // vindex

	vec3 vpos = vec3(instAttrModel * vec4(u_pos.positionIdx[genInstance].xyz, 1.0));
	vec4 normalScale = vec4(normalize(nrml), length(nrml));

	vec4 texCoords[7] = u_vmat.billboards[matIndex].texCoords;

	vec2 fadeInAngle = u_vmat.billboards[matIndex].dimFadeIn.zw;
	vec2 dim = u_vmat.billboards[matIndex].dimFadeIn.xy;
	vec4 coordsOH = u_vmat.billboards[matIndex].coordsOH;
	float heightOH = u_vmat.billboards[matIndex].bbMinHeightOH.w;

	vec3 bbMin = u_vmat.billboards[matIndex].bbMinHeightOH.xyz;
	vec3 bbMax = u_vmat.billboards[matIndex].bbMax.xyz;

	vec3 vnrml = normalScale.xyz;
	float scale = normalScale.w;

	float distToCam = calcDist(u_view.camPos, vpos, vnrml, scale, vec3[](bbMin, bbMax));
	float fadeOutAlpha = compFadeOutAlpha(distToCam, u_vmat.fadeOutRanges[matIndex] * vec2(u_view.lodFactor, 1.0 / u_view.lodFactor));
	if (fadeOutAlpha <= .0) {
		gl_Position = vec4(0.0, 0.0, 0.0, 0.0);
		return;
	}

	vec3 fadeScale = scale * vec3(fadeOutAlpha, fadeOutAlpha, 1.0);

	const float PI = 3.14159265;

	float offset = -dim.y * .5 * scale * u_view.projView[2][2];		// TODO coordsOH?

	if (front) {	
		vec3 binormal_ = vec3(.0, .0, 1.0);
		vec3 tangent_ = normalize(cross(binormal_, u_light.lightDir));

		float instanceRot = atan(vnrml.y, vnrml.x);
		float hAngle = atan(u_light.lightDir.y, u_light.lightDir.x) - instanceRot + PI / 6.0;		// [-pi, pi] - [0, 2*pi] + pi/6
		int j = int(12.0 + 3.0 * hAngle / PI) % 6;

		vec3[4] vertices = getVertices(dim, vpos, tangent_, binormal_, fadeScale);
		vec2[4] tcs = getTexCoords(texCoords, j);

		texCoordAlpha = vec3(tcs[vertex], 1.0);
		gl_Position = u_view.projView * vec4(vertices[vertex], 1.0);
		depth = gl_Position.z + offset;
#ifdef RESCALE_Z_POS
		gl_Position.z = (.5 * gl_Position.z + .5 * gl_Position.w);
#endif
#ifdef INVERT_Y
		gl_Position.y = -gl_Position.y;
#endif
	} else if (!front) {	
		vec3 normal_ = vec3(.0, .0, 1.0);
		vec3 tangent_ = vnrml;
		vec3 binormal_ = cross(normal_, tangent_);

		vec3[4] vertices = getVerticesOH(coordsOH, heightOH, vpos, tangent_, binormal_, normal_, fadeScale);
		vec2[4] tcs = getTexCoords(texCoords, 6);

		texCoordAlpha = vec3(tcs[vertex], 1.0);
		gl_Position = u_view.projView * vec4(vertices[vertex], 1.0);
		depth = gl_Position.z + offset;
#ifdef RESCALE_Z_POS
		gl_Position.z = (.5 * gl_Position.z + .5 * gl_Position.w);
#endif
#ifdef INVERT_Y
		gl_Position.y = -gl_Position.y;
#endif
	} else {
		gl_Position = vec4(0.0, 0.0, 0.0, 0.0);
	}
}
