#version 150
/// BEGIN AUTOGENERATED HEADER
#define CONC(a,b) a##b

#define IF(c, t, e) CONC(IF_, c)(t, e)

#define IF_UNDEF(t, e) e
#define IF_0(t, e) t
#define IF_1(t, e) t
#define IF_2(t, e) t
#define IF_3(t, e) t
#define IF_4(t, e) t
#define IF_5(t, e) t
#define IF_6(t, e) t
#define IF_7(t, e) t
#define IF_8(t, e) t
#define IF_9(t, e) t
#define IF_10(t, e) t
#define IF_11(t, e) t
#define IF_12(t, e) t
#define IF_13(t, e) t
#define IF_14(t, e) t
#define IF_15(t, e) t
#define IF_16(t, e) t
// Workaround for intel HD:
#define IF_00(t, e) t
#ifdef UG_COMPILE_SPIRV
	#define gl_VertexID gl_VertexIndex

	#define LAYOUT_SAMPLER2(s, b) layout(set = s, binding = b)
	#define LAYOUT_SAMPLER(s, b) layout(set = s, binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, set = s, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(push_constant, std140)
	#define LAYOUT_STORAGE(s, b) layout(std140, set = s, binding = b) readonly restrict buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) IF(loc, layout (location = loc) mod in type name, const type name = defaultValue)
		
	#define INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)

	#define OUTPUT(loc, type, name) IF(loc, layout (location = loc) out type name, type name)
	
	#define OUTPUT_MOD(loc, mod, type, name) IF(loc, layout (location = loc) mod out type name, type name)
	
	#define WINDING ccw

	#define LOCATION(loc) layout(location = loc) 
#else
	#extension GL_ARB_separate_shader_objects : require
	#extension GL_ARB_explicit_attrib_location : require
	#extension GL_ARB_shading_language_420pack : require

#ifdef USE_SAMPLER2
	#define LAYOUT_SAMPLER2(s, b)
#else
	#define LAYOUT_SAMPLER2(s, b) layout(binding = b)
#endif

	#define LAYOUT_SAMPLER(s, b) layout(binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(std140, binding = 2)
	#define LAYOUT_STORAGE(s, b) layout(std140, binding = b) buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) mod in type name
		
	#define INPUT(loc, type, name, defaultValue) in type name

	#define OUTPUT(loc, type, name) out type name
	
	#define OUTPUT_MOD(loc, mod, type, name) mod out type name
	
	#define WINDING ccw

	#define LOCATION(loc)
#endif
/// END AUTOGENERATED HEADER

struct Billboard {
	vec4 texCoords[7];
	vec4 dimFadeIn;
	vec4 coordsOH;
	vec4 bbMinHeightOH;
	vec4 bbMax;
};

LAYOUT_UBO(1, 4) uniform VMaterial {
	Billboard billboards[16];
	vec2 fadeOutRanges[16];
	vec2 smoothLodRange;
} u_vmat;

VERTEX_INPUT(ATTR_POS_LOC, vec4, attrPositionIdx, vec4(1.0));
VERTEX_INPUT(ATTR_NRML_LOC, vec3, attrNormal, vec3(1.0));

VERTEX_INPUT(INSTATTR_MDL_LOC, mat4, instAttrModel, mat4());

LOCATION(0) out VertexData {
	vec3 position;
	vec4 normalScale;
	flat int index;

	vec4 instColor;

	vec4 texCoords[7];
	vec4 dimFadeIn;
	vec4 coordsOH;
	float heightOH;
	
	vec3 bbMin;
	vec3 bbMax;
} outData;

void main() {
	vec3 nrml = vec3(instAttrModel * vec4(attrNormal, .0));

	outData.position = vec3(instAttrModel * vec4(attrPositionIdx.xyz, 1.0));
	outData.normalScale = vec4(normalize(nrml), length(nrml));
	outData.index = 0;

	//outData.texCoords = u_vmat.billboards[0].texCoords;
	outData.texCoords[0] = u_vmat.billboards[0].texCoords[0];
	outData.texCoords[1] = u_vmat.billboards[0].texCoords[1];
	outData.texCoords[2] = u_vmat.billboards[0].texCoords[2];
	outData.texCoords[3] = u_vmat.billboards[0].texCoords[3];
	outData.texCoords[4] = u_vmat.billboards[0].texCoords[4];
	outData.texCoords[5] = u_vmat.billboards[0].texCoords[5];
	outData.texCoords[6] = u_vmat.billboards[0].texCoords[6];
	outData.dimFadeIn = u_vmat.billboards[0].dimFadeIn;
	outData.coordsOH = u_vmat.billboards[0].coordsOH;
	outData.heightOH = u_vmat.billboards[0].bbMinHeightOH.w;

	outData.bbMin = u_vmat.billboards[0].bbMinHeightOH.xyz;
	outData.bbMax = u_vmat.billboards[0].bbMax.xyz;
}
