#version 150
/// BEGIN AUTOGENERATED HEADER
#define CONC(a,b) a##b

#define IF(c, t, e) CONC(IF_, c)(t, e)

#define IF_UNDEF(t, e) e
#define IF_0(t, e) t
#define IF_1(t, e) t
#define IF_2(t, e) t
#define IF_3(t, e) t
#define IF_4(t, e) t
#define IF_5(t, e) t
#define IF_6(t, e) t
#define IF_7(t, e) t
#define IF_8(t, e) t
#define IF_9(t, e) t
#define IF_10(t, e) t
#define IF_11(t, e) t
#define IF_12(t, e) t
#define IF_13(t, e) t
#define IF_14(t, e) t
#define IF_15(t, e) t
#define IF_16(t, e) t
// Workaround for intel HD:
#define IF_00(t, e) t
#ifdef UG_COMPILE_SPIRV
	#define gl_VertexID gl_VertexIndex

	#define LAYOUT_SAMPLER2(s, b) layout(set = s, binding = b)
	#define LAYOUT_SAMPLER(s, b) layout(set = s, binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, set = s, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(push_constant, std140)
	#define LAYOUT_STORAGE(s, b) layout(std140, set = s, binding = b) readonly restrict buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) IF(loc, layout (location = loc) mod in type name, const type name = defaultValue)
		
	#define INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)

	#define OUTPUT(loc, type, name) IF(loc, layout (location = loc) out type name, type name)
	
	#define OUTPUT_MOD(loc, mod, type, name) IF(loc, layout (location = loc) mod out type name, type name)
	
	#define WINDING ccw

	#define LOCATION(loc) layout(location = loc) 
#else
	#extension GL_ARB_separate_shader_objects : require
	#extension GL_ARB_explicit_attrib_location : require
	#extension GL_ARB_shading_language_420pack : require

#ifdef USE_SAMPLER2
	#define LAYOUT_SAMPLER2(s, b)
#else
	#define LAYOUT_SAMPLER2(s, b) layout(binding = b)
#endif

	#define LAYOUT_SAMPLER(s, b) layout(binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(std140, binding = 2)
	#define LAYOUT_STORAGE(s, b) layout(std140, binding = b) buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) mod in type name
		
	#define INPUT(loc, type, name, defaultValue) in type name

	#define OUTPUT(loc, type, name) out type name
	
	#define OUTPUT_MOD(loc, mod, type, name) mod out type name
	
	#define WINDING ccw

	#define LOCATION(loc)
#endif
/// END AUTOGENERATED HEADER

layout (points) in;
layout (triangle_strip, max_vertices = 8) out;

LAYOUT_UBO(0, 10) uniform View {
	mat4 projView;
	mat4 projViewInverse;
	mat4 proj;
	mat4 projInverse;
	mat4 view;
	mat4 viewInverse;
	vec3 camPos;
	float lodFactor;
	float near;
	float far;
} u_view;

struct Billboard {
	vec4 texCoords[7];
	vec4 dimFadeIn;
	vec4 coordsOH;
	vec4 bbMinHeightOH;
	vec4 bbMax;
};

LAYOUT_UBO(1, 4) uniform VMaterial {
	Billboard billboards[16];
	vec2 fadeOutRanges[16];
	vec2 smoothLodRange;
} u_vmat;

LOCATION(0) in VertexData {
	vec3 position;
	vec4 normalScale;
	flat int index;

	vec4 instColor;

	vec4 texCoords[7];
	vec4 dimFadeIn;
	vec4 coordsOH;
	float heightOH;

	vec3 bbMin;
	vec3 bbMax;
} inData[];

OUTPUT(POS_LOC, vec4, posAmbient);
OUTPUT(NRML_LOC, vec3, normal_);
OUTPUT(TNGT_LOC, vec3, tangent_);
OUTPUT(BINORM_LOC, vec3, binormal_);
OUTPUT_MOD(TC_LOC, centroid, vec3, texCoordAlpha);
OUTPUT(COL_LOC, vec4, color);
OUTPUT(OFFSET_LOC, vec3, offset);
OUTPUT_MOD(MATIDX_LOC, flat, int, matIndex);
OUTPUT(VPOS_LOC, vec3, vpos);
OUTPUT(FOGFACT_LOC, float, fogFactor);
OUTPUT(EXTFACT_LOC, vec3, extFactor);
OUTPUT(INSCATT_LOC, vec3, inScatt);

const vec3[8] of = vec3[8](
	vec3(.0, .0, .0),
	vec3(1.0, .0, .0),
	vec3(.0, 1.0, .0),
	vec3(1.0, 1.0, .0),
	
	vec3(.0, .0, .0),
	vec3(1.0, .0, .0),
	vec3(.0, 1.0, .0),
	vec3(1.0, 1.0, .0)
);

float calcDist(vec3 refPos, vec3 pos, vec3 nrml, float scale, vec3 box[2]);
float compFadeOutAlpha(float distance, vec2 range);
vec3[4] getVertices(vec2 dim, vec3 pos, vec3 tangent, vec3 binormal, float scale);
vec3[4] getVerticesOH(vec4 coordsOH, float heightOH, vec3 pos, vec3 tangent, vec3 binormal, vec3 normal, float scale);
vec2[4] getTexCoords(vec4 texCoords[7], int faceIdx);
void calcFogFactor(vec3 pos, out float fogFactor, out vec3 extFactor, out vec3 inScatt);

void main() {
	vec3 vpos2 = inData[0].position;
	vec3 vnrml = inData[0].normalScale.xyz;
	float scale = inData[0].normalScale.w;
	vec4 vcolor = inData[0].instColor;
	int vindex = inData[0].index;

	float distToCam = calcDist(u_view.viewInverse[3].xyz, vpos2, vnrml, scale, vec3[](inData[0].bbMin, inData[0].bbMax));
	float fadeOutAlpha = compFadeOutAlpha(distToCam, u_vmat.fadeOutRanges[vindex] * vec2(u_view.lodFactor, 1.0 / u_view.lodFactor));
	if (fadeOutAlpha <= .0) return;

	vec4 texCoords[7] = inData[0].texCoords;
	vec2 fadeInAngle = inData[0].dimFadeIn.zw;
	vec2 dim = inData[0].dimFadeIn.xy;
	vec4 coordsOH = inData[0].coordsOH;
	float heightOH = inData[0].heightOH;

	const float PI = 3.14159265;

	vec3 vertexToCam = u_view.viewInverse[3].xyz - vpos2;

	float angle = atan(vertexToCam.z / length(vertexToCam.xy));
	float instanceRot = atan(vnrml.y, vnrml.x);

	color = vcolor;
	matIndex = vindex;

	float fogFactor2;
	vec3 extFactor2;
	vec3 inScatt2;
	calcFogFactor(vpos2, fogFactor2, extFactor2, inScatt2);
	vpos = vpos2;
	fogFactor = fogFactor2;
	extFactor = extFactor2;
	inScatt = inScatt2;

	if (angle < fadeInAngle.x) {
		binormal_ = vec3(.0, .0, 1.0);
		tangent_ = normalize(cross(binormal_, vertexToCam));
		normal_ = cross(tangent_, binormal_);	

		float hAngle = atan(vertexToCam.y, vertexToCam.x) - instanceRot + PI / 6.0;		// [-pi, pi] - [0, 2*pi] + pi/6
		int j = int(12.0 + 3.0 * hAngle / PI) % 6;

		float s = clamp((angle - fadeInAngle.x) / (fadeInAngle.y - fadeInAngle.x), .0, 1.0);
		float finalAlpha = fadeOutAlpha * min(s * 2.0, 1.0);

		vec3[4] vertices = getVertices(dim, vpos2, tangent_, binormal_, scale);
		vec2[4] tcs = getTexCoords(texCoords, j);
		for (int i = 0; i < 4; ++i) {
			posAmbient = vec4(vertices[i], /*attrModel[0][3][3]*/ 1.0);
			texCoordAlpha = vec3(tcs[i], finalAlpha);	
			//calcFogFactor(vertices[i]);
			offset = of[i];
			gl_Position = u_view.projView * vec4(vertices[i], 1.0);
#ifdef UG_COMPILE_SPIRV
			binormal_ = vec3(.0, .0, 1.0);
			tangent_ = normalize(cross(binormal_, vertexToCam));
			normal_ = cross(tangent_, binormal_);

			color = vcolor;
			matIndex = vindex;

			vpos = vpos2;
			fogFactor = fogFactor2;
			extFactor = extFactor2;
			inScatt = inScatt2;
#endif

#ifdef RESCALE_Z_POS // Standard says vertex outputs from geometry should be re-emitted for each vertex
			gl_Position.z = (.5 * gl_Position.z + .5 * gl_Position.w);
#endif
#ifdef INVERT_Y
			gl_Position.y = -gl_Position.y;
#endif
			EmitVertex();
		}
		EndPrimitive();
	}

	if (angle >= fadeInAngle.y) {	
		normal_ = vec3(.0, .0, 1.0);
		tangent_ = vnrml;
		binormal_ = cross(normal_, tangent_);

		float s = clamp((angle - fadeInAngle.x) / (fadeInAngle.y - fadeInAngle.x), .0, 1.0);
		float finalAlpha = fadeOutAlpha * min(2.0 * (1.0 - s), 1.0);

		vec3[4] vertices = getVerticesOH(coordsOH, heightOH, vpos2, tangent_, binormal_, normal_, scale);
		vec2[4] tcs = getTexCoords(texCoords, 6);

		for (int i = 0; i < 4; ++i) {	
			posAmbient = vec4(vertices[i], /*attrModel[0][3][3]*/ 1.0);
			texCoordAlpha = vec3(tcs[i], finalAlpha);    
			//calcFogFactor(vertices[i]);
			offset = vec3(of[i + 4].xy, instanceRot);
			gl_Position = u_view.projView * vec4(vertices[i], 1.0);
#ifdef UG_COMPILE_SPIRV
			normal_ = vec3(.0, .0, 1.0);
			tangent_ = vnrml;
			binormal_ = cross(normal_, tangent_);

			color = vcolor;
			matIndex = vindex;
			
			vpos = vpos2;
			fogFactor = fogFactor2;
			extFactor = extFactor2;
			inScatt = inScatt2;
#endif

#ifdef RESCALE_Z_POS // Standard says vertex outputs from geometry should be re-emitted for each vertex
			gl_Position.z = (.5 * gl_Position.z + .5 * gl_Position.w);
#endif
#ifdef INVERT_Y
			gl_Position.y = -gl_Position.y;
#endif
			EmitVertex();
		}
		EndPrimitive();
	}
}
