#version 150
/// BEGIN AUTOGENERATED HEADER
#define CONC(a,b) a##b

#define IF(c, t, e) CONC(IF_, c)(t, e)

#define IF_UNDEF(t, e) e
#define IF_0(t, e) t
#define IF_1(t, e) t
#define IF_2(t, e) t
#define IF_3(t, e) t
#define IF_4(t, e) t
#define IF_5(t, e) t
#define IF_6(t, e) t
#define IF_7(t, e) t
#define IF_8(t, e) t
#define IF_9(t, e) t
#define IF_10(t, e) t
#define IF_11(t, e) t
#define IF_12(t, e) t
#define IF_13(t, e) t
#define IF_14(t, e) t
#define IF_15(t, e) t
#define IF_16(t, e) t
// Workaround for intel HD:
#define IF_00(t, e) t
#ifdef UG_COMPILE_SPIRV
	#define gl_VertexID gl_VertexIndex

	#define LAYOUT_SAMPLER2(s, b) layout(set = s, binding = b)
	#define LAYOUT_SAMPLER(s, b) layout(set = s, binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, set = s, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(push_constant, std140)
	#define LAYOUT_STORAGE(s, b) layout(std140, set = s, binding = b) readonly restrict buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) IF(loc, layout (location = loc) mod in type name, const type name = defaultValue)
		
	#define INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)

	#define OUTPUT(loc, type, name) IF(loc, layout (location = loc) out type name, type name)
	
	#define OUTPUT_MOD(loc, mod, type, name) IF(loc, layout (location = loc) mod out type name, type name)
	
	#define WINDING ccw

	#define LOCATION(loc) layout(location = loc) 
#else
	#extension GL_ARB_separate_shader_objects : require
	#extension GL_ARB_explicit_attrib_location : require
	#extension GL_ARB_shading_language_420pack : require

#ifdef USE_SAMPLER2
	#define LAYOUT_SAMPLER2(s, b)
#else
	#define LAYOUT_SAMPLER2(s, b) layout(binding = b)
#endif

	#define LAYOUT_SAMPLER(s, b) layout(binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(std140, binding = 2)
	#define LAYOUT_STORAGE(s, b) layout(std140, binding = b) buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) mod in type name
		
	#define INPUT(loc, type, name, defaultValue) in type name

	#define OUTPUT(loc, type, name) out type name
	
	#define OUTPUT_MOD(loc, mod, type, name) mod out type name
	
	#define WINDING ccw

	#define LOCATION(loc)
#endif
/// END AUTOGENERATED HEADER

layout(points) in;

LAYOUT_SAMPLER(2, 23) uniform sampler2D heightmapTex;
LAYOUT_SAMPLER(2, 24) uniform sampler2D ambientmapTex;

LAYOUT_UBO(0, 10) uniform View {
	mat4 projView;
	mat4 projViewInverse;
	mat4 proj;
	mat4 projInverse;
	mat4 view;
	mat4 viewInverse;
	vec3 camPos;
	float lodFactor;
	float near;
	float far;
} u_view;

LAYOUT_UBO(1, 11) uniform Terrain {
	vec2 terrainStart;
	vec2 terrainMinMax;
	
	vec4 terrainTileData1; // tileSize, matBorder, ambSize, ambBorder
	float terrainTileData2; // hmBorder
} u_terrain;

LAYOUT_UBO(1, 16) uniform GrassDataBlock {
	vec4 widthHeightDensityLod[256];
} u_grassDataBlock;

LAYOUT_UBO(1, 15) uniform MatDataBlock {
	vec4 mat2grassOverlayScaling[256];
} u_matDataBlock;

LAYOUT_UBO(2, 12) uniform Tile {
	ivec4 materialMap[17 * 16];
} u_tile; // TODO

LAYOUT_PUSH_CONSTANT() uniform PushConstant {
	vec4 blockCoordDim;
	vec2 tileSubPos;
	vec2 tileOffset;
	float distanceScaling;
	float alphaThreshold;
	int numSamples;
	vec4 color;
} u_push; // TODO

LOCATION(0) in VertexData {
	vec2 texCoord;
	int matType;
	int sampleIndex;
} inData[];

OUTPUT(VPOS_LOC, vec3, vpos);
OUTPUT(NRML_LOC, vec3, normal_);
OUTPUT(TNGT_LOC, vec3, tangentAmb_);
OUTPUT(TC_LOC, vec2, texCoord);
OUTPUT_MOD(MATTYPE_LOC, flat, ivec2, grassMatType);

#define TILE_GROUPS 4

vec4 getLevelColor(vec3 pos, int iLevel, vec3 normal, 
		out vec3 nrml, out float texHeight, out float ambient, vec3 dposdx, vec3 dposdy);

vec2 addBorder(vec2 coord, float res, float border) {
	float actualRes = res * TILE_GROUPS + 2.0 * border;
 	return ((coord + u_push.tileSubPos) * res + border) / actualRes;
}

vec2 addBorderEC(vec2 coord, float res, float border) {
	float actualRes = res * TILE_GROUPS + 2.0 * border + 1;
	return ((coord + u_push.tileSubPos) * res + 1.5) / actualRes;
}

float getAmbient(vec2 texCoord) {
	return texture(ambientmapTex, addBorder(texCoord, u_terrain.terrainTileData1.z, u_terrain.terrainTileData1.w)).r;
}

float betterTextureSampler(sampler2D tex, vec2 tc) {
	return texture(tex, tc).r;
}

void getNormal(sampler2D heightmapTex, vec2 tc, out mat3 tangentMat) {
	float hmin = u_terrain.terrainMinMax.x;
	float hmax = u_terrain.terrainMinMax.y;
	
	vec2 resolution = vec2(1.0);

	vec2 tcCnt = addBorderEC(tc, u_terrain.terrainTileData1.x, u_terrain.terrainTileData2);
	float hmSize = u_terrain.terrainTileData1.x + 2 * u_terrain.terrainTileData2 + 1;
	vec2 tcBL = tcCnt  - vec2(.5) / hmSize / TILE_GROUPS;
	vec2 tcTR = tcCnt  + vec2(.5) / hmSize / TILE_GROUPS;
	
	float hl = mix(hmin, hmax, betterTextureSampler(heightmapTex, vec2(tcBL.x, tcCnt.y)));
	float hr = mix(hmin, hmax, betterTextureSampler(heightmapTex, vec2(tcTR.x, tcCnt.y)));
	float hb = mix(hmin, hmax, betterTextureSampler(heightmapTex, vec2(tcCnt.x, tcBL.y)));
	float ht = mix(hmin, hmax, betterTextureSampler(heightmapTex, vec2(tcCnt.x, tcTR.y)));
	
	vec3 normal = normalize(vec3((hl - hr) * resolution.y, (hb - ht) * resolution.x, resolution.x * resolution.y));
	vec3 tangent = normalize(vec3(normal.z, .0, -normal.x));
	vec3 bitangent = cross(normal, tangent);

	tangentMat = mat3(tangent, bitangent, normal);	
}

mat2 rota(float scale, float angle) {
    float s = sin(angle);
    float c = cos(angle);
    
    return mat2(c * scale, -s * scale,
                s * scale, c * scale);
}

// TODO: check randomness
float rand(vec2 co) {
    return fract(sin(dot(co.xy, vec2(12.912313898, 78.2131232133))) * 43758.513213453);
}

void calcFogFactor(vec3 vpos);
void createPrimitive(float width, float height, mat2 modelMat, vec3 vposx, vec3 nrml, vec3 tngnt, int matType, int grassType, float amb);

void genVertexData(mat2 modelMat, vec3 vposx, vec3 nrml, vec3 tngnt, vec3 vert, vec2 tc, int matType, int grassType, float amb) {

	vpos = vposx + vec3(modelMat * vert.xy, vert.z);
	
	gl_Position = (u_view.projView * vec4(vpos, 1.0));
#ifdef RESCALE_Z_POS
	gl_Position.z = (.5 * gl_Position.z + .5 * gl_Position.w);
#endif
#ifdef INVERT_Y
	gl_Position.y = -gl_Position.y;
#endif

#ifdef UG_COMPILE_SPIRV
	calcFogFactor(vposx); // debug only: technically must emit all data for all vertices
#endif
	
	texCoord = tc;
	normal_ = nrml;
	tangentAmb_ = vec3(tngnt.xy, amb);
	
	grassMatType = ivec2(grassType, matType);
}


void main() {
	int matType = inData[0].matType;
	if (matType == 0 || matType == 255) return;

	--matType;

	float h = mix(u_terrain.terrainMinMax.x, u_terrain.terrainMinMax.y, 
		texture(heightmapTex, addBorderEC(inData[0].texCoord, u_terrain.terrainTileData1.x, u_terrain.terrainTileData2)).r);
	
	mat3 tangentMat;
	getNormal(heightmapTex, inData[0].texCoord, tangentMat);
	
	vec3 vpos = vec3((u_push.tileOffset + inData[0].texCoord) * u_terrain.terrainTileData1.x, h - 0.02);
	
	vec3 camVertex = vpos - u_view.viewInverse[3].xyz;
	float dist = length(camVertex);
	
	vec4 matData = u_matDataBlock.mat2grassOverlayScaling[matType];
	int grassType = int(matData.x);
	
	if (grassType == 255) return;
	
	vec4 grassData = u_grassDataBlock.widthHeightDensityLod[grassType];
	float width = grassData.x;
	float height = grassData.y;
	float density = grassData.z;
	float lodDistance = grassData.w * u_push.distanceScaling;
	float lodDistanceNear = 0.0;
	if (dist > lodDistance) return;
	
	float densityLODScale = clamp(mix(1.0, 0.0, (dist - lodDistanceNear) / (lodDistance - lodDistanceNear)), 0.0, 1.0);
	
	density *= densityLODScale * densityLODScale;
	if (inData[0].sampleIndex > density) return;
	
	float lodScale = 1.0;
	if (inData[0].sampleIndex + 1 >= density) {
		lodScale = density - inData[0].sampleIndex;
	}
	
	vec2 ambCoord = addBorder(inData[0].texCoord, u_terrain.terrainTileData1.z, u_terrain.terrainTileData1.w);
	float amb = texture(ambientmapTex, ambCoord).r;
	
	calcFogFactor(vpos);
	
	float rnd = rand(4.21 * vpos.xy); // TODO remove
	float rnd2 = rand(3.41 * vpos.yx); // TODO remove
	
	float dir = rnd * 6.281245;
	float modelScale = lodScale * (rnd2 * .4 + .8);
	
	mat2 modelMat = rota(1.0, dir);
	
	vec3 nrml = vec3(tangentMat[2]); //vec3(modelMat * vec2(1.0, .0), .0);
	vec3 tngnt = vec3(modelMat * vec2(.0, 1.0), .0);

	createPrimitive(width * modelScale, height * modelScale, modelMat, vpos, nrml, tngnt, matType, grassType, amb);
}
