#version 150
/// BEGIN AUTOGENERATED HEADER
#define CONC(a,b) a##b

#define IF(c, t, e) CONC(IF_, c)(t, e)

#define IF_UNDEF(t, e) e
#define IF_0(t, e) t
#define IF_1(t, e) t
#define IF_2(t, e) t
#define IF_3(t, e) t
#define IF_4(t, e) t
#define IF_5(t, e) t
#define IF_6(t, e) t
#define IF_7(t, e) t
#define IF_8(t, e) t
#define IF_9(t, e) t
#define IF_10(t, e) t
#define IF_11(t, e) t
#define IF_12(t, e) t
#define IF_13(t, e) t
#define IF_14(t, e) t
#define IF_15(t, e) t
#define IF_16(t, e) t
// Workaround for intel HD:
#define IF_00(t, e) t
#ifdef UG_COMPILE_SPIRV
	#define gl_VertexID gl_VertexIndex

	#define LAYOUT_SAMPLER2(s, b) layout(set = s, binding = b)
	#define LAYOUT_SAMPLER(s, b) layout(set = s, binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, set = s, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(push_constant, std140)
	#define LAYOUT_STORAGE(s, b) layout(std140, set = s, binding = b) readonly restrict buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) IF(loc, layout (location = loc) mod in type name, const type name = defaultValue)
		
	#define INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)

	#define OUTPUT(loc, type, name) IF(loc, layout (location = loc) out type name, type name)
	
	#define OUTPUT_MOD(loc, mod, type, name) IF(loc, layout (location = loc) mod out type name, type name)
	
	#define WINDING ccw

	#define LOCATION(loc) layout(location = loc) 
#else
	#extension GL_ARB_separate_shader_objects : require
	#extension GL_ARB_explicit_attrib_location : require
	#extension GL_ARB_shading_language_420pack : require

#ifdef USE_SAMPLER2
	#define LAYOUT_SAMPLER2(s, b)
#else
	#define LAYOUT_SAMPLER2(s, b) layout(binding = b)
#endif

	#define LAYOUT_SAMPLER(s, b) layout(binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(std140, binding = 2)
	#define LAYOUT_STORAGE(s, b) layout(std140, binding = b) buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) mod in type name
		
	#define INPUT(loc, type, name, defaultValue) in type name

	#define OUTPUT(loc, type, name) out type name
	
	#define OUTPUT_MOD(loc, mod, type, name) mod out type name
	
	#define WINDING ccw

	#define LOCATION(loc)
#endif
/// END AUTOGENERATED HEADER
#ifndef UG_COMPILE_SPIRV
#extension GL_ARB_tessellation_shader : require
#endif

layout(quads, equal_spacing, ccw) in;

LAYOUT_UBO(0, 10) uniform View {
	mat4 projView;
	mat4 projViewInverse;
	mat4 proj;
	mat4 projInverse;
	mat4 view;
	mat4 viewInverse;
	vec3 camPos;
	float lodFactor;
	float near;
	float far;
} u_view;

LOCATION(0) in VertexDataIn {
	vec4 vposAmbient;
	vec4 normal2;
	vec4 tangent2;
	flat ivec2 matTypeGrassType;
	vec2 widthHeight;

	vec4 instColor;
	
	float fogFactor;
	vec3 extFactor;
	vec3 inScatt;
} inData[];

OUTPUT(VPOS_LOC, vec3, vpos);
OUTPUT(NRML_LOC, vec3, normal_);
OUTPUT(TNGT_LOC, vec3, tangentAmb_);
OUTPUT(TC_LOC, vec2, texCoord);
OUTPUT_MOD(MATTYPE_LOC, flat, ivec2, grassMatType);
OUTPUT(FOGFACT_LOC, float, fogFactor);
OUTPUT(EXTFACT_LOC, vec3, extFactor);
OUTPUT(INSCATT_LOC, vec3, inScatt);

void main() {
	vec3 w = mix(- inData[0].tangent2.xyz * inData[0].widthHeight.x * 0.5, inData[0].tangent2.xyz * inData[0].widthHeight.x * 0.5, gl_TessCoord.x);
	// vec3 n = inData[0].normal2.xyz;
	vec3 n = vec3(0.0, 0.0, 1.0);
	vec3 h = mix(vec3(0.0), n * inData[0].widthHeight.y, gl_TessCoord.y);
	vec3 c = cross(inData[0].tangent2.xyz, n);
	vpos = inData[0].vposAmbient.xyz + w + h + c * gl_TessCoord.y * gl_TessCoord.y * 0.4;
	
	gl_Position = (u_view.projView * vec4(vpos, 1.0));
#ifdef RESCALE_Z_POS
	gl_Position.z = (.5 * gl_Position.z + .5 * gl_Position.w);
#endif
	
	texCoord = gl_TessCoord.xy;
	normal_ = inData[0].normal2.xyz;
	tangentAmb_ = vec3(inData[0].tangent2.xy, inData[0].vposAmbient.w);
	
	grassMatType = ivec2(inData[0].matTypeGrassType.y, inData[0].matTypeGrassType.x);

	fogFactor = inData[0].fogFactor;
	extFactor = inData[0].extFactor;
	inScatt = inData[0].inScatt;
}
