#version 150
/// BEGIN AUTOGENERATED HEADER
#define CONC(a,b) a##b

#define IF(c, t, e) CONC(IF_, c)(t, e)

#define IF_UNDEF(t, e) e
#define IF_0(t, e) t
#define IF_1(t, e) t
#define IF_2(t, e) t
#define IF_3(t, e) t
#define IF_4(t, e) t
#define IF_5(t, e) t
#define IF_6(t, e) t
#define IF_7(t, e) t
#define IF_8(t, e) t
#define IF_9(t, e) t
#define IF_10(t, e) t
#define IF_11(t, e) t
#define IF_12(t, e) t
#define IF_13(t, e) t
#define IF_14(t, e) t
#define IF_15(t, e) t
#define IF_16(t, e) t
// Workaround for intel HD:
#define IF_00(t, e) t
#ifdef UG_COMPILE_SPIRV
	#define gl_VertexID gl_VertexIndex

	#define LAYOUT_SAMPLER2(s, b) layout(set = s, binding = b)
	#define LAYOUT_SAMPLER(s, b) layout(set = s, binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, set = s, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(push_constant, std140)
	#define LAYOUT_STORAGE(s, b) layout(std140, set = s, binding = b) readonly restrict buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) IF(loc, layout (location = loc) mod in type name, const type name = defaultValue)
		
	#define INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)

	#define OUTPUT(loc, type, name) IF(loc, layout (location = loc) out type name, type name)
	
	#define OUTPUT_MOD(loc, mod, type, name) IF(loc, layout (location = loc) mod out type name, type name)
	
	#define WINDING ccw

	#define LOCATION(loc) layout(location = loc) 
#else
	#extension GL_ARB_separate_shader_objects : require
	#extension GL_ARB_explicit_attrib_location : require
	#extension GL_ARB_shading_language_420pack : require

#ifdef USE_SAMPLER2
	#define LAYOUT_SAMPLER2(s, b)
#else
	#define LAYOUT_SAMPLER2(s, b) layout(binding = b)
#endif

	#define LAYOUT_SAMPLER(s, b) layout(binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(std140, binding = 2)
	#define LAYOUT_STORAGE(s, b) layout(std140, binding = b) buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) mod in type name
		
	#define INPUT(loc, type, name, defaultValue) in type name

	#define OUTPUT(loc, type, name) out type name
	
	#define OUTPUT_MOD(loc, mod, type, name) mod out type name
	
	#define WINDING ccw

	#define LOCATION(loc)
#endif
/// END AUTOGENERATED HEADER

LAYOUT_SAMPLER(2, 23) uniform sampler2D heightmapTex;
LAYOUT_SAMPLER(2, 24) uniform sampler2D ambientmapTex;
LAYOUT_SAMPLER(2, 25) uniform sampler2D materialIndexTex;

LAYOUT_UBO(1, 11) uniform Terrain {
	vec2 terrainStart;
	vec2 terrainMinMax;
	
	vec4 terrainTileData1; // tileSize, matBorder, ambSize, ambBorder
	float terrainTileData2; // hmBorder
} u_terrain;

LAYOUT_UBO(2, 14) uniform Tile {
	ivec4 materialMap[17 * 16];
} u_tile; // TODO

LAYOUT_PUSH_CONSTANT() uniform PushConstant {
	vec4 blockCoordDim;
	vec2 tileSubPos;
	vec2 tileOffset;
	float distanceScaling;
	float alphaThreshold;
	int numSamples;
	vec4 color;
} u_push;

LAYOUT_UBO(0, 10) uniform View {
	mat4 projView;
	mat4 projViewInverse;
	mat4 proj;
	mat4 projInverse;
	mat4 view;
	mat4 viewInverse;
	vec3 camPos;
	float lodFactor;
	float near;
	float far;
} u_view;

LAYOUT_UBO(1, 16) uniform GrassDataBlock {
	vec4 widthHeightDensityLod[256];
} u_grassDataBlock;

LAYOUT_UBO(1, 15) uniform MatDataBlock {
	vec4 mat2grassOverlayScaling[256];
} u_matDataBlock;

OUTPUT(VPOS_LOC, vec3, vpos);
OUTPUT(NRML_LOC, vec3, normal_);
OUTPUT(TNGT_LOC, vec3, tangentAmb_);
OUTPUT(TC_LOC, vec2, texCoord);
OUTPUT_MOD(MATTYPE_LOC, flat, ivec2, grassMatType);

#define TILE_GROUPS 4

const int sampleSize = 16;
const vec2[sampleSize] sampleCoords = vec2[sampleSize](
	vec2(1, 1),
	vec2(2, 3),
	vec2(3, 0),
	vec2(0, 2),
	
	vec2(3, 2),
	vec2(0, 0),
	vec2(1, 3),
	vec2(2, 1),
	
	vec2(0, 3),
	vec2(3, 1),
	vec2(1, 0),
	vec2(2, 2),

	vec2(0, 1),
	vec2(3, 3),
	vec2(2, 0),
	vec2(1, 2)
);

#if GRASS_QUALITY == 1
const int vertexPerQuad = 8;
const vec3[vertexPerQuad] vertices = vec3[vertexPerQuad](

	// vec3(0.0, -0.5, 0.0), // RESTART

	vec3(0.0, -0.5, 0.0),
	vec3(0.0, 0.5, 0.0),
	
	vec3(0.0, -0.5, 0.3),
	vec3(0.0, 0.5, 0.3),
	
	vec3(0.1, -0.5, 0.6),
	vec3(0.1, 0.5, 0.6),

	vec3(0.3, -0.5, 1.0),
	vec3(0.3, 0.5, 1.0)

	// vec3(0.3, 0.5, 1.0) // RESTART
);

const vec2[vertexPerQuad] texCoords = vec2[vertexPerQuad](
	// vec2(0.0, 0.0 + 0.025), // RESTART

	vec2(0.0, 0.0 + 0.025),
	vec2(1.0, 0.0 + 0.025),
	
	vec2(0.0, 0.3),
	vec2(1.0, 0.3),
	
	vec2(0.0, 0.6),
	vec2(1.0, 0.6),

	vec2(0.0, 1.0 - 0.025),
	vec2(1.0, 1.0 - 0.025)

	// vec2(1.0, 1.0 - 0.025) // RESTART
);
#else 
const int vertexPerQuad = 4;
const vec3[vertexPerQuad] vertices = vec3[vertexPerQuad](

	// vec3(0.0, -0.5, 0.0), // RESTART

	vec3(0.0, -0.5, 0.0),
	vec3(0.0, 0.5, 0.0),

	vec3(0.3, -0.5, 1.0),
	vec3(0.3, 0.5, 1.0)

	// vec3(0.3, 0.5, 1.0) // RESTART
);

const vec2[vertexPerQuad] texCoords = vec2[vertexPerQuad](
	// vec2(0.0, 0.0 + 0.025), // RESTART

	vec2(0.0, 0.0 + 0.025),
	vec2(1.0, 0.0 + 0.025),

	vec2(0.0, 1.0 - 0.025),
	vec2(1.0, 1.0 - 0.025)

	// vec2(1.0, 1.0 - 0.025) // RESTART
);
#endif

void calcFogFactor(vec3 pos);

float rand(vec2 co) {
    return fract(sin(dot(co.xy, vec2(12.912313898, 78.2131232133))) * 43758.513213453);
}

mat2 rota(float scale, float angle) {
    float s = sin(angle);
    float c = cos(angle);
    
    return mat2(c * scale, -s * scale,
                s * scale, c * scale);
}

int mapMaterial(int i, int offset) {
	return u_tile.materialMap[i + offset + 1].x - 1;
}

int getNumMaterials(int offset) {
	return u_tile.materialMap[offset].x;
}

int getOffset(vec2 tileSubPos) {
	return 17 * (4 * int(tileSubPos.x) + int(tileSubPos.y));
}

const float[sampleSize] offsets = float[sampleSize](
	0.0, 0.5, 0.125, 0.625,
	0.75, 0.25, 0.875, 0.375,
	0.1875, 0.6875, 0.0625, 0.5625,
	0.9375, 0.4375, 0.8125, 0.3125
);

vec2 addBorder(vec2 coord, float res, float border) {
	float actualRes = res * TILE_GROUPS + 2.0 * border;
 	return ((coord + u_push.tileSubPos) * res + border) / actualRes;
}

ivec2 addBorderN(vec2 coord, float res, float border) {
	float actualRes = res + 2.0 * border;
   	vec2 pos2 = ((coord * res + border) / actualRes + u_push.tileSubPos); 

	int actualResInt = int(actualRes);
	ivec2 of = actualResInt * ivec2(u_push.tileSubPos);
	return clamp(ivec2(pos2 * actualResInt), of, actualResInt + of - 1);
}

vec2 addBorderEC(vec2 coord, float res, float border) {
	float actualRes = res * TILE_GROUPS + 2.0 * border + 1;
	return ((coord + u_push.tileSubPos) * res + 1.5) / actualRes;
}

int safeToInt(float val) {
	return int(val * 255.0 + 0.5);
}

float betterTextureSampler(sampler2D tex, vec2 tc) {
	return texture(tex, tc).r;
}

void getNormal(sampler2D heightmapTex, vec2 tc, out mat3 tangentMat) {
	float hmin = u_terrain.terrainMinMax.x;
	float hmax = u_terrain.terrainMinMax.y;
	
	vec2 resolution = vec2(1.0);

	vec2 tcCnt = addBorderEC(tc, u_terrain.terrainTileData1.x, u_terrain.terrainTileData2);
	float hmSize = u_terrain.terrainTileData1.x + 2 * u_terrain.terrainTileData2 + 1;
	vec2 tcBL = tcCnt  - vec2(.5) / hmSize / TILE_GROUPS;
	vec2 tcTR = tcCnt  + vec2(.5) / hmSize / TILE_GROUPS;
	
	float hl = mix(hmin, hmax, betterTextureSampler(heightmapTex, vec2(tcBL.x, tcCnt.y)));
	float hr = mix(hmin, hmax, betterTextureSampler(heightmapTex, vec2(tcTR.x, tcCnt.y)));
	float hb = mix(hmin, hmax, betterTextureSampler(heightmapTex, vec2(tcCnt.x, tcBL.y)));
	float ht = mix(hmin, hmax, betterTextureSampler(heightmapTex, vec2(tcCnt.x, tcTR.y)));
	
	vec3 normal = normalize(vec3((hl - hr) * resolution.y, (hb - ht) * resolution.x, resolution.x * resolution.y));
	vec3 tangent = normalize(vec3(normal.z, .0, -normal.x));
	vec3 bitangent = cross(normal, tangent);

	tangentMat = mat3(tangent, bitangent, normal);	
}

void genVertexData(mat2 modelMat, vec3 vposx, vec3 nrml, vec3 tngnt, vec3 vert, vec2 tc, int matType, int grassType, float amb) {
	vpos = vposx + vec3(modelMat * vert.xy, vert.z);
	
	gl_Position = (u_view.projView * vec4(vpos, 1.0));
#ifdef RESCALE_Z_POS
	gl_Position.z = (.5 * gl_Position.z + .5 * gl_Position.w);
#endif
#ifdef INVERT_Y
	gl_Position.y = -gl_Position.y;
#endif
	
	texCoord = tc;
	normal_ = nrml;
	tangentAmb_ = vec3(tngnt.xy, amb);
	
	grassMatType = ivec2(grassType, matType);
}

void main() {
	int vertexId = gl_VertexID % vertexPerQuad;
	int quadId = gl_VertexID / vertexPerQuad;

	int sampleIndex = quadId % u_push.numSamples;
	int cellIndex = quadId / u_push.numSamples;
	int ix = cellIndex % int(u_push.blockCoordDim.z);
	int iy = cellIndex / int(u_push.blockCoordDim.z);
	vec2 cellCoord = vec2(ix, iy); // meters
	
	vec2 sampleCoord = sampleCoords[(sampleIndex + 3 * ix * 7 * iy) % sampleSize] / 4; // sample offset
	sampleCoord += vec2(offsets[iy % sampleSize], offsets[ix % sampleSize]) / 4 + 1.0 / 32; // random offset, meters
	
	vec2 rpos = u_push.blockCoordDim.xy + (cellCoord + sampleCoord);
	
	vec2 terrainTexCoord = rpos / u_terrain.terrainTileData1.x;

	int matType = safeToInt(texelFetch(materialIndexTex, addBorderN(terrainTexCoord, u_terrain.terrainTileData1.x, u_terrain.terrainTileData1.y), 0).r);

	int offset = getOffset(u_push.tileSubPos);

	if (getNumMaterials(offset + 1) != -1) matType = mapMaterial(matType, offset) + 1;


	if (matType == 0 || matType == 255) {
		gl_Position = vec4(0.0, 0.0, 0.0, 0.0);
		return; // TODO
	}

	--matType;

	float h = mix(u_terrain.terrainMinMax.x, u_terrain.terrainMinMax.y, 
		texture(heightmapTex, addBorderEC(terrainTexCoord, u_terrain.terrainTileData1.x, u_terrain.terrainTileData2)).r);
	
	mat3 tangentMat;
	getNormal(heightmapTex, terrainTexCoord, tangentMat);
	
	vec3 vpos = vec3((u_push.tileOffset + terrainTexCoord) * u_terrain.terrainTileData1.x, h - 0.02);
	
	vec3 camVertex = vpos - u_view.viewInverse[3].xyz;
	float dist = length(camVertex);
	
	vec4 matData = u_matDataBlock.mat2grassOverlayScaling[matType];
	int grassType = int(matData.x);
	if (grassType == 255) {
		gl_Position = vec4(0.0, 0.0, 0.0, 0.0);
		return;
	}
	
	vec4 grassData = u_grassDataBlock.widthHeightDensityLod[grassType];
	float width = grassData.x;
	float height = grassData.y;
	float density = grassData.z;
	float lodDistance = grassData.w * u_push.distanceScaling;
	float lodDistanceNear = 0.0;
	if (dist > lodDistance) {
		gl_Position = vec4(0.0, 0.0, 0.0, 0.0);
		return; // TODO
	}
	
	float densityLODScale = clamp(mix(1.0, 0.0, (dist - lodDistanceNear) / (lodDistance - lodDistanceNear)), 0.0, 1.0);
	
	density *= densityLODScale * densityLODScale;
	if (sampleIndex > density) {
		gl_Position = vec4(0.0, 0.0, 0.0, 0.0);
		return; // TODO
	}
	
	float lodScale = 1.0;
	if (sampleIndex + 1 >= density) {
		lodScale = density - sampleIndex;
	}
	
	vec2 ambCoord = addBorder(terrainTexCoord, u_terrain.terrainTileData1.z, u_terrain.terrainTileData1.w);
	float amb = texture(ambientmapTex, ambCoord).r;
	
	calcFogFactor(vpos);
	
	float rnd = rand(4.21 * vpos.xy); // TODO remove
	float rnd2 = rand(3.41 * vpos.yx); // TODO remove
	
	float dir = rnd * 6.281245;
	float modelScale = lodScale * (rnd2 * .4 + .8);
	
	mat2 modelMat = rota(1.0, dir);
	
	vec3 nrml = vec3(tangentMat[2]); //vec3(modelMat * vec2(1.0, .0), .0);
	vec3 tngnt = vec3(modelMat * vec2(.0, 1.0), .0);

	vec3 vert = vec3(vertices[vertexId].x, vertices[vertexId].y * width * modelScale, vertices[vertexId].z * height * modelScale);
	
	genVertexData(modelMat, vpos, nrml, tngnt, vert, texCoords[vertexId], matType, grassType, amb);
}
