#version 150
/// BEGIN AUTOGENERATED HEADER
#define CONC(a,b) a##b

#define IF(c, t, e) CONC(IF_, c)(t, e)

#define IF_UNDEF(t, e) e
#define IF_0(t, e) t
#define IF_1(t, e) t
#define IF_2(t, e) t
#define IF_3(t, e) t
#define IF_4(t, e) t
#define IF_5(t, e) t
#define IF_6(t, e) t
#define IF_7(t, e) t
#define IF_8(t, e) t
#define IF_9(t, e) t
#define IF_10(t, e) t
#define IF_11(t, e) t
#define IF_12(t, e) t
#define IF_13(t, e) t
#define IF_14(t, e) t
#define IF_15(t, e) t
#define IF_16(t, e) t
// Workaround for intel HD:
#define IF_00(t, e) t
#ifdef UG_COMPILE_SPIRV
	#define gl_VertexID gl_VertexIndex

	#define LAYOUT_SAMPLER2(s, b) layout(set = s, binding = b)
	#define LAYOUT_SAMPLER(s, b) layout(set = s, binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, set = s, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(push_constant, std140)
	#define LAYOUT_STORAGE(s, b) layout(std140, set = s, binding = b) readonly restrict buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) IF(loc, layout (location = loc) mod in type name, const type name = defaultValue)
		
	#define INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)

	#define OUTPUT(loc, type, name) IF(loc, layout (location = loc) out type name, type name)
	
	#define OUTPUT_MOD(loc, mod, type, name) IF(loc, layout (location = loc) mod out type name, type name)
	
	#define WINDING ccw

	#define LOCATION(loc) layout(location = loc) 
#else
	#extension GL_ARB_separate_shader_objects : require
	#extension GL_ARB_explicit_attrib_location : require
	#extension GL_ARB_shading_language_420pack : require

#ifdef USE_SAMPLER2
	#define LAYOUT_SAMPLER2(s, b)
#else
	#define LAYOUT_SAMPLER2(s, b) layout(binding = b)
#endif

	#define LAYOUT_SAMPLER(s, b) layout(binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(std140, binding = 2)
	#define LAYOUT_STORAGE(s, b) layout(std140, binding = b) buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) mod in type name
		
	#define INPUT(loc, type, name, defaultValue) in type name

	#define OUTPUT(loc, type, name) out type name
	
	#define OUTPUT_MOD(loc, mod, type, name) mod out type name
	
	#define WINDING ccw

	#define LOCATION(loc)
#endif
/// END AUTOGENERATED HEADER
#ifndef UG_COMPILE_SPIRV
#extension GL_ARB_tessellation_shader : require
#endif

layout (vertices = 1) out;

LAYOUT_SAMPLER(2, 23) uniform sampler2D heightmapTex;
LAYOUT_SAMPLER(2, 24) uniform sampler2D ambientmapTex;

LAYOUT_UBO(0, 10) uniform View {
	mat4 projView;
	mat4 projViewInverse;
	mat4 proj;
	mat4 projInverse;
	mat4 view;
	mat4 viewInverse;
	vec3 camPos;
	float lodFactor;
	float near;
	float far;
} u_view;

LAYOUT_UBO(1, 11) uniform Terrain {
	vec2 terrainStart;
	vec2 terrainMinMax;
	
	vec4 terrainTileData1; // tileSize, matBorder, ambSize, ambBorder
	float terrainTileData2; // hmBorder
} u_terrain;

LAYOUT_UBO(1, 16) uniform GrassDataBlock {
	vec4 widthHeightDensityLod[256];
} u_grassDataBlock;

LAYOUT_UBO(1, 15) uniform MatDataBlock {
	vec4 mat2grassOverlayScaling[256];
} u_matDataBlock;

LAYOUT_UBO(2, 12) uniform Tile {
	ivec4 materialMap[17 * 16];
} u_tile; // TODO

LAYOUT_PUSH_CONSTANT() uniform PushConstant {
	vec4 blockCoordDim;
	vec2 tileSubPos;
	vec2 tileOffset;
	float distanceScaling;
	float alphaThreshold;
	int numSamples;
	vec4 color;
} u_push; // TODO

layout(location = 0) in vec4 vposAmbient[];
layout(location = 1) in vec2 texCoord[];
layout(location = 2) flat in int matType[];
layout(location = 3) flat in int sampleIndex[];
layout(location = 4) in vec4 instColor[];
layout(location = 5) in float fogFactor[];
layout(location = 6) in vec3 extFactor[];
layout(location = 7) in vec3 inScatt[];

LOCATION(0) out VertexDataIn {
	vec4 vposAmbient;
	vec4 normal2;
	vec4 tangent2;
	flat ivec2 matTypeGrassType;
	vec2 widthHeight;

	vec4 instColor;

	float fogFactor;
	vec3 extFactor;
	vec3 inScatt;
} outData[];

#define TILE_GROUPS 4

float rand(vec2 co) {
    return fract(sin(dot(co.xy, vec2(12.912313898, 78.2131232133))) * 43758.513213453);
}

float betterTextureSampler(sampler2D tex, vec2 tc) {
	return texture(tex, tc).r;
}

vec2 addBorderEC(vec2 coord, float res, float border) {
	float actualRes = res * TILE_GROUPS + 2.0 * border + 1;
	return ((coord + u_push.tileSubPos) * res + 1.5) / actualRes;
}

void getNormal(sampler2D heightmapTex, vec2 tc, out mat3 tangentMat) {
	float hmin = u_terrain.terrainMinMax.x;
	float hmax = u_terrain.terrainMinMax.y;
	
	vec2 resolution = vec2(1.0);

	vec2 tcCnt = addBorderEC(tc, u_terrain.terrainTileData1.x, u_terrain.terrainTileData2);
	float hmSize = u_terrain.terrainTileData1.x + 2 * u_terrain.terrainTileData2 + 1;
	vec2 tcBL = tcCnt  - vec2(.5) / hmSize / TILE_GROUPS;
	vec2 tcTR = tcCnt  + vec2(.5) / hmSize / TILE_GROUPS;
	
	float hl = mix(hmin, hmax, betterTextureSampler(heightmapTex, vec2(tcBL.x, tcCnt.y)));
	float hr = mix(hmin, hmax, betterTextureSampler(heightmapTex, vec2(tcTR.x, tcCnt.y)));
	float hb = mix(hmin, hmax, betterTextureSampler(heightmapTex, vec2(tcCnt.x, tcBL.y)));
	float ht = mix(hmin, hmax, betterTextureSampler(heightmapTex, vec2(tcCnt.x, tcTR.y)));
	
	vec3 normal = normalize(vec3((hl - hr) * resolution.y, (hb - ht) * resolution.x, resolution.x * resolution.y));
	vec3 tangent = normalize(vec3(normal.z, .0, -normal.x));
	vec3 bitangent = cross(normal, tangent);

	tangentMat = mat3(tangent, bitangent, normal);	
}

mat2 rota(float scale, float angle) {
    float s = sin(angle);
    float c = cos(angle);
    
    return mat2(c * scale, -s * scale,
                s * scale, c * scale);
}

void main() {
	gl_TessLevelInner[0] = 1.0;
	gl_TessLevelInner[1] = 1.0;
	gl_TessLevelOuter[0] = 1.0;
	gl_TessLevelOuter[1] = 1.0;
	gl_TessLevelOuter[2] = 1.0;
	gl_TessLevelOuter[3] = 1.0;

	int matType2 = matType[gl_InvocationID];
	if (matType2 == 0 || matType2 == 255) {
		gl_TessLevelOuter[1] = 0.0;
		gl_TessLevelInner[1] = 0.0;
		matType2 = 1;
		// return;
	}
	--matType2;
	
	vec3 camVertex = vposAmbient[gl_InvocationID].xyz - u_view.viewInverse[3].xyz;
	float dist = length(camVertex);
	
	vec4 matData = u_matDataBlock.mat2grassOverlayScaling[matType2];
	int grassType = int(matData.x);
	if (grassType == 255) {
		gl_TessLevelOuter[1] = 0.0;
		gl_TessLevelInner[1] = 0.0;
	}
	
	vec4 grassData = u_grassDataBlock.widthHeightDensityLod[grassType];
	float width = grassData.x;
	float height = grassData.y;
	float density = grassData.z;
	float lodDistance = grassData.w * u_push.distanceScaling;
	float lodDistanceNear = 0.0;
	
	float densityLODScale = clamp(mix(1.0, 0.0, (dist - lodDistanceNear) / (lodDistance - lodDistanceNear)), 0.0, 1.0);
	
	density *= densityLODScale * densityLODScale;
	if (sampleIndex[gl_InvocationID] > density) {
		gl_TessLevelOuter[1] = 0.0;
		gl_TessLevelInner[1] = 0.0;
		// return; // CAN'T RETURN
	}
	
	if (dist > lodDistance) {
		gl_TessLevelOuter[1] = 0.0;
		gl_TessLevelInner[1] = 0.0;
		// return; // CAN'T RETURN
	}

	float lodScale = 1.0;
	if (sampleIndex[gl_InvocationID] + 1 >= density) {
		lodScale = clamp(density - sampleIndex[gl_InvocationID], 0.0, 1.0);
	}
	

	float vertValue = mix(1.0, 2.0, densityLODScale);
	gl_TessLevelInner[1] = vertValue;
	gl_TessLevelOuter[0] = vertValue;
	gl_TessLevelOuter[2] = vertValue;

	mat3 tangentMat;
	getNormal(heightmapTex, texCoord[gl_InvocationID], tangentMat);
	
	float rnd = rand(4.21 * vposAmbient[gl_InvocationID].xy); // TODO remove
	float rnd2 = rand(3.41 * vposAmbient[gl_InvocationID].yx); // TODO remove
	
	float dir = rnd * 6.281245;
	float modelScale = lodScale * (rnd2 * .4 + .8);
	
	mat2 modelMat = rota(1.0, dir);

	outData[gl_InvocationID].widthHeight = vec2(width * lodScale, height * lodScale);

	outData[gl_InvocationID].matTypeGrassType.y =  grassType;
	outData[gl_InvocationID].matTypeGrassType.x = matType2;

	outData[gl_InvocationID].vposAmbient =  vposAmbient[gl_InvocationID];
	
	outData[gl_InvocationID].normal2 = vec4(tangentMat[2], .0); //vec3(modelMat * vec2(1.0, .0), .0);
	outData[gl_InvocationID].tangent2 = vec4(modelMat * vec2(.0, 1.0), .0, .0);

	outData[gl_InvocationID].fogFactor = fogFactor[gl_InvocationID];
	outData[gl_InvocationID].extFactor = extFactor[gl_InvocationID];
	outData[gl_InvocationID].inScatt = inScatt[gl_InvocationID];
}
