#version 150
/// BEGIN AUTOGENERATED HEADER
#define CONC(a,b) a##b

#define IF(c, t, e) CONC(IF_, c)(t, e)

#define IF_UNDEF(t, e) e
#define IF_0(t, e) t
#define IF_1(t, e) t
#define IF_2(t, e) t
#define IF_3(t, e) t
#define IF_4(t, e) t
#define IF_5(t, e) t
#define IF_6(t, e) t
#define IF_7(t, e) t
#define IF_8(t, e) t
#define IF_9(t, e) t
#define IF_10(t, e) t
#define IF_11(t, e) t
#define IF_12(t, e) t
#define IF_13(t, e) t
#define IF_14(t, e) t
#define IF_15(t, e) t
#define IF_16(t, e) t
// Workaround for intel HD:
#define IF_00(t, e) t
#ifdef UG_COMPILE_SPIRV
	#define gl_VertexID gl_VertexIndex

	#define LAYOUT_SAMPLER2(s, b) layout(set = s, binding = b)
	#define LAYOUT_SAMPLER(s, b) layout(set = s, binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, set = s, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(push_constant, std140)
	#define LAYOUT_STORAGE(s, b) layout(std140, set = s, binding = b) readonly restrict buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) IF(loc, layout (location = loc) mod in type name, const type name = defaultValue)
		
	#define INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)

	#define OUTPUT(loc, type, name) IF(loc, layout (location = loc) out type name, type name)
	
	#define OUTPUT_MOD(loc, mod, type, name) IF(loc, layout (location = loc) mod out type name, type name)
	
	#define WINDING ccw

	#define LOCATION(loc) layout(location = loc) 
#else
	#extension GL_ARB_separate_shader_objects : require
	#extension GL_ARB_explicit_attrib_location : require
	#extension GL_ARB_shading_language_420pack : require

#ifdef USE_SAMPLER2
	#define LAYOUT_SAMPLER2(s, b)
#else
	#define LAYOUT_SAMPLER2(s, b) layout(binding = b)
#endif

	#define LAYOUT_SAMPLER(s, b) layout(binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(std140, binding = 2)
	#define LAYOUT_STORAGE(s, b) layout(std140, binding = b) buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) mod in type name
		
	#define INPUT(loc, type, name, defaultValue) in type name

	#define OUTPUT(loc, type, name) out type name
	
	#define OUTPUT_MOD(loc, mod, type, name) mod out type name
	
	#define WINDING ccw

	#define LOCATION(loc)
#endif
/// END AUTOGENERATED HEADER
#ifndef UG_COMPILE_SPIRV
#	extension GL_ARB_shader_storage_buffer_object : require
#endif

layout(location = 0) out vec4 positionAndHeightMapOffset;
layout(location = 1) out vec4 tessLevelOuter;
layout(location = 2) out vec2 tessLevelInner;

LAYOUT_UBO(3, 7) uniform TerrainTessSettings {
	vec3 viewEye;
	float patchLevel;
	float gamma;
	float errorThreshold;
}
u_terrainTess;

struct TerrainPatch {
	vec4 zMinMaxErrZeroOne; // z = <unused>,  w = 0 = 32x32
	vec4 errors; // 1=16x16, 2=8x8, 3=4x4, 4=2x2
};

LAYOUT_STORAGE(3, 3) TerrainPatchBuffer {
	TerrainPatch patches[];
} u_terrainPatches;

LAYOUT_UBO(1, 11) uniform Terrain {
	vec2 terrainStart;
	vec2 terrainMinMax;
	
	vec4 terrainTileData1; // tileSize, matBorder, ambSize, ambBorder
	float terrainTileData2; // hmBorder
} u_terrain;

LAYOUT_SAMPLER2(2, 23) uniform sampler2D heightmapTex;

int getPatchesPerTileDim() {
	return int(1u << int(u_terrainTess.patchLevel));
}

int getPatchesPerTile() {
	return getPatchesPerTileDim() * getPatchesPerTileDim();
}

int getTileSize()  {
	return int(u_terrain.terrainTileData1.x);
}

int getPatchSize() {
	return getTileSize() / getPatchesPerTileDim();
}

ivec2 getTileCoord(int patchId) {
	int numXTiles = int(u_terrain.terrainStart.x) * -2;
	int tileId = patchId / getPatchesPerTile();
	ivec2 tileCoord = ivec2(tileId % numXTiles, tileId / numXTiles);
	return tileCoord;
}

ivec2 getLocalPatchCoord(int patchId) {
	int localPatchId = patchId % getPatchesPerTile();
	ivec2 localPatchCoord = ivec2(localPatchId % getPatchesPerTileDim(), localPatchId / getPatchesPerTileDim());
	return localPatchCoord;
}

ivec2 getGlobalPatchCoord(int patchId) {
	return getTileCoord(patchId) * getPatchesPerTileDim() + getLocalPatchCoord(patchId);
}

vec2 getTerrainStartPosition() {
	return u_terrain.terrainStart * getTileSize();
}

vec2 getPatchPosition(int patchId) {
	return getTerrainStartPosition() + getGlobalPatchCoord(patchId) * getPatchSize();
}

vec2 patchPosToTilePos(vec2 patchPos) {
	return floor(patchPos / 256.0);
}

vec2 getTileOffset(vec2 tilePos) {
	return vec2(uvec2(tilePos - u_terrain.terrainStart) % uvec2(4u, 4u));
}

ivec2 getNumTiles() {
	return ivec2(u_terrain.terrainStart.xy) * -2;
}

int getLocalPatchIndex(int x, int y) {
	return (x + y * getPatchesPerTileDim());
}

int globalPatchCoordToPatchId(ivec2 patchCoord) {
	ivec2 numTiles = getNumTiles();
	ivec2 tileCoord = patchCoord / getPatchesPerTileDim();
	ivec2 localPatchCoord = patchCoord % getPatchesPerTileDim();
	int localPatchId = getLocalPatchIndex(localPatchCoord.x, localPatchCoord.y);
	int tileId = tileCoord.x + tileCoord.y * numTiles.x;
	return tileId * getPatchesPerTile() + localPatchId;
}

vec2 getHeightMapOffset(vec2 position, int patchId) {
	vec2 offset = getTileOffset(patchPosToTilePos(position));
	ivec2 localPatchCoord = getLocalPatchCoord(patchId);
	vec2 result = offset * getPatchesPerTileDim() + localPatchCoord;
	return result;
}

int offsetPatchId(int patchId, int x, int y) {
	ivec2 numPatches = getNumTiles() * getPatchesPerTileDim();
	ivec2 globalPatchCoord = getGlobalPatchCoord(patchId);
	globalPatchCoord.x = clamp(globalPatchCoord.x + x, 0, numPatches.x - 1);
	globalPatchCoord.y = clamp(globalPatchCoord.y + y, 0, numPatches.y - 1);
	return globalPatchCoordToPatchId(globalPatchCoord);
}

vec3 getClosestBoundPoint(int patchId) {
	vec3 viewEye = u_terrainTess.viewEye.xyz;
	float patchSize = getPatchSize();
	vec2 position = getPatchPosition(patchId);
	vec2 zMinMax = u_terrainPatches.patches[patchId].zMinMaxErrZeroOne.xy;
	return vec3(
		clamp(viewEye.x, position.x, position.x + patchSize),
		clamp(viewEye.y, position.y, position.y + patchSize),
		clamp(viewEye.z, zMinMax.x, zMinMax.y)
	);
}

float calcFinalErrorScreen(float error, vec3 point) {
	vec3 viewEye = u_terrainTess.viewEye;
	float p = distance(viewEye, point);
	return u_terrainTess.gamma * (error / p);
}

float invLerp(float from, float to, float value) {
	return (value - from) / (to - from);
}

float getPatchFactorCont(int patchId) {
	int maxSimplificationLevel = 8 - int(u_terrainTess.patchLevel);
	int minSimplificationLevel = max(1, maxSimplificationLevel - 5);
	int numLevels = maxSimplificationLevel - minSimplificationLevel;

	vec3 bbPoint = getClosestBoundPoint(patchId);

	float errors[5];
	errors[0] = u_terrainPatches.patches[patchId].zMinMaxErrZeroOne.w;
	for (int i = 0; i < 4; i++) {
		errors[i+1] = u_terrainPatches.patches[patchId].errors[i];
	}
	
	float threshold = u_terrainTess.errorThreshold;
	float maxError = 0;
	float minError = 9999999;
	int maxLevel = -1;
	int minLevel = -1;
	for (int s = numLevels - 1; s >= 0; --s) {
		float error = calcFinalErrorScreen(errors[s], bbPoint);
		if (error < threshold) {
			maxError = error;
			maxLevel = s;
			break;
		} else {
			if (error < minError) {
				minLevel = s;
				minError = error;	
			}
		}
	} 

	float maxFactor = (1u << (maxSimplificationLevel - minSimplificationLevel - maxLevel));
	bool doLerp = minLevel >= 0;
	doLerp = false; //turn off for now -> wobbles
	if (!doLerp) {
 		return maxFactor;
	}

	if (maxError == 0) {
		maxError = minError * 0.75;
	}

	float alpha = clamp(invLerp(minError, maxError, threshold), 0.0f, 1.0f);
	float minFactor = (1 << (maxSimplificationLevel - minSimplificationLevel - minLevel));
	return mix(minFactor, maxFactor, alpha);
}

float getPatchFactor(int patchId) {
	return getPatchFactorCont(patchId);
}
 
void exportTessFactors(vec2 position, int patchId) {
	int edgeLeft = 0;
	int edgeBottom = 1;
	int edgeRight = 2;
	int edgeTop = 3;

	int leftPatchId = offsetPatchId(patchId, -1, 0);
	int bottomPatchId = offsetPatchId(patchId, 0, 1);
	int rightPatchId = offsetPatchId(patchId, 1, 0);
	int topPatchId = offsetPatchId(patchId, 0, -1);

	float thisPatchFactor = getPatchFactor(patchId);
	tessLevelOuter[edgeLeft] = min(thisPatchFactor, getPatchFactor(leftPatchId));
	tessLevelOuter[edgeBottom] = min(thisPatchFactor, getPatchFactor(bottomPatchId));
	tessLevelOuter[edgeRight] = min(thisPatchFactor, getPatchFactor(rightPatchId));
	tessLevelOuter[edgeTop] = min(thisPatchFactor, getPatchFactor(topPatchId));

	tessLevelInner[0] = thisPatchFactor;
	tessLevelInner[1] = thisPatchFactor;
}

void exportPositionAndHeightMapOffset(vec2 position, int patchId) {
	vec2 heightMapOffset = getHeightMapOffset(position, patchId);

	positionAndHeightMapOffset.xy = position;
	positionAndHeightMapOffset.zw = heightMapOffset;
}

void main() {
	int patchId = gl_VertexID;

	vec2 position = getPatchPosition(patchId);
	
	exportTessFactors(position, patchId);
	exportPositionAndHeightMapOffset(position, patchId);
}
