#version 150
#extension GL_ARB_texture_gather : enable
/// BEGIN AUTOGENERATED HEADER
#define CONC(a,b) a##b

#define IF(c, t, e) CONC(IF_, c)(t, e)

#define IF_UNDEF(t, e) e
#define IF_0(t, e) t
#define IF_1(t, e) t
#define IF_2(t, e) t
#define IF_3(t, e) t
#define IF_4(t, e) t
#define IF_5(t, e) t
#define IF_6(t, e) t
#define IF_7(t, e) t
#define IF_8(t, e) t
#define IF_9(t, e) t
#define IF_10(t, e) t
#define IF_11(t, e) t
#define IF_12(t, e) t
#define IF_13(t, e) t
#define IF_14(t, e) t
#define IF_15(t, e) t
#define IF_16(t, e) t
// Workaround for intel HD:
#define IF_00(t, e) t
#ifdef UG_COMPILE_SPIRV
	#define gl_VertexID gl_VertexIndex

	#define LAYOUT_SAMPLER2(s, b) layout(set = s, binding = b)
	#define LAYOUT_SAMPLER(s, b) layout(set = s, binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, set = s, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(push_constant, std140)
	#define LAYOUT_STORAGE(s, b) layout(std140, set = s, binding = b) readonly restrict buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) IF(loc, layout (location = loc) mod in type name, const type name = defaultValue)
		
	#define INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)

	#define OUTPUT(loc, type, name) IF(loc, layout (location = loc) out type name, type name)
	
	#define OUTPUT_MOD(loc, mod, type, name) IF(loc, layout (location = loc) mod out type name, type name)
	
	#define WINDING ccw

	#define LOCATION(loc) layout(location = loc) 
#else
	#extension GL_ARB_separate_shader_objects : require
	#extension GL_ARB_explicit_attrib_location : require
	#extension GL_ARB_shading_language_420pack : require

#ifdef USE_SAMPLER2
	#define LAYOUT_SAMPLER2(s, b)
#else
	#define LAYOUT_SAMPLER2(s, b) layout(binding = b)
#endif

	#define LAYOUT_SAMPLER(s, b) layout(binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(std140, binding = 2)
	#define LAYOUT_STORAGE(s, b) layout(std140, binding = b) buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) mod in type name
		
	#define INPUT(loc, type, name, defaultValue) in type name

	#define OUTPUT(loc, type, name) out type name
	
	#define OUTPUT_MOD(loc, mod, type, name) mod out type name
	
	#define WINDING ccw

	#define LOCATION(loc)
#endif
/// END AUTOGENERATED HEADER

#pragma optionNV(ifcvt all)
#pragma optionNV(fastmath on)
#pragma optionNV(inline all)
#pragma optionNV(strict on)
#pragma optionNV(unroll all)
#pragma optionNV(looplimit 4)
// #pragma optionNV(fastprecision on)

LAYOUT_SAMPLER2(2, 23) uniform sampler2D heightmapTex;
LAYOUT_SAMPLER2(2, 24) uniform sampler2D ambientmapTex;
LAYOUT_SAMPLER2(2, 25) uniform sampler2D materialIndexTex;

LAYOUT_UBO(1, 11) uniform Terrain {
	vec2 terrainStart;
	vec2 terrainMinMax;
	
	vec4 terrainTileData1; // tileSize, matBorder, ambSize, ambBorder
	float terrainTileData2; // hmBorder
} u_terrain;

LAYOUT_UBO(2, 14) uniform Tile {
	ivec4 materialMap[17 * 16];
} u_tile; // TODO

INPUT(VPOS_LOC, vec3, vpos, vec3(1.0));
INPUT(TC_TILEOFFSET_LOC, vec4, texCoordtileOffset, vec4(1.0));

#define TILE_GROUPS 4

const float ambientBoost = 1.0;

float getAmbient(vec2 texCoord);
void getNormal(sampler2D heightmapTex, vec2 tc, out mat3 tangentMat);
vec3 decodeNormal(vec3 color);
vec3 transformNormal(vec3 normal);
vec3 getLevelColor(vec3 pos, int iLevel, vec3 normal, 
		out vec2 nrml, out vec3 glosAoH, vec3 dposdx, vec3 dposdy);

vec2 getTexCoord() {
	return texCoordtileOffset.xy;
}

vec2 getTileOffset() {
	return floor(texCoordtileOffset.zw + .5);
}

int mapMaterial(int i, int offset) {
	return u_tile.materialMap[i + offset + 1].x - 1;
}

int getNumMaterials(int offset) {
	return u_tile.materialMap[offset].x;
}

int getOffset(vec2 tileSubPos) {
	return 17 * (4 * int(tileSubPos.x) + int(tileSubPos.y));
}

vec4 getLevelColor(vec3 pos, int iLevel, vec3 normal, 
		out vec3 nrml, out float texHeight, out float ambient, vec3 dposdx, vec3 dposdy);

vec2 addBorder(vec2 coord, vec2 tileSubPos, float res, float border) {
	float actualRes = res * TILE_GROUPS + 2.0 * border;
 	return ((coord + tileSubPos) * res + border) / actualRes;
}

ivec2 addBorderN(vec2 coord, vec2 tileSubPos, float res, float border) {
	float actualRes = res + 2.0 * border;
   	vec2 pos2 =  ((coord * res + border) / actualRes + tileSubPos);

	int actualResInt = int(actualRes);
	ivec2 of = actualResInt * ivec2(tileSubPos);
	return clamp(ivec2(pos2 * actualResInt), of, actualResInt + of - 1);
}

vec2 addBorderEC(vec2 coord, vec2 tileSubPos, float res, float border) {
	float actualRes = res * TILE_GROUPS + 2.0 * border + 1;
	return ((coord + tileSubPos) * res + 1.5) /  actualRes;
}

float getAmbient(vec2 texCoord, vec2 tileSubPos) {
	return texture(ambientmapTex, addBorder(texCoord, tileSubPos, u_terrain.terrainTileData1.z, u_terrain.terrainTileData1.w)).r;
}

float betterTextureSampler(sampler2D tex, vec2 tc) {
#ifdef GL_ARB_texture_gather
	vec2 tc0 = tc * textureSize(tex, 0) + vec2(.5);
	vec4 gat = textureGather(tex, floor(tc0) / textureSize(tex, 0));
	vec2 a = tc0 - floor(tc0);

	return mix(mix(gat.w, gat.z, a.x), mix(gat.x, gat.y, a.x), a.y);
#else
	return texture(tex, tc).r;
#endif
}

void getNormal(sampler2D heightmapTex, vec2 tc, vec2 tileSubPos, out mat3 tangentMat) {
	float hmin = u_terrain.terrainMinMax.x;
	float hmax = u_terrain.terrainMinMax.y;
	
	vec2 resolution = vec2(1.0);

	vec2 tcCnt = addBorderEC(tc, tileSubPos, u_terrain.terrainTileData1.x,u_terrain.terrainTileData2);
	float hmSize = u_terrain.terrainTileData1.x + 2 * u_terrain.terrainTileData2 + 1;
	vec2 tcBL = tcCnt - vec2(.5) / hmSize / TILE_GROUPS;
	vec2 tcTR = tcCnt + vec2(.5) / hmSize / TILE_GROUPS;
	
	float hl = mix(hmin, hmax, betterTextureSampler(heightmapTex, vec2(tcBL.x, tcCnt.y)))
		- mix(hmin, hmax, betterTextureSampler(heightmapTex, vec2(tcTR.x, tcCnt.y)));
	float hb = mix(hmin, hmax, betterTextureSampler(heightmapTex, vec2(tcCnt.x, tcBL.y)))
		- mix(hmin, hmax, betterTextureSampler(heightmapTex, vec2(tcCnt.x, tcTR.y)));
	
	vec3 normal = normalize(vec3(hl * resolution.y, hb * resolution.x, resolution.x * resolution.y));
	vec3 tangent = normalize(vec3(normal.z, .0, -normal.x));
	vec3 bitangent = cross(normal, tangent);

	tangentMat = mat3(tangent, bitangent, normal);	
}

int getLevelIndex(vec2 texCoord, vec2 tileSubPos, vec2 offset) {
	vec2 pos = (floor(texCoord * u_terrain.terrainTileData1.x + offset) + vec2(.5)) / u_terrain.terrainTileData1.x;
	ivec2 posInt = addBorderN(pos, tileSubPos, u_terrain.terrainTileData1.x, u_terrain.terrainTileData1.y);

	//const float eps = .00025;
	//pos2 = clamp(pos2, eps + .25 * tileSubPos, .25 - eps + .25 * tileSubPos);

	//float texVal = texture(materialIndexTex, pos2).r;
	float texVal = texelFetch(materialIndexTex, posInt, 0).r;

	int idx = int(255.0 * texVal + .5);
	return idx;
}

float gauss(float x, float sigma) {
	return exp(-.5 * x * x / (sigma * sigma));
}

vec3 heightBlend1(vec3 colors, vec2 normals, vec3 glossAoH, out vec3 normal, out vec2 glossAo) {
	normal = decodeNormal(vec3(normals, 0.0));
	glossAo = glossAoH.xy;
	return colors;
}

vec3 blendAllMaterials1(vec2 texCoord, vec2 tileSubPos, vec3 dposdx, vec3 dposdy, int maxInd, 
		float maxWeight, out vec3 normal, out vec2 ambientGloss) {
	mat3 tangentMat;
	getNormal(heightmapTex, texCoord, tileSubPos, tangentMat);
	
	float ambient = getAmbient(texCoord.xy, tileSubPos);
	
	vec3 cols = vec3(.0);
	vec2 nrmls = vec2(.0);
	vec3 glossAoH = vec3(0.0, 1.0, -4.0);

	vec3 transformedNormal = transformNormal(tangentMat[2]);
	if (maxInd >= 0 && maxInd != 254) {
		cols = getLevelColor(vpos, maxInd, transformedNormal, nrmls, glossAoH, dposdx, dposdy);
	}
		
	vec3 nrml;
	vec2 glossAo;
	vec3 col = heightBlend1(cols, nrmls, glossAoH, nrml, glossAo);

	glossAo.y = (1.0 - (1.0 - glossAo.y) * ambientBoost) * ambient;

	ambientGloss = vec2(clamp(glossAo.y, 0.0, 1.0), glossAo.x);
	normal = tangentMat * nrml;
	return col;
}

vec3 heightBlend2(mat2x3 colors, mat2x2 normals, mat2x3 glossAoH, float maxHeight, out vec3 normal, out vec2 glossAo) {
	const float mixHeightInterval = 0.1;
	float height0 = maxHeight - mixHeightInterval;

	vec2 normal2 = vec2(.0);
	
	vec2 level = max(vec3(.0, .0, 1.0) * glossAoH - height0, .0);

	vec3 color = colors * level;
	glossAo = (glossAoH * level).xy;
	normal2 = normals * level;
	float sum = dot(level, vec2(1.0));
	if (sum > .0) sum = 1 / sum;

	glossAo *= sum;
	normal = decodeNormal(vec3(normal2 * sum, 0.0));
	return color * sum;
}

vec3 blendAllMaterials2(vec2 texCoord, vec2 tileSubPos, vec3 dposdx, vec3 dposdy, ivec2 maxInd, 
		vec2 maxWeight, out vec3 normal, out vec2 ambientGloss) {
	mat3 tangentMat;
	getNormal(heightmapTex, texCoord, tileSubPos, tangentMat);
	
	float ambient = getAmbient(texCoord.xy, tileSubPos);
	
	float sum = 1.0 / dot(maxWeight, vec2(1.0));
	
	mat2x3 cols = mat2x3(vec3(.0), vec3(.0));
	mat2x2 nrmls = mat2x2(vec2(.0), vec2(.0));
	mat2x3 glossAoH = mat2x3(vec3(0.0, 1.0, -0.2), vec3(0.0, 1.0, -0.2));

	float maxH = .0;
	
	vec3 transformedNormal = transformNormal(tangentMat[2]);
	for (int i = 0; i < 2; ++i) {
		int index = maxInd[i];
		if (index >= 0 && index != 254) {
			float w = maxWeight[i] * sum;
		
			cols[i] = getLevelColor(vpos, index, transformedNormal, nrmls[i], glossAoH[i], dposdx, dposdy);
			glossAoH[i].z *= pow(w, 0.25);
			maxH = max(glossAoH[i].z, maxH);
		}
	}
		
	vec3 nrml;
	vec2 glossAo;
	vec3 col = heightBlend2(cols, nrmls, glossAoH, maxH, nrml, glossAo);

	glossAo.y = (1.0 - (1.0 - glossAo.y) * ambientBoost) * ambient;

	ambientGloss = vec2(clamp(glossAo.y, 0.0, 1.0), glossAo.x);
	normal = tangentMat * nrml;
	return col;
}

vec3 heightBlend4(mat4x3 colors, mat4x2 normals, mat4x3 glossAoH, float maxHeight, out vec3 normal, out vec2 glossAo) {
	const float mixHeightInterval = 0.1;
	float height0 = maxHeight - mixHeightInterval;
	vec4 level = max(vec3(.0, .0, 1.0) * glossAoH - height0, .0);

	vec3 color = colors * level;
	normal.xy = normals * level;
	float sum = dot(level, vec4(1.0));
	if (sum > .0) sum = 1 / sum;

	glossAo = (glossAoH * level).xy * sum;
	normal = decodeNormal(vec3(normal.xy * sum, 0.0));
	return color * sum;
}

vec3 blendAllMaterials(vec2 texCoord, vec2 tileSubPos, vec3 dposdx, vec3 dposdy, ivec4 maxInd, 
		vec4 maxWeight, out vec3 normal, out vec2 ambientGloss) {
	float sum = 1.0 / dot(maxWeight, vec4(1.0));
	
	mat4x3 cols = mat4x3(vec3(.0), vec3(.0), vec3(.0), vec3(.0));
	mat4x2 nrmls = mat4x2(vec2(.0), vec2(.0), vec2(.0), vec2(.0));
	mat4x3 glossAoH = mat4x3(vec3(0.0, 1.0, -0.2), vec3(0.0, 1.0, -0.2), vec3(0.0, 1.0, -0.2), vec3(0.0, 1.0, -0.2));
	
	ambientGloss.x = .0;
	
	int index;
	float w;

	mat3 tangentMat;
	getNormal(heightmapTex, texCoord, tileSubPos, tangentMat);
	normal = transformNormal(tangentMat[2]);
	{
		index = maxInd[0];
		if (index >= 0 && index != 254) {
			w = maxWeight[0] * sum;
		
			cols[0] = getLevelColor(vpos, index, normal, nrmls[0], glossAoH[0], dposdx, dposdy);
			glossAoH[0].z *= pow(w, 0.25);
			ambientGloss.x = max(glossAoH[0].z, ambientGloss.x);
		}
	}{
		index = maxInd[1];
		if (index >= 0 && index != 254) {
			w = maxWeight[1] * sum;
		
			cols[1] = getLevelColor(vpos, index, normal, nrmls[1], glossAoH[1], dposdx, dposdy);
			glossAoH[1].z *= pow(w, 0.25);
			ambientGloss.x = max(glossAoH[1].z, ambientGloss.x);
		}
	}{
		index = maxInd[2];
		if (index >= 0 && index != 254) {
			w = maxWeight[2] * sum;
		
			cols[2] = getLevelColor(vpos, index, normal, nrmls[2], glossAoH[2], dposdx, dposdy);
			glossAoH[2].z *= pow(w, 0.25);
			ambientGloss.x = max(glossAoH[2].z, ambientGloss.x);
		}
	}{
		index = maxInd[3];
		if (index >= 0 && index != 254) {
			w = maxWeight[3] * sum;
		
			cols[3] = getLevelColor(vpos, index, normal, nrmls[3], glossAoH[3], dposdx, dposdy);
			glossAoH[3].z *= pow(w, 0.25);
			ambientGloss.x = max(glossAoH[3].z, ambientGloss.x);
		}
	}
		
	vec2 glossAo;
	vec3 col = heightBlend4(cols, nrmls, glossAoH, ambientGloss.x, normal, glossAo);

	float ambient = getAmbient(texCoord.xy, tileSubPos);
	glossAo.y = (1.0 - (1.0 - glossAo.y) * ambientBoost) * ambient;

	ambientGloss = vec2(clamp(glossAo.y, 0.0, 1.0), glossAo.x);
	normal = tangentMat * normal;
	return col;
}
