#version 150
/// BEGIN AUTOGENERATED HEADER
#define CONC(a, b) a##b

#define IF(c, t, e) CONC(IF_, c)(t, e)

#define IF_UNDEF(t, e) e
#define IF_0(t, e) t
#define IF_1(t, e) t
#define IF_2(t, e) t
#define IF_3(t, e) t
#define IF_4(t, e) t
#define IF_5(t, e) t
#define IF_6(t, e) t
#define IF_7(t, e) t
#define IF_8(t, e) t
#define IF_9(t, e) t
#define IF_10(t, e) t
#define IF_11(t, e) t
#define IF_12(t, e) t
#define IF_13(t, e) t
#define IF_14(t, e) t
#define IF_15(t, e) t
#define IF_16(t, e) t
// Workaround for intel HD:
#define IF_00(t, e) t
#ifdef UG_COMPILE_SPIRV
#	define gl_VertexID gl_VertexIndex

#	define LAYOUT_SAMPLER2(s, b) layout(set = s, binding = b)
#	define LAYOUT_SAMPLER(s, b) layout(set = s, binding = b)
#	define LAYOUT_UBO(s, b) layout(std140, set = s, binding = b)
#	define LAYOUT_PUSH_CONSTANT() layout(push_constant, std140)

#	define VERTEX_INPUT(loc, type, name, defaultValue)                                                                     \
		IF(loc, layout(location = loc) in type name, const type name = defaultValue)

#	define INPUT_MOD(loc, mod, type, name, defaultValue)                                                                   \
		IF(loc, layout(location = loc) mod in type name, const type name = defaultValue)

#	define INPUT(loc, type, name, defaultValue) IF(loc, layout(location = loc) in type name, const type name = defaultValue)

#	define OUTPUT(loc, type, name) IF(loc, layout(location = loc) out type name, type name)

#	define OUTPUT_MOD(loc, mod, type, name) IF(loc, layout(location = loc) mod out type name, type name)

#	define WINDING ccw

#	define LOCATION(loc) layout(location = loc)
#else
#	extension GL_ARB_separate_shader_objects : require
#	extension GL_ARB_explicit_attrib_location : require
#	extension GL_ARB_shading_language_420pack : require

#	ifdef USE_SAMPLER2
#		define LAYOUT_SAMPLER2(s, b)
#	else
#		define LAYOUT_SAMPLER2(s, b) layout(binding = b)
#	endif

#	define LAYOUT_SAMPLER(s, b) layout(binding = b)
#	define LAYOUT_UBO(s, b) layout(std140, binding = b)
#	define LAYOUT_PUSH_CONSTANT() layout(std140, binding = 2)

#	define VERTEX_INPUT(loc, type, name, defaultValue)                                                                     \
		IF(loc, layout(location = loc) in type name, const type name = defaultValue)

#	define INPUT_MOD(loc, mod, type, name, defaultValue) mod in type name

#	define INPUT(loc, type, name, defaultValue) in type name

#	define OUTPUT(loc, type, name) out type name

#	define OUTPUT_MOD(loc, mod, type, name) mod out type name

#	define WINDING ccw

#	define LOCATION(loc)
#endif
/// END AUTOGENERATED HEADER

#ifndef UG_COMPILE_SPIRV
#	extension GL_ARB_tessellation_shader : require
layout(quads, fractional_even_spacing, cw) in;
#else
layout(quads, fractional_even_spacing, ccw) in;
#endif

LAYOUT_UBO(3, 7) uniform TerrainTessSettings {
	vec3 viewEye;
	float patchLevel;
	float gamma;
	float errorThreshold;
}
u_terrainTess;

LAYOUT_UBO(1, 11) uniform Terrain {
	vec2 terrainStart;
	vec2 terrainMinMax;
	
	vec4 terrainTileData1; // tileSize, matBorder, ambSize, ambBorder
	float terrainTileData2; // hmBorder
} u_terrain;

LAYOUT_SAMPLER2(2, 23) uniform sampler2D heightmapTex;

OUTPUT(TC_TILEOFFSET_LOC, vec4, texCoordtileOffset);

#define TILE_GROUPS 4

int getPatchDim() {
	return 1 << int(u_terrainTess.patchLevel);
}

int getPatchSize() {
	return int(int(u_terrain.terrainTileData1.x) / getPatchDim());
}

vec2 patchPosToTilePos(vec2 patchPos) {
	return floor(patchPos / 256.0);
}

vec2 getTexCoord(vec2 worldCoord, vec2 tilePos) {
	return (worldCoord / u_terrain.terrainTileData1.x) - tilePos;
}

vec2 getTileOffset(vec2 tilePos) {
	return vec2(uvec2(tilePos - u_terrain.terrainStart) % uvec2(4u, 4u));
}

vec2 addBorderECTess(vec2 coord, vec2 heightMapOffset, float res, float border) {
	float actualRes = ((res * TILE_GROUPS) + (2.0 * border)) + 1.0;
	return (((coord + heightMapOffset) * res / getPatchDim()) + 1.5) / actualRes.xx;
}

float getHeightAt(vec2 heightMapOffset, vec2 uv) {
	vec2 b = addBorderECTess(uv, heightMapOffset, u_terrain.terrainTileData1.x, u_terrain.terrainTileData2);
	float sampled = texture(heightmapTex, b).x;
	float h = mix(u_terrain.terrainMinMax.x, u_terrain.terrainMinMax.y, sampled);
	return h;
}

void exportData(vec2 worldPos, vec2 patchPos) {
	vec2 tilePos = patchPosToTilePos(patchPos);

	texCoordtileOffset = vec4(getTexCoord(worldPos, tilePos), getTileOffset(tilePos));
}
