#version 150
/// BEGIN AUTOGENERATED HEADER
#define CONC(a,b) a##b

#define IF(c, t, e) CONC(IF_, c)(t, e)

#define IF_UNDEF(t, e) e
#define IF_0(t, e) t
#define IF_1(t, e) t
#define IF_2(t, e) t
#define IF_3(t, e) t
#define IF_4(t, e) t
#define IF_5(t, e) t
#define IF_6(t, e) t
#define IF_7(t, e) t
#define IF_8(t, e) t
#define IF_9(t, e) t
#define IF_10(t, e) t
#define IF_11(t, e) t
#define IF_12(t, e) t
#define IF_13(t, e) t
#define IF_14(t, e) t
#define IF_15(t, e) t
#define IF_16(t, e) t
// Workaround for intel HD:
#define IF_00(t, e) t
#ifdef UG_COMPILE_SPIRV
	#define gl_VertexID gl_VertexIndex

	#define LAYOUT_SAMPLER2(s, b) layout(set = s, binding = b)
	#define LAYOUT_SAMPLER(s, b) layout(set = s, binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, set = s, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(push_constant, std140)
	#define LAYOUT_STORAGE(s, b) layout(std140, set = s, binding = b) readonly restrict buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) IF(loc, layout (location = loc) mod in type name, const type name = defaultValue)
		
	#define INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)

	#define OUTPUT(loc, type, name) IF(loc, layout (location = loc) out type name, type name)
	
	#define OUTPUT_MOD(loc, mod, type, name) IF(loc, layout (location = loc) mod out type name, type name)
	
	#define WINDING ccw

	#define LOCATION(loc) layout(location = loc) 
#else
	#extension GL_ARB_separate_shader_objects : require
	#extension GL_ARB_explicit_attrib_location : require
	#extension GL_ARB_shading_language_420pack : require

#ifdef USE_SAMPLER2
	#define LAYOUT_SAMPLER2(s, b)
#else
	#define LAYOUT_SAMPLER2(s, b) layout(binding = b)
#endif

	#define LAYOUT_SAMPLER(s, b) layout(binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(std140, binding = 2)
	#define LAYOUT_STORAGE(s, b) layout(std140, binding = b) buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) mod in type name
		
	#define INPUT(loc, type, name, defaultValue) in type name

	#define OUTPUT(loc, type, name) out type name
	
	#define OUTPUT_MOD(loc, mod, type, name) mod out type name
	
	#define WINDING ccw

	#define LOCATION(loc)
#endif
/// END AUTOGENERATED HEADER

LAYOUT_SAMPLER2(0, 7) uniform sampler2D dataTex;

struct Contour {
	vec4 color;
	float level;
	float width;
	float fadeDist;
};

LAYOUT_UBO(0, 9) uniform ColorMap {
	int dataSourceType;

	int levels;
	vec4 colorMin;
	vec4 colorMax;
	vec2 minMaxValue;
	int operation;

	float waterLevel;

	float cameraDist;

	vec4 waterColor;

	vec2 bbMin;
	vec2 bbMax;

	int numContours;
	Contour contours[10];
} u_colorMap;

float addContour(float height, float dist, float width) {
	float f = fract(height / dist);
	float df = fwidth(height / dist);
	
	if (df == .0) return .0;
	
	return 1.0 - smoothstep(.0 * df, width * df, f) * smoothstep(1.0, 1.0 - width * df, f);
}

float getValue(vec3 pos) {
	if (u_colorMap.dataSourceType == 1) { // dataSourceType 1: TEXTURE
		vec2 d = u_colorMap.bbMax - u_colorMap.bbMin;

		float x = clamp((u_colorMap.bbMax.x - pos.x) / d.x, .0, 1.0);
		float y = clamp((u_colorMap.bbMax.y - pos.y) / d.y, .0, 1.0);

		return texture(dataTex, vec2(1.0 - x, 1.0 - y)).r;
	} else if (u_colorMap.dataSourceType == 2) { // dataSourceType 2: HEIGHT
		return pos.z + .01; // note: avoid contour line to "lie" on a terrain face
	}
	return 0.0;
}

vec4 getColor(vec4 posAmbient, vec4 color) {
	if (u_colorMap.dataSourceType == 0 || color.a >= .0) return color; // dataSourceType 0: COLOR

	float value = getValue(posAmbient.xyz);
	
	vec4 finalColor = vec4(color.rgb, -color.a);
	
	if (u_colorMap.dataSourceType == 2 && posAmbient.z < u_colorMap.waterLevel) {
		finalColor.rgb *= mix(vec3(1.0), u_colorMap.waterColor.rgb, u_colorMap.waterColor.a); // apply operation??
	} else {
		float normValue = clamp((value - u_colorMap.minMaxValue.x) / (u_colorMap.minMaxValue.y - u_colorMap.minMaxValue.x), .0, 1.0);
		float t = floor(normValue * u_colorMap.levels) / u_colorMap.levels;
		vec4 col = mix(u_colorMap.colorMin, u_colorMap.colorMax, t);
		if (u_colorMap.operation == 0) { // operation 0: MULTIPLICATION
			finalColor.rgb *= mix(vec3(1.0), col.rgb, col.a);
		} else { // operation 1: ALPHA_BLEND
			finalColor.rgb = mix(finalColor.rgb, col.rgb, col.a);
		}
	}
	
	if (u_colorMap.numContours <= 0) {
		return finalColor;
	} else {
		const int maxContours = 10;
		for (int i = 0; i < min(u_colorMap.numContours, maxContours); i++) {
			float fade = pow(1.0 - clamp(u_colorMap.cameraDist / u_colorMap.contours[i].fadeDist, .0, 1.0), 3.0);
			float mag = mix(1.0, 2.0, pow(1.0 - clamp(u_colorMap.cameraDist / 4000.0, .0, 1.0), 3.0));
		
			float contourValue = addContour(value, u_colorMap.contours[i].level, mag * u_colorMap.contours[i].width);
			float alpha = fade * contourValue * u_colorMap.contours[i].color.a;
			
			finalColor.rgb = mix(finalColor.rgb, u_colorMap.contours[i].color.rgb, alpha);
		}

		return finalColor;
	}
}
