#version 150
/// BEGIN AUTOGENERATED HEADER
#define CONC(a,b) a##b

#define IF(c, t, e) CONC(IF_, c)(t, e)

#define IF_UNDEF(t, e) e
#define IF_0(t, e) t
#define IF_1(t, e) t
#define IF_2(t, e) t
#define IF_3(t, e) t
#define IF_4(t, e) t
#define IF_5(t, e) t
#define IF_6(t, e) t
#define IF_7(t, e) t
#define IF_8(t, e) t
#define IF_9(t, e) t
#define IF_10(t, e) t
#define IF_11(t, e) t
#define IF_12(t, e) t
#define IF_13(t, e) t
#define IF_14(t, e) t
#define IF_15(t, e) t
#define IF_16(t, e) t
// Workaround for intel HD:
#define IF_00(t, e) t
#ifdef UG_COMPILE_SPIRV
	#define gl_VertexID gl_VertexIndex

	#define LAYOUT_SAMPLER2(s, b) layout(set = s, binding = b)
	#define LAYOUT_SAMPLER(s, b) layout(set = s, binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, set = s, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(push_constant, std140)
	#define LAYOUT_STORAGE(s, b) layout(std140, set = s, binding = b) readonly restrict buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) IF(loc, layout (location = loc) mod in type name, const type name = defaultValue)
		
	#define INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)

	#define OUTPUT(loc, type, name) IF(loc, layout (location = loc) out type name, type name)
	
	#define OUTPUT_MOD(loc, mod, type, name) IF(loc, layout (location = loc) mod out type name, type name)
	
	#define WINDING ccw

	#define LOCATION(loc) layout(location = loc) 
#else
	#extension GL_ARB_separate_shader_objects : require
	#extension GL_ARB_explicit_attrib_location : require
	#extension GL_ARB_shading_language_420pack : require

#ifdef USE_SAMPLER2
	#define LAYOUT_SAMPLER2(s, b)
#else
	#define LAYOUT_SAMPLER2(s, b) layout(binding = b)
#endif

	#define LAYOUT_SAMPLER(s, b) layout(binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(std140, binding = 2)
	#define LAYOUT_STORAGE(s, b) layout(std140, binding = b) buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) mod in type name
		
	#define INPUT(loc, type, name, defaultValue) in type name

	#define OUTPUT(loc, type, name) out type name
	
	#define OUTPUT_MOD(loc, mod, type, name) mod out type name
	
	#define WINDING ccw

	#define LOCATION(loc)
#endif
/// END AUTOGENERATED HEADER

LAYOUT_SAMPLER2(2, 29) uniform sampler2D dirtTex;
LAYOUT_SAMPLER2(2, 30) uniform sampler2D dirtNormalTex;
LAYOUT_SAMPLER2(2, 31) uniform sampler2D rustTex;
LAYOUT_SAMPLER2(2, 32) uniform sampler2D rustNormalTex;

vec3 decodeNormal(vec2 color);

void applyDirtRust(vec3 dirtColor, vec3 rustColor, float dirtScale, 
		float rustScale, float dirtOpacity, float rustOpacity, float dirtFactor, float rustFactor,
		vec2 texCoord, float dirtMask, float rustMask, float age, inout vec3 albedo,
		inout float gloss, inout vec3 normal) {

	vec4 dirtTexValue = texture(dirtTex, dirtScale * texCoord);
	vec4 rustTexValue = texture(rustTex, rustScale * texCoord);

	float dirtAgeFactor = max(dirtFactor, age);
	float rustAgeFactor = max(rustFactor, age);

	float dirtFactorFinal = clamp((dirtMask - (1.0 - dirtAgeFactor)) / (dirtAgeFactor * .92 + .01), .0, 1.0);
	float rustFactorFinal = clamp((rustMask - (1.0 - rustAgeFactor)) / (rustAgeFactor * .92 + .01), .0, 1.0);

	// 1. rust, 2. dirt
	albedo = mix(albedo, mix(rustColor + 2.0 * rustTexValue.rgb - 1.0, rustColor, 1.0 - rustOpacity), rustFactorFinal);
	albedo = mix(albedo, mix(dirtColor + 2.0 * dirtTexValue.rgb - 1.0, dirtColor, 1.0 - dirtOpacity), dirtFactorFinal);

	albedo = clamp(albedo, vec3(.0), vec3(1.0));
	
	gloss = mix(gloss, dirtTexValue.a, dirtFactorFinal);
	gloss = mix(gloss, rustTexValue.a, rustFactorFinal);

	vec3 dirtNormal = decodeNormal(texture(dirtNormalTex, dirtScale * texCoord).rg);
	vec3 rustNormal = decodeNormal(texture(rustNormalTex, rustScale * texCoord).rg);

	normal = mix(normal, dirtNormal, dirtFactorFinal);
	normal = mix(normal, rustNormal, rustFactorFinal);
}
