#version 150
/// BEGIN AUTOGENERATED HEADER
#define CONC(a,b) a##b

#define IF(c, t, e) CONC(IF_, c)(t, e)

#define IF_UNDEF(t, e) e
#define IF_0(t, e) t
#define IF_1(t, e) t
#define IF_2(t, e) t
#define IF_3(t, e) t
#define IF_4(t, e) t
#define IF_5(t, e) t
#define IF_6(t, e) t
#define IF_7(t, e) t
#define IF_8(t, e) t
#define IF_9(t, e) t
#define IF_10(t, e) t
#define IF_11(t, e) t
#define IF_12(t, e) t
#define IF_13(t, e) t
#define IF_14(t, e) t
#define IF_15(t, e) t
#define IF_16(t, e) t
#ifdef UG_COMPILE_SPIRV
#define LAYOUT_SAMPLER(s, b) layout(set = s, binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, set = s, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(push_constant, std140)

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) IF(loc, layout (location = loc) mod in type name, const type name = defaultValue)
		
	#define INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)

	#define OUTPUT(loc, type, name) IF(loc, layout (location = loc) out type name, type name)
	
	#define OUTPUT_MOD(loc, mod, type, name) IF(loc, layout (location = loc) mod out type name, type name)
	
	#define WINDING ccw

	#define LOCATION(loc) layout(location = loc) 
#else
	#extension GL_ARB_separate_shader_objects : require
	#extension GL_ARB_explicit_attrib_location : require
	#extension GL_ARB_shading_language_420pack : require

	#define LAYOUT_SAMPLER(s, b) layout(binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(std140, binding = 2)

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) mod in type name
		
	#define INPUT(loc, type, name, defaultValue) in type name

	#define OUTPUT(loc, type, name) out type name
	
	#define OUTPUT_MOD(loc, mod, type, name) mod out type name
	
	#define WINDING ccw

	#define LOCATION(loc)
#endif
/// END AUTOGENERATED HEADER

#ifndef UG_COMPILE_SPIRV
layout (triangle_strip, max_vertices = 8) out;
#endif

float calcDistToBox(vec3 p, vec3 box[2]) {
	vec3 closestPointOnOrInBox = clamp(p, box[0], box[1]);
	return distance(p, closestPointOnOrInBox);
}

mat4x3 makeTransf(vec3 pos, vec3 dir, float scale) {
	vec3 xAxis = dir;
	//vec3 xAxis = vec3(dir.xy, .0);
	vec3 zAxis = vec3(.0, .0, 1.0);
	vec3 yAxis = cross(zAxis, xAxis);
	return mat4x3(scale * xAxis, scale * yAxis, scale * zAxis, pos);
}

vec3[2] transformBox(mat4x3 transf, vec3 box[2]) {
	vec3 x0 = box[0].x * transf[0];
	vec3 x1 = box[1].x * transf[0];
	vec3 y0 = box[0].y * transf[1];
	vec3 y1 = box[1].y * transf[1];
	vec3 z0 = box[0].z * transf[2];
	vec3 z1 = box[1].z * transf[2];

	vec3 mi = min(x0, x1) + min(y0, y1) + min(z0, z1) + transf[3];
	vec3 ma = max(x0, x1) + max(y0, y1) + max(z0, z1) + transf[3];

	return vec3[](mi, ma);
}

float calcDist(vec3 refPos, vec3 pos, vec3 nrml, float scale, vec3 box[2]) {
	return calcDistToBox(refPos, transformBox(makeTransf(pos, nrml, scale), box));
}

float compFadeOutAlpha(float distance, vec2 range) {
	// the 2.0 scale allows for using this function for transitions between two objects
	// so that always one of the two objects is 100% opaque during interpolation
	// note that alpha to coverage can not really blend two objects with 50% each
	
	return clamp(2.0 * (range.x - distance) * range.y, .0, 1.0);
}

float compFadeOutAlpha(vec3 vpos, vec3 campos, vec2 range) {
	return compFadeOutAlpha(distance(vpos, campos), range);
}
