function data()
return {
	"1st Street",
	"2nd Street",
	"3rd Street",
	"4th Street",
	"5th Street",
	"6th Street",
	"7th Street",
	"8th Street",
	"9th Street",
	"10th Street",
	"11th Street",
	"12th Street",
	"13th Street",
	"14th Street",
	"15th Street",
	"16th Street",
	"17th Street",
	
	"Wangfujing Street",
	"Xidan Commercial Street",
	"Qianmen Street",
	"Silver Street",
	"Li Yuen Street",
	"Jianguomenwai Street",
	"Chang'an Avenue",
	"Jianguomen Inner Street",
	"South Zhongzhou Road",
	"North Zhongzhou Road",
	
	"Temple Street",
	"Shanghai Street",
	"Nathan Road",
	"Chun Yueng Street",
	"Chaowai Street",
	"Granville Road",
	"Cheong Wan Road",
	"Prince Edward Road",
	"Ma Tau Chung Raoad",
	"Boundary Street",
	"Embankment Road",
	"Yen Chow Street",
	
	"Takeshita Street",
	"Omote-sando Avenue",
	"Shibuya Crossing",
	"Mosaic Street",
	"Chuo-dori",
	
	"Nikolskaya Street",
	"Tverskaya Street",
	"Kamergersky Lane",
	"Solyanka Street",
	"Vozdvizhenka Street",
	"New Arbat Avenue",
	"Chistoprudny Boulevard",
	
	"Fasil Road",
	"Idgah Road",
	"Peshwa Road",
	"Connaught Street",
	"Atul Grove Lane",
}
end
