function data()
return {
	metadata = {
		["*.*.*.axles"] = { name = "Axles", type = "ARRAY" },
		["*.*.*.axles.*"] = { name = "Axle", type = "MESH" },
		["*.*.*.wheels"] = { name = "Wheels", type = "ARRAY" },
		["*.*.*.wheels.*"] = { name = "Wheel", type = "MESH" },
		["*.*.*.fakeBogies"] = { name = "Fake bogies", type = "ARRAY" },
		["*.*.*.fakeBogies.*"] = { name = "Fake bogie", type = "TABLE" },
		["*.*.*.fakeBogies.*.group"] = { name = "Group", type = "MESHID" },
		["*.*.*.fakeBogies.*.position"] = { name = "Position", type = "FLOAT" },
		["*.*.*.fakeBogies.*.offset"] = { name = "Offset", type = "FLOAT" },
		["*.*.*.steeringParts"] = { name = "Steering parts", type = "ARRAY" },
		["*.*.*.steeringParts.*"] = { name = "Steering part", type = "MESHID" },
		["*.configs.*.wheelRadii"] = { name = "Wheels radius", type = "ARRAY" },
		["*.configs.*.wheelRadii.*"] = { name = "Radius", type = "FLOAT" },
		["*.configs.*.axleRadii"] = { name = "Axles radius", type = "ARRAY" },
		["*.configs.*.axleRadii.*"] = { name = "Radius", type = "FLOAT" },
			
		["autoGroundTex"] = { name = "Auto ground tex", type = "TABLE" },
		["autoGroundTex.categories"] = { name = "Categories", type = "ARRAY" },
		["autoGroundTex.categories.*"] = { name = "Category", type = "STRING" },
		
		["airVehicle"] = { name = "Air vehicle", type = "TABLE" },
		["airVehicle.configs"] = { name = "Configs", type = "ARRAY" },
		["airVehicle.configs.*"] = { name = "Config", type = "TABLE" },
		["airVehicle.configs.*.*.ids"] = { name = "Ids", type = "ARRAY" },
		["airVehicle.configs.*.*.ids.*"] = { name = "Id", type = "MESHID" },
		["airVehicle.configs.*.*.maxAngle"] = { name = "Max. angle", type = "FLOAT" },
		["airVehicle.configs.*.aileronLeft"] = { name = "Left aileron", type = "TABLE" },
		["airVehicle.configs.*.aileronRight"] = { name = "Right aileron", type = "TABLE" },
		["airVehicle.configs.*.elevator"] = { name = "Elevator", type = "TABLE" },
		["airVehicle.configs.*.flaps"] = { name = "Flaps", type = "TABLE" },
		["airVehicle.configs.*.props"] = { name = "Propellers", type = "ARRAY" },
		["airVehicle.configs.*.props.*"] = { name = "Propeller", type = "MESHID" },
		["airVehicle.configs.*.propsB"] = { name = "Propellers blurred", type = "ARRAY" },
		["airVehicle.configs.*.propsB.*"] = { name = "Propeller blurred", type = "MESHID" },
		["airVehicle.configs.*.beaconLights"] = { name = "Beacon lights", type = "ARRAY" },
		["airVehicle.configs.*.beaconLights.*"] = { name = "Beacon light", type = "MESHID" },
		["airVehicle.configs.*.strobeLights"] = { name = "Strobe lights", type = "ARRAY" },
		["airVehicle.configs.*.strobeLights.*"] = { name = "Strobe light", type = "MESHID" },
		["airVehicle.configs.*.landingLight"] = { name = "Landing lights", type = "ARRAY" },
		["airVehicle.configs.*.landingLight.*"] = { name = "Landing light", type = "MESHID" },
		["airVehicle.configs.*.rudder"] = { name = "Rudder", type = "TABLE" },
		["airVehicle.idleThrust"] = { name = "Idle thrust", type = "FLOAT" },
		["airVehicle.maxPayload"] = { name = "Max. Payload", type = "FLOAT" },
		["airVehicle.maxTakeOffWeight"] = { name = "MTO", type = "FLOAT" },
		["airVehicle.maxThrust"] = { name = "Max. thrust", type = "FLOAT" },
		["airVehicle.timeToFullThrust"] = { name = "Time to full thrust", type = "FLOAT" },
		["airVehicle.topSpeed"] = { name = "Top speed", type = "FLOAT" },
		["airVehicle.weight"] = { name = "Weight", type = "FLOAT" },
		["airVehicle.wingArea"] = { name = "Wing area", type = "FLOAT" },
		
		["railVehicle"] = { name = "Rail vehicle", type = "TABLE" },
		["railVehicle.configs"] = { name = "Configs", type = "ARRAY" },
		["railVehicle.configs.*"] = { name = "Config", type = "TABLE" },
		["railVehicle.configs.*.blinkingLights0"] = { name = "Blinking lights A", type = "ARRAY" },
		["railVehicle.configs.*.blinkingLights0.*"] = { name = "Blinking light", type = "MESHID" },
		["railVehicle.configs.*.blinkingLights1"] = { name = "Blinking lights B", type = "ARRAY" },
		["railVehicle.configs.*.blinkingLights1.*"] = { name = "Blinking light", type = "MESHID" },
		["railVehicle.configs.*.blinkLightsLeft0"] = { name = "Blinking lights Turning Left A", type = "ARRAY" },
		["railVehicle.configs.*.blinkLightsLeft0.*"] = { name = "Blinking light Turning Left", type = "MESHID" },
		["railVehicle.configs.*.blinkLightsLeft1"] = { name = "Blinking lights Turning Left B", type = "ARRAY" },
		["railVehicle.configs.*.blinkLightsLeft1.*"] = { name = "Blinking light Turning Left", type = "MESHID" },
		["railVehicle.configs.*.blinkLightsRight0"] = { name = "Blinking lights Turning Right A", type = "ARRAY" },
		["railVehicle.configs.*.blinkLightsRight0.*"] = { name = "Blinking light Turning Right", type = "MESHID" },
		["railVehicle.configs.*.blinkLightsRight1"] = { name = "Blinking lights Turning Right B", type = "ARRAY" },
		["railVehicle.configs.*.blinkLightsRight1.*"] = { name = "Blinking light Turning Right", type = "MESHID" },
		["railVehicle.configs.*.brakeLights"] = { name = "Brake lights", type = "ARRAY" },
		["railVehicle.configs.*.brakeLights.*"] = { name = "Id", type = "MESHID" },
		
		["railVehicle.configs.*.backBackwardParts"] = { name = "Backward End lights", type = "ARRAY" },
		["railVehicle.configs.*.backBackwardParts.*"] = { name = "Backward End light", type = "MESHID" },
		["railVehicle.configs.*.frontBackwardParts"] = { name = "Backward lights", type = "ARRAY" },
		["railVehicle.configs.*.frontBackwardParts.*"] = { name = "Backward light", type = "MESHID" },
		["railVehicle.configs.*.innerBackwardParts"] = { name = "Backward inner parts", type = "ARRAY" },
		["railVehicle.configs.*.innerBackwardParts.*"] = { name = "Backward inner parts", type = "MESHID" },
		
		["railVehicle.configs.*.backForwardParts"] = { name = "Forward End lights", type = "ARRAY" },
		["railVehicle.configs.*.backForwardParts.*"] = { name = "Forward End light", type = "MESHID" },
		["railVehicle.configs.*.frontForwardParts"] = { name = "Forward lights", type = "ARRAY" },
		["railVehicle.configs.*.frontForwardParts.*"] = { name = "Forward light", type = "MESHID" },
		["railVehicle.configs.*.innerForwardParts"] = { name = "Forward inner parts", type = "ARRAY" },
		["railVehicle.configs.*.innerForwardParts.*"] = { name = "Forward inner parts", type = "MESHID" },
		
		["railVehicle.topSpeed"] = { name = "Top speed", type = "FLOAT" },
		["railVehicle.blinkInterval"] = { name = "Blink Interval", type = "INTEGER" },
		["railVehicle.weight"] = { name = "Weight", type = "FLOAT" },
		["railVehicle.engines"] = { name = "Engines", type = "ARRAY" },
		["railVehicle.engines.*"] = { name = "Engine", type = "TABLE" },
		["railVehicle.engines.*.type"] = { name = "Type", type = "STRING", values = { "HORSE", "STEAM", "ELECTRIC", "DIESEL" } },
		["railVehicle.engines.*.power"] = { name = "Power", type = "FLOAT" },
		["railVehicle.engines.*.tractiveEffort"] = { name = "Tractive effort", type = "FLOAT" },
		["railVehicle.soundSet"] = { name = "Sound set", type = "TABLE" },
		["railVehicle.soundSet.name"] = { name = "Name", type = "STRING" },
		["railVehicle.soundSet.horn"] = { name = "Horn", type = "STRING" },
		
		["roadVehicle"] = { name = "Road vehicle", type = "TABLE" },
		["roadVehicle.configs"] = { name = "Configs", type = "ARRAY" },
		["roadVehicle.configs.*"] = { name = "Config", type = "TABLE" },
		["roadVehicle.configs.*.headLights"] = { name = "Head lights", type = "ARRAY" },
		["roadVehicle.configs.*.headLights.*"] = { name = "Id", type = "MESHID" },
		["roadVehicle.configs.*.blinkLightsLeft"] = { name = "Blink lights left", type = "ARRAY" },
		["roadVehicle.configs.*.blinkLightsLeft.*"] = { name = "Id", type = "MESHID" },
		["roadVehicle.configs.*.blinkLightsRight"] = { name = "Blink lights right", type = "ARRAY" },
		["roadVehicle.configs.*.blinkLightsRight.*"] = { name = "Id", type = "MESHID" },
		["roadVehicle.configs.*.brakeLights"] = { name = "Brake lights", type = "ARRAY" },
		["roadVehicle.configs.*.brakeLights.*"] = { name = "Id", type = "MESHID" },
		["roadVehicle.topSpeed"] = { name = "Top speed", type = "FLOAT" },
		["roadVehicle.blinkInterval"] = { name = "Blink Interval", type = "INTEGER" },
		["roadVehicle.weight"] = { name = "Weight", type = "FLOAT" },
		["roadVehicle.engine"] = { name = "Engine", type = "TABLE" },
		["roadVehicle.engine.type"] = { name = "Type", type = "STRING", values = { "HORSE", "STEAM", "ELECTRIC", "DIESEL" } },
		["roadVehicle.engine.power"] = { name = "Power", type = "FLOAT" },
		["roadVehicle.engine.tractiveEffort"] = { name = "Tractive effort", type = "FLOAT" },
		["roadVehicle.soundSet"] = { name = "Sound set", type = "TABLE" },
		["roadVehicle.soundSet.name"] = { name = "Name", type = "STRING" },
		["roadVehicle.soundSet.horn"] = { name = "Horn", type = "STRING" },
		
		["waterVehicle"] = { name = "Water vehicle", type = "TABLE" },
		["waterVehicle.configs"] = { name = "Configs", type = "ARRAY" },
		["waterVehicle.configs.*"] = { name = "Config", type = "TABLE" },
		["waterVehicle.configs.*.*.ids"] = { name = "Ids", type = "ARRAY" },
		["waterVehicle.configs.*.*.ids.*"] = { name = "Id", type = "MESHID" },
		["waterVehicle.configs.*.paddles"] = { name = "Paddles", type = "ARRAY" },
		["waterVehicle.configs.*.rudder"] = { name = "Rudder", type = "ARRAY" },
		["waterVehicle.configs.*.flags"] = { name = "Flags", type = "ARRAY" },
		["waterVehicle.weight"] = { name = "Top speed", type = "FLOAT" },
		["waterVehicle.availPower"] = { name = "Weight", type = "FLOAT" },
		["waterVehicle.maxRpm"] = { name = "Power", type = "FLOAT" },
		["waterVehicle.area"] = { name = "Tractive effort", type = "FLOAT" },
		["waterVehicle.topSpeed"] = { name = "Sound set", type = "FLOAT" },
		["waterVehicle.waterLine"] = { name = "Water Line", type = "ARRAY" },
		["waterVehicle.waterLine.*"] = { name = "Position", type = "VECTOR2" },
		
		
		["car"] = { name = "Car", type = "TABLE" },
		
		["person"] = { name = "Person", type = "TABLE" },
		["person.gender"] = { name = "Gender", type = "STRING", values = { "FEMALE", "MALE" } },
		["person.drivingLicenses"] = { name = "Driving licenses", type = "ARRAY" },
		["person.drivingLicenses.*"] = { name = "Driving license", type = "STRING", values = { "BUS", "TRUCK", "RAIL", "TRAM", "AIR", "AIR_OUTDOOR", "WATER" } },
		
		["tree"] = { name = "Tree", type = "TABLE" },
		["rock"] = { name = "Rock", type = "TABLE" },
		
		["categoryList"] = { name = "CategoryList", type = "TABLE" },
		["categoryList.categories"] = { name = "Categories", type = "ARRAY" },
		["categoryList.categories.*"] = { name = "Category", type = "STRING" },
		
		["category"] = { name = "Category", type = "TABLE" },
		["category.categories"] = { name = "Categories", type = "ARRAY" },
		["category.categories.*"] = { name = "Category", type = "STRING" },
		
		["particleSystem"] = { name = "Particle system", type = "TABLE" },
		["particleSystem.emitters"] = { name = "Emitters", type = "ARRAY" },
		["particleSystem.emitters.*"] = { name = "Emitter", type = "TABLE" },
		["particleSystem.emitters.*.position"] = { name = "Position", type = "VECTOR3" },
		["particleSystem.emitters.*.velocity"] = { name = "Velocity", type = "VECTOR3" },
		["particleSystem.emitters.*.color"] = { name = "Color", type = "COLOR" },
		["particleSystem.emitters.*.frequency"] = { name = "Frequency", type = "FLOAT" },
		["particleSystem.emitters.*.lifeTime"] = { name = "Life time", type = "FLOAT" },
		["particleSystem.emitters.*.size01"] = { name = "Size01", type = "VECTOR2" },
		["particleSystem.emitters.*.child"] = { name = "Child", type = "MESHID" },
		["particleSystem.emitters.*.velocityDampingFactor"] = { name = "Damping factor", type = "FLOAT" },
		["particleSystem.emitters.*.initialAlpha"] = { name = "Initial alpha", type = "FLOAT" },

		["availability"] = { name = "Availability", type = "TABLE" },
		["availability.yearFrom"] = { name = "Year from", type = "INTEGER" },
		["availability.yearTo"] = { name = "Year to", type = "INTEGER" },

		["cost"] = { name = "Cost", type = "TABLE" },
		["cost.price"] = { name = "Price", type = "INTEGER" },
		
		["description"] = { name = "Description", type = "TABLE" },
		["description.description"] = { name = "Description", type = "STRING" },
		["description.name"] = { name = "Name", type = "STRING" },
		["description.icon"] = { name = "Icon", type = "STRING" },
		["description.smallIcon"] = { name = "Small icon", type = "STRING" },
		["description.icon20"] = { name = "Icon20", type = "STRING" },
		
		["emission"] = { name = "Emission", type = "TABLE" },
		["emission.idleEmission"] = { name = "Idle Emission", type = "INTEGER" },
		["emission.maxPowerEmission"] = { name = "Max Power Emission", type = "INTEGER" },
		["emission.maxSpeedEmission"] = { name = "Max Speed Emission", type = "INTEGER" },
		
		["maintenance"] = { name = "Maintenance", type = "TABLE" },
		["maintenance.runningCosts"] = { name = "Running Costs", type = "INTEGER" },
		["maintenance.lifespan"] = { name = "Lifespan", type = "INTEGER" },
		
		["signal"] = { name = "Signal", type = "TABLE" },
		["signal.type"] = { name = "Type", type = "STRING", values = { "PATH_SIGNAL", "WAYPOINT" , "ONE_WAY_PATH_SIGNAL" } },
		
		["streetTerminal"] = { name = "Street terminal", type = "TABLE" },
		["streetTerminal.cargo"] = { name = "Cargo", type = "BOOLEAN" },
		
		["transportVehicle"] = { name = "Transport vehicle", type = "TABLE" },
		["transportVehicle.carrier"] = { name = "Carrier", type = "STRING", values = { "ROAD", "RAIL", "TRAM", "AIR", "WATER" } },
		["transportVehicle.compartments"] = { name = "Old Compartments", type = "ARRAY" },
		["transportVehicle.compartments.*"] = { name = "Load Configs", type = "ARRAY" },
		["transportVehicle.compartments.*.*"] = { name = "Cargo Entries", type = "ARRAY" },
		["transportVehicle.compartments.*.*.*"] = { name = "Entry", type = "TABLE" },
		["transportVehicle.compartments.*.*.*.type"] = { name = "Type", type = "STRING" },
		["transportVehicle.compartments.*.*.*.capacity"] = { name = "Capacity", type = "INTEGER" },
		["transportVehicle.compartments.*.*.*.cargoBay"] = { name = "Cargo Bay", type = "TABLE" },
		["transportVehicle.compartments.*.*.*.cargoBay.bbMin"] = { name = "bbMin", type = "VECTOR3" },
		["transportVehicle.compartments.*.*.*.cargoBay.bbMax"] = { name = "bbMax", type = "VECTOR3" },
		["transportVehicle.compartments.*.*.*.cargoBay.gridSize"] = { name = "Grid Size", type = "ARRAY" },
		["transportVehicle.compartments.*.*.*.loadIndicators"] = { name = "Load Indicators", type = "ARRAY" },
		["transportVehicle.compartments.*.*.*.loadIndicators.*"] = { name = "Load Indicator", type = "TABLE" },
		["transportVehicle.compartments.*.*.*.loadIndicators.*.type"] = { name = "Type", type = "STRING" },
		["transportVehicle.compartments.*.*.*.loadIndicators.*.params"] = { name = "Parameters", type = "TABLE" },
		["transportVehicle.compartments.*.*.*.loadIndicators.*.params.items"] = { name = "Items", type = "ARRAY" },
		["transportVehicle.compartments.*.*.*.loadIndicators.*.params.items.*"] = { name = "Item", type = "MESHID" },
		["transportVehicle.compartments.*.*.*.loadIndicators.*.params.id"] = { name = "Id", type = "MESHID" },
		["transportVehicle.compartments.*.*.*.loadIndicators.*.params.maxHeight"] = { name = "Max. height", type = "FLOAT" },
		["transportVehicle.compartmentsList"] = { name = "Compartments", type = "ARRAY" },
		["transportVehicle.compartmentsList.*"] = { name = "Compartments", type = "TABLE" },
		["transportVehicle.compartmentsList.*.loadConfigs"] = { name = "Load Configs", type = "ARRAY" },
		["transportVehicle.compartmentsList.*.loadConfigs.*"] = { name = "Load Configs", type = "TABLE" },
		["transportVehicle.compartmentsList.*.loadConfigs.*.toHide"] = { name = "Meshes to hide", type = "ARRAY" },
		["transportVehicle.compartmentsList.*.loadConfigs.*.toHide.*"] = { name = "Meshes to hide", type = "STRING" },
		["transportVehicle.compartmentsList.*.loadConfigs.*.cargoEntries"] = { name = "Cargo Entries", type = "ARRAY" },
		["transportVehicle.compartmentsList.*.loadConfigs.*.cargoEntries.*"] = { name = "Entry", type = "TABLE" },
		["transportVehicle.compartmentsList.*.loadConfigs.*.cargoEntries.*.seats"] = { name = "Seats", type = "ARRAY" },
		["transportVehicle.compartmentsList.*.loadConfigs.*.cargoEntries.*.seats.*"] = { name = "Seats", type = "INTEGER" },
		["transportVehicle.compartmentsList.*.loadConfigs.*.cargoEntries.*.type"] = { name = "Type", type = "STRING" },
		["transportVehicle.compartmentsList.*.loadConfigs.*.cargoEntries.*.capacity"] = { name = "Capacity", type = "INTEGER" },
		["transportVehicle.compartmentsList.*.loadConfigs.*.cargoEntries.*.cargoBay"] = { name = "Cargo Bay", type = "TABLE" },
		["transportVehicle.compartmentsList.*.loadConfigs.*.cargoEntries.*.cargoBay.bbMin"] = { name = "bbMin", type = "VECTOR3" },
		["transportVehicle.compartmentsList.*.loadConfigs.*.cargoEntries.*.cargoBay.bbMax"] = { name = "bbMax", type = "VECTOR3" },
		["transportVehicle.compartmentsList.*.loadConfigs.*.cargoEntries.*.cargoBay.gridSize"] = { name = "Grid Size", type = "ARRAY" },
		["transportVehicle.compartmentsList.*.loadConfigs.*.cargoEntries.*.loadIndicators"] = { name = "Load Indicators", type = "ARRAY" },
		["transportVehicle.compartmentsList.*.loadConfigs.*.cargoEntries.*.loadIndicators.*"] = { name = "Load Indicator", type = "TABLE" },
		["transportVehicle.compartmentsList.*.loadConfigs.*.cargoEntries.*.loadIndicators.*.type"] = { name = "Type", type = "STRING" },
		["transportVehicle.compartmentsList.*.loadConfigs.*.cargoEntries.*.loadIndicators.*.params"] = { name = "Parameters", type = "TABLE" },
		["transportVehicle.compartmentsList.*.loadConfigs.*.cargoEntries.*.loadIndicators.*.params.items"] = { name = "Items", type = "ARRAY" },
		["transportVehicle.compartmentsList.*.loadConfigs.*.cargoEntries.*.loadIndicators.*.params.items.*"] = { name = "Item", type = "MESHID" },
		["transportVehicle.compartmentsList.*.loadConfigs.*.cargoEntries.*.loadIndicators.*.params.id"] = { name = "Id", type = "MESHID" },
		["transportVehicle.compartmentsList.*.loadConfigs.*.cargoEntries.*.loadIndicators.*.params.maxHeight"] = { name = "Max. height", type = "FLOAT" },
		
		["transportVehicle.compartmentsList.*.loadConfigs.*.cargoEntries.*.customCargoModels"] = { name = "Custom Cargo Models", type = "TABLE" },
		["transportVehicle.compartmentsList.*.loadConfigs.*.cargoEntries.*.customCargoModels.configurations"] = { name = "Configurations", type = "ARRAY" },
		["transportVehicle.compartmentsList.*.loadConfigs.*.cargoEntries.*.customCargoModels.configurations.*"] = { name = "Configuration", type = "TABLE" },
		["transportVehicle.compartmentsList.*.loadConfigs.*.cargoEntries.*.customCargoModels.configurations.*.slotLevels"] = { name = "Slot Levels", type = "ARRAY" },
		["transportVehicle.compartmentsList.*.loadConfigs.*.cargoEntries.*.customCargoModels.configurations.*.slotLevels.*"] = { name = "Slot Level", type = "ARRAY" },
		["transportVehicle.compartmentsList.*.loadConfigs.*.cargoEntries.*.customCargoModels.configurations.*.slotLevels.*.*"] = { name = "Cargo Slot", type = "INTEGER" },
		
		["transportVehicle.loadSpeed"] = { name = "Load Speed", type = "FLOAT" },
		["transportVehicle.multipleUnitOnly"] = { name = "Multiple unit only", type = "BOOLEAN" },
		
		["seatProvider"] = { name = "Seat provider", type = "TABLE" },
		["seatProvider.seats"] = { name = "Seats", type = "ARRAY" },
		["seatProvider.seats.*"] = { name = "Seat", type = "TABLE" },
		["seatProvider.seats.*.group"] = { name = "Group", type = "MESHID" },
		["seatProvider.seats.*.transf"] = { name = "Transformation", type = "TRANSF" },
		["seatProvider.seats.*.standing"] = { name = "Standing", type = "BOOLEAN" },
		["seatProvider.seats.*.crew"] = { name = "Crew", type = "BOOLEAN" },
		["seatProvider.drivingLicense"] = { name = "Driving license", type = "STRING", values = { "BUS", "TRUCK", "RAIL", "TRAM", "AIR", "AIR_OUTDOOR", "WATER" } },
		["seatProvider.crewModels"] = { name = "Crew models", type = "ARRAY" },
		["seatProvider.crewModels.*"] = { name = "Crew model", type = "STRING" },
		
		["transportNetworkProvider"] = { name = "Transport network provider", type = "TABLE" },
		["transportNetworkProvider.laneLists"] = { name = "Lane lists", type = "ARRAY" },
		["transportNetworkProvider.laneLists.*"] = { name = "Lane list", type = "TABLE" },
		["transportNetworkProvider.laneLists.*.transportModes"] = { name = "Transport modes", type = "ARRAY" },
		["transportNetworkProvider.laneLists.*.transportModes.*"] = { name = "Transport mode", type = "STRING", values = { "PERSON", "CARGO", "CAR", "BUS", "TRUCK", "TRAM", "ELECTRIC_TRAM", "TRAIN", "ELECTRIC_TRAIN", "AIRCRAFT", "SHIP", "SMALL_AIRCRAFT", "SMALL_SHIP" } },
		["transportNetworkProvider.laneLists.*.nodes"] = { name = "Nodes", type = "ARRAY" },
		["transportNetworkProvider.laneLists.*.nodes.*"] = { name = "Node", type = "TABLE" },
		["transportNetworkProvider.laneLists.*.nodes.*.1"] = { name = "Position", type = "VECTOR3" },
		["transportNetworkProvider.laneLists.*.nodes.*.2"] = { name = "Tangent", type = "VECTOR3" },
		["transportNetworkProvider.laneLists.*.nodes.*.3"] = { name = "Width", type = "FLOAT" },
		["transportNetworkProvider.terminals"] = { name = "Terminals", type = "ARRAY" },
		["transportNetworkProvider.terminals.*"] = { name = "Terminal", type = "TABLE" },
		["transportNetworkProvider.terminals.*.vehicleNode"] = { name = "Vehicle node", type = "INTEGER" },
		["transportNetworkProvider.terminals.*.personNodes"] = { name = "Person nodes", type = "ARRAY" },
		["transportNetworkProvider.terminals.*.personNodes.*"] = { name = "Person node", type = "INTEGER" },
		["transportNetworkProvider.terminals.*.personEdges"] = { name = "Person Edges", type = "ARRAY" },
		["transportNetworkProvider.terminals.*.personNodes.*"] = { name = "Person node", type = "INTEGER" },
		["transportNetworkProvider.runways"] = { name = "Runways", type = "ARRAY" },
		["transportNetworkProvider.runways.*"] = { name = "Runway", type = "TABLE" },
		["transportNetworkProvider.runways.*.type"] = { name = "Type", type = "STRING", values = { "LANDING", "TAKEOFF" } },
		["transportNetworkProvider.runways.*.node"] = { name = "Node", type = "INTEGER" },
		["transportNetworkProvider.runways.*.edges"] = { name = "Edges", type = "ARRAY" },
		["transportNetworkProvider.runways.*.edges.*"] = { name = "Edge", type = "INTEGER" },
		
		["soundConfig"] = { name = "Sound Config", type = "TABLE" },
		["soundConfig.effects"] = { name = "Effects", type = "MAP" },
		["soundConfig.effects.*"] = { name = "Effect", type = "ARRAY" },
		["soundConfig.effects.*.*"] = { name = "File", type = "STRING" },
		["soundConfig.soundSet"] = { name = "Sound Set", type = "TABLE" },
		["soundConfig.soundSet.name"] = { name = "Name", type = "STRING" },
		["soundConfig.soundSet.horn"] = { name = "Horn", type = "STRING" },
		
		["vehicleDepot"] = { name = "Vehicle depot", type = "TABLE" },
		["vehicleDepot.carrier"] = { name = "Carrier", type = "STRING", values = { "ROAD", "RAIL", "TRAM", "AIR", "WATER" } },
		["vehicleDepot.capacity"] = { name = "Capacity", type = "INTEGER" },
		["vehicleDepot.inNodes"] = { name = "In nodes", type = "ARRAY" },
		["vehicleDepot.inNodes.*"] = { name = "In node", type = "INTEGER" },
		["vehicleDepot.outNodes"] = { name = "Out nodes", type = "ARRAY" },
		["vehicleDepot.outNodes.*"] = { name = "Out node", type = "INTEGER" },

		["colorConfig"] = { name = "Color config", type = "TABLE" },
		["colorConfig.configs"] = { name = "Configs", type = "ARRAY" },
		["colorConfig.configs.*"] = { name = "Config", type = "ARRAY" },
		["colorConfig.configs.*.*"] = { name = "Color", type = "COLOR" },
		
		
		["cameraConfig"] = { name = "Camera Config", type = "TABLE" },
		["cameraConfig.positions"] = { name = "Positions", type = "ARRAY" },
		["cameraConfig.positions.*"] = { name = "Position", type = "TABLE" },
		["cameraConfig.positions.*.fov"] = { name = "Field of View", type = "INTEGER" },
		["cameraConfig.positions.*.group"] = { name = "Group", type = "MESHID" },
		["cameraConfig.positions.*.transf"] = { name = "Transformation", type = "TRANSF" },
		
		["labelList"] = { name = "Label list", type = "TABLE" },
		["labelList.labels"] = { name = "Labels", type = "ARRAY" },
		["labelList.labels.*"] = { name = "Label", type = "TABLE" },
		["labelList.labels.*.transf"] = { name = "Transf", type = "TRANSF" },
		["labelList.labels.*.size"] = { name = "Size", type = "VECTOR2" },
		["labelList.labels.*.nLines"] = { name = "Number of Lines", type = "INTEGER" },
		["labelList.labels.*.color"] = { name = "Color", type = "COLOR" },
		["labelList.labels.*.alpha"] = { name = "Alpha", type = "FLOAT" },
		["labelList.labels.*.childId"] = { name = "Child Id", type = "STRING" },
		["labelList.labels.*.params"] = { name = "Params", type = "TABLE" },
		-- ["labelList.labels.*.params.relative"] = { name = "Relative", type = "INTEGER" },
		-- ["labelList.labels.*.params.offset"] = { name = "Offset", type = "INTEGER" },
		-- ["labelList.labels.*.params.expr"] = { name = "Expr", type = "STRING" },
		-- ["labelList.labels.*.params.replace"] = { name = "Replace", type = "STRING" },
		["labelList.labels.*.alignment"] = { name = "Alignment", type = "STRING", values = { "LEFT", "CENTER", "RIGHT" } },
		["labelList.labels.*.verticalAlignment"] = { name = "Alignment", type = "STRING", values = { "BOTTOM", "CENTER", "TOP" } },
		["labelList.labels.*.type"] = { name = "Type", type = "STRING", values = { "NONE", "LINE_NAME", "NEXT_STOP", "NAME", "COMPANY_NAME" , "STATION_NAME" , "CUSTOM" } },
		["labelList.labels.*.fitting"] = { name = "Fitting", type = "STRING", values = { "NONE", "CUT", "SCALE" } },
		["labelList.labels.*.filter"] = { name = "Filter", type = "STRING", values = { "NONE", "NUMBER", "CUSTOM" } },
		["labelList.labels.*.renderMode"] = { name = "Render mode", type = "STRING" , values = { "STD", "EMISSIVE" } },
		["labelList.labels.*.alphaMode"] = { name = "Blend mode", type = "STRING" , values = { "CUTOUT", "BLEND", "NONE"} },
		["labelList.labels.*.font"] = { name = "Font", type = "STRING" },
		
		["cargoSlotProvider"] = { name = "Cargo Slot Provider", type = "TABLE" },
		["cargoSlotProvider.slots"] = { name = "Slots", type = "ARRAY" },
		["cargoSlotProvider.slots.*"] = { name = "Slot", type = "TABLE" },
		["cargoSlotProvider.slots.*.randomId"] = { name = "Random Id", type = "INTEGER" },
		["cargoSlotProvider.slots.*.transf"] = { name = "Transf", type = "TRANSF" },
		["cargoSlotProvider.slots.*.group"] = { name = "Group", type = "MESHID" },
		["cargoSlotProvider.slots.*.models"] = { name = "Models", type = "ARRAY" },
		["cargoSlotProvider.slots.*.models.*"] = { name = "Model", type = "STRING" },
		
		["colliderList"] = { name = "Collider List", type = "TABLE" },
		["colliderList.colliders"] = { name = "Colliders", type = "ARRAY" },
		["colliderList.colliders.*.childId"] = { name = "Child Id", type = "STRING" },
		["colliderList.colliders.*.collider"] = { name = "Collider", type = "TABLE" },
		["colliderList.colliders.*.collider.transf"] = { name = "Transf", type = "TRANSF" },
		["colliderList.colliders.*.collider.type"] = { name = "Type", type = "STRING", values = { "BOX", "CYLINDER", "POINT_CLOUD" } },
		["colliderList.colliders.*.collider.params"] = { name = "Params", type = "TABLE" },
		["colliderList.colliders.*.collider.params.halfExtents"] = { name = "Half Extents", type = "VECTOR3" },

	}
}
end
