function data()
return {
	params = {
		["*.compressionAllowed"] = { name = "Compression allowed (!)", type = "BOOLEAN" },
		["*.fileName"] = { name = "Filename", type = "TEXTURE" },
		["*.magFilter"] = { name = "Mag filter", type = "STRING", values = { "NEAREST", "LINEAR" } },
		["*.minFilter"] = { name = "Min filter (!)", type = "STRING", values = { "NEAREST", "LINEAR", "LINEAR_MIPMAP_LINEAR" } },
		["*.mipmapAlphaScale"] = { name = "Mipmap alpha scale (!)", type = "FLOAT" },
		["*.redGreen"] = { name = "Red-green (!)", type = "BOOLEAN" },
		["*.scaleDownAllowed"] = { name = "Scale down allowed", type = "BOOLEAN" },
		["*.type"] = { name = "Type (!)", type = "STRING", values = { "TWOD", "CUBE_MAP", "TWOD_ARRAY" } },
		["*.wrapS"] = { name = "Wrap s", type = "STRING", values = { "REPEAT", "CLAMP_TO_EDGE" } },
		["*.wrapT"] = { name = "Wrap t", type = "STRING", values = { "REPEAT", "CLAMP_TO_EDGE" } },
		
		["alpha_scale"] = { name = "Alpha scale", type = "TABLE" },
		["alpha_scale.alphaScale"] = { name = "Alpha scale", type = "FLOAT", min = 0, step = 0.05 },
		
		["alpha_scales"] = { name = "Alpha scales", type = "ARRAY" },
		["alpha_scales.*"] = { name = "Alpha scale", type = "TABLE" },
		["alpha_scales.*.alphaScale"] = { name = "Alpha scale", type = "FLOAT", min = 0, step = 0.05 },
		
		["smooth_lod"] = { name = "Smooth LOD", type = "TABLE" },
		["smooth_lod.startDist"] = { name = "Start distance", type = "FLOAT", min = 0, step = 0.05 },
		["smooth_lod.endDist"] = { name = "End distance", type = "FLOAT", min = 0, step = 0.05 },
		
		["alpha_test"] = { name = "Alpha Test", type = "TABLE" },
		["alpha_test.alphaThreshold"] = { name = "Alpha threshold", type = "FLOAT", min = 0, step = 0.05 },
		["alpha_test.a2CThreshold"] = { name = "Alpha 2 Coverage threshold", type = "FLOAT", min = 0, step = 0.05 },
		["alpha_test.cutout"] = { name = "Cut out", type = "BOOLEAN" },
		["alpha_test.sorted"] = { name = "Sorted", type = "BOOLEAN" },
		["alpha_test.disableDepthAndNormalWrite"] = { name = "Disable Depth/Normal Write", type = "BOOLEAN" },

		["color"] = { name = "Color", type = "TABLE" },
		["color.color"] = { name = "Color", type = "LINKED_SLIDER", min = 0, max = 1 },

		["albedo_scale"] = { name = "Albedo scale", type = "TABLE" },
		["albedo_scale.albedoScale"] = { name = "Albedo scale", type = "LINKED_SLIDER", min = 0, max = 2 },
		
		["albedo_scales"] = { name = "Albedo scale", type = "ARRAY" },
		["albedo_scales.*"] = { name = "Albedo scale", type = "TABLE" },
		["albedo_scales.*.albedoScale"] = { name = "Albedo scale", type = "LINKED_SLIDER", min = 0, max = 2 },
		
		["billboard_shadow"] = { name = "Fake Billboard Shadow", type = "TABLE" },
		["billboard_shadow.low"] = { name = "Shadow low", type = "FLOAT", min = 0, max = 1.0, step = 0.05 },
		["billboard_shadow.high"] = { name = "Shadow high", type = "FLOAT", min = 0, max = 1.0, step = 0.05 },
		["billboard_shadow.contrast"] = { name = "Contrast", type = "FLOAT", min = 0, max = 7.0, step = 0.05 },
		["billboard_shadow.vOffset"] = { name = "Vertical offset", type = "FLOAT", min = 0, max = 1.0, step = 0.05 },
		["billboard_shadow.*.radius"] = { name = "Vertical radius", type = "FLOAT", min = 0, max = 3.0, step = 0.05 },
		
		["billboard_shadows"] = { name = "Fake Billboard Shadows", type = "ARRAY" },
		["billboard_shadows.*"] = { name = "Fake Billboard Shadow", type = "TABLE" },
		["billboard_shadows.*.low"] = { name = "Shadow low", type = "FLOAT", min = 0, max = 1.0, step = 0.05 },
		["billboard_shadows.*.high"] = { name = "Shadow high", type = "FLOAT", min = 0, max = 1.0, step = 0.05 },
		["billboard_shadows.*.contrast"] = { name = "Contrast", type = "FLOAT", min = 0, max = 7.0, step = 0.05 },
		["billboard_shadows.*.vOffset"] = { name = "Vertical offset", type = "FLOAT", min = 0, max = 1.0, step = 0.05 },
		["billboard_shadows.*.radius"] = { name = "Vertical radius", type = "FLOAT", min = 0, max = 3.0, step = 0.05 },
		
		["billboards"] = { name = "Billboards", type = "ARRAY" },
		["billboards.*"] = { name = "Billboard", type = "TABLE" },
		["billboards.*.coordsOH"] = { name = "Coords. OH", type = "ARRAY" },
		["billboards.*.coordsOH.*"] = { name = "Coord. OH", type = "FLOAT" },
		["billboards.*.dimension"] = { name = "Dimension", type = "ARRAY" },
		["billboards.*.dimension.*"] = { name = "Dimension", type = "FLOAT" },
		["billboards.*.fadeInEndAngle"] = { name = "Fade in end angle", type = "FLOAT" },
		["billboards.*.fadeInStartAngle"] = { name = "Fade in start angle", type = "FLOAT" },
		["billboards.*.heightOH"] = { name = "Height OH", type = "FLOAT" },
		["billboards.*.texCoords"] = { name = "Texture coordinates", type = "ARRAY" },
		["billboards.*.texCoords.*"] = { name = "Texture coordinate", type = "ARRAY" },
		["billboards.*.texCoords.*.*"] = { name = "Texture coordinate", type = "FLOAT" },
		["billboards.*.bbMin"] = { name = "BB Min", type = "ARRAY" },
		["billboards.*.bbMax"] = { name = "BB Max", type = "ARRAY" },
		
		["color_blend"] = { name = "Color blend", type = "TABLE" },
		["color_blend.albedoScales"] = { name = "Albedo scales", type = "ARRAY" },
		["color_blend.albedoScales.*"] = { name = "Albedo scale", type = "FLOAT", min = 0, step = 0.05 },
		["color_blend.colors"] = { name = "Colors", type = "ARRAY" },
		["color_blend.colors.*"] = { name = "Color", type = "COLOR" },

		["dirt_rust"] = { name = "Dirt / Rust", type = "TABLE" },
		["dirt_rust.dirtColor"] = { name = "Dirt color", type = "COLOR" },
		["dirt_rust.dirtOpacity"] = { name = "Dirt opacity", type = "FLOAT", min = 0, max = 1, step = 0.01 },
		["dirt_rust.dirtScale"] = { name = "Dirt scale", type = "FLOAT", min = 0, step = 0.05 },
		["dirt_rust.rustColor"] = { name = "Rust color", type = "COLOR" },
		["dirt_rust.rustOpacity"] = { name = "Rust opacity", type = "FLOAT", min = 0, max = 1, step = 0.01 },
		["dirt_rust.rustScale"] = { name = "Rust scale", type = "FLOAT", min = 0, step = 0.05 },
		["dirt_rust.age"] = { name = "Age", type = "FLOAT", min = 0, step = 1 },
		
		["fade_out_range"] = { name = "Fade out range", type = "TABLE" },
		["fade_out_range.fadeOutStartDist"] = { name = "Start dist", type = "FLOAT", min = 0, step = 1 },
		["fade_out_range.fadeOutEndDist"] = { name = "End dist", type = "FLOAT", min = 0, step = 1 },
		
		["fade_out_ranges"] = { name = "Fade out ranges", type = "ARRAY" },
		["fade_out_ranges.*"] = { name = "Fade out range", type = "TABLE" },
		["fade_out_ranges.*.fadeOutStartDist"] = { name = "Start dist", type = "FLOAT", min = 0, step = 1 },
		["fade_out_ranges.*.fadeOutEndDist"] = { name = "End dist", type = "FLOAT", min = 0, step = 1 },
		
		["emissive_scale"] = { name = "Emissive scale", type = "TABLE" },
		["emissive_scale.emissiveScale"] = { name = "Emissive scale", type = "LINKED_SLIDER", min = 0, max = 2500 },
		
		["map_albedo"] = { name = "Map albedo", type = "TABLE" },
		["map_albedo_gloss"] = { name = "Map albedo gloss", type = "TABLE" },
		["map_albedo_opacity"] = { name = "Map albedo", type = "TABLE" },
		["map_ao"] = { name = "Map ao", type = "TABLE" },
		["map_cblend"] = { name = "Map cblend", type = "TABLE" },
		["map_cblend_dirt_rust"] = { name = "Map cblend dirt rust", type = "TABLE" },
		["map_color_alpha"] = { name = "Map color alpha", type = "TABLE" },
		["map_dirt"] = { name = "Map dirt", type = "TABLE" },
		["map_dirt_normal"] = { name = "Map dirt normal", type = "TABLE" },
		["map_emissive"] = { name = "Map emissive", type = "TABLE" },
		["map_metal_gloss_ao"] = { name = "Map metal gloss ao", type = "TABLE" },
		["map_normal"] = { name = "Map normal", type = "TABLE" },
		["map_op"] = { name = "Map operation", type = "TABLE" },
		["map_op_1"] = { name = "Map operation 1", type = "TABLE" },
		["map_op_2"] = { name = "Map operation 2", type = "TABLE" },
		["map_rust"] = { name = "Map rust", type = "TABLE" },
		["map_rust_normal"] = { name = "Map rust normal", type = "TABLE" },
        
        ["normal_scale"] = { name = "Normal scale", type = "TABLE" },
		["normal_scale.normalScale"] = { name = "Normal scale", type = "FLOAT", min = 0, step = 0.05 },
		
		["operation"] = { name = "Operation", type = "TABLE" },
		["operation_1"] = { name = "Operation 1", type = "TABLE" },
		["operation_2"] = { name = "Operation 2", type = "TABLE" },
		["*.op"] = { name = "Type", type = "STRING", values = { "NO_OP", "MULTIPLICATION", "OVERLAY", "LINEAR_BURN", "ALPHA_BLEND" } },
		["*.mode"] = { name = "Mode", type = "STRING", values = { "TEXCOORD", "WORLD_XY", "NORMAL", "UV_MODE_TEX_TNG_BIN", "UV_MODE_TNG_BIN", "UV_MODE_REF_NRML", "UV_MODE_WORLD", "UV_MODE_SCALE" } },
		["*.scale"] = { name = "Scale", type = "ARRAY" },
		["*.scale.1"] = { name = "X", type = "FLOAT", min = 0, step = 0.01 },
		["*.scale.2"] = { name = "Y", type = "FLOAT", min = 0, step = 0.01 },
		["*.opacity"] = { name = "Opacity", type = "FLOAT", min = 0, max = 1, step = 0.05 },
		
		["polygon_offset"] = { name = "Polygon offset", type = "TABLE" },
		["polygon_offset.factor"] = { name = "Factor", type = "FLOAT" },
		["polygon_offset.units"] = { name = "Units", type = "FLOAT" },
		
		["props"] = { name = "Basic properties", type = "TABLE" },
		["props.coeffs"] = { name = "Coefficients", type = "ARRAY" },
		["props.coeffs.1"] = { name = "Ka", type = "FLOAT" },
		["props.coeffs.2"] = { name = "Kd", type = "FLOAT" },
		["props.coeffs.3"] = { name = "Ks", type = "FLOAT" },
		["props.coeffs.4"] = { name = "Shininess", type = "FLOAT" },
		
		["two_sided"] = { name = "Two sided", type = "TABLE" },
		["two_sided.flipNormal"] = { name = "Flip normal", type = "BOOLEAN" },
		["two_sided.twoSided"] = { name = "Two sided", type = "BOOLEAN" },
		
		["map_logo"] = { name = "Map logo", type = "STRING" },
	}
}
end
