#version 150
/// BEGIN AUTOGENERATED HEADER
#define CONC(a,b) a##b

#define IF(c, t, e) CONC(IF_, c)(t, e)

#define IF_UNDEF(t, e) e
#define IF_0(t, e) t
#define IF_1(t, e) t
#define IF_2(t, e) t
#define IF_3(t, e) t
#define IF_4(t, e) t
#define IF_5(t, e) t
#define IF_6(t, e) t
#define IF_7(t, e) t
#define IF_8(t, e) t
#define IF_9(t, e) t
#define IF_10(t, e) t
#define IF_11(t, e) t
#define IF_12(t, e) t
#define IF_13(t, e) t
#define IF_14(t, e) t
#define IF_15(t, e) t
#define IF_16(t, e) t
// Workaround for intel HD:
#define IF_00(t, e) t
#ifdef UG_COMPILE_SPIRV
	#define gl_VertexID gl_VertexIndex

	#define LAYOUT_SAMPLER2(s, b) layout(set = s, binding = b)
	#define LAYOUT_SAMPLER(s, b) layout(set = s, binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, set = s, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(push_constant, std140)
	#define LAYOUT_STORAGE(s, b) layout(std140, set = s, binding = b) readonly restrict buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) IF(loc, layout (location = loc) mod in type name, const type name = defaultValue)
		
	#define INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)

	#define OUTPUT(loc, type, name) IF(loc, layout (location = loc) out type name, type name)
	
	#define OUTPUT_MOD(loc, mod, type, name) IF(loc, layout (location = loc) mod out type name, type name)
	
	#define WINDING ccw

	#define LOCATION(loc) layout(location = loc) 
#else
	#extension GL_ARB_separate_shader_objects : require
	#extension GL_ARB_explicit_attrib_location : require
	#extension GL_ARB_shading_language_420pack : require

#ifdef USE_SAMPLER2
	#define LAYOUT_SAMPLER2(s, b)
#else
	#define LAYOUT_SAMPLER2(s, b) layout(binding = b)
#endif

	#define LAYOUT_SAMPLER(s, b) layout(binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(std140, binding = 2)
	#define LAYOUT_STORAGE(s, b) layout(std140, binding = b) buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) mod in type name
		
	#define INPUT(loc, type, name, defaultValue) in type name

	#define OUTPUT(loc, type, name) out type name
	
	#define OUTPUT_MOD(loc, mod, type, name) mod out type name
	
	#define WINDING ccw

	#define LOCATION(loc)
#endif
/// END AUTOGENERATED HEADER

LAYOUT_SAMPLER(2, 25) uniform sampler2D normalTex;
LAYOUT_SAMPLER(1, 26) uniform sampler2D waterDepthTex;
LAYOUT_SAMPLER(1, 27) uniform sampler2D foamTex;
LAYOUT_SAMPLER(1, 28) uniform sampler2D foamDetailTex;

LAYOUT_UBO(0, 10) uniform View {
	mat4 projView;
	mat4 projViewInverse;
	mat4 proj;
	mat4 projInverse;
	mat4 view;
	mat4 viewInverse;
	vec3 camPos;
	float lodFactor;
	float near;
	float far;
} u_view;

LAYOUT_UBO(2, 14) uniform Water2 {
	vec2 fragCoordScale;
	vec2 fragCoordOfs;

	float time;

	float turbAlpha;
} u_water;

INPUT(POS_LOC, vec4, posAmbient, vec4(1.0)); // ambient = length!
INPUT_MOD(TC_LOC, centroid, vec3, texCoordAlpha, vec3(1.0));

vec3 rgbToNormal(vec3 rgb);
void fragmentOutput(vec3 pos, float ambient, vec3 normal, vec3 albedo, float metalness, float glossiness, float alpha);

vec3 getNormal(vec2 uv) {
	vec4 col = texture(normalTex, uv);
	return vec3(u_view.viewInverse * vec4(rgbToNormal(col.rgb), .0));
}

void main() {
	if (posAmbient.w < .01) discard;
	
	vec3 waterCol = pow(texture(waterDepthTex, vec2(.25, .0)).rgb, vec3(2.2));
	
	vec2 texCoord = gl_FragCoord.xy * u_water.fragCoordScale + u_water.fragCoordOfs;
	vec3 normal = getNormal(texCoord);

	vec2 scaledUV = .25 * posAmbient.xy + pow(posAmbient.w, 2.0) * normal.xy + 1e-6 * texCoordAlpha.xy;
	float scroll = .1 * u_water.time;

	float r = texture(foamTex, scaledUV - vec2(scroll, .1 * cos(posAmbient.x))).r;
	float g = texture(foamTex, .5 * scaledUV - vec2(.1 * sin(posAmbient.y), scroll)).g;
	float b = texture(foamTex, scaledUV - vec2(.1 * sin(posAmbient.y), scroll)).b;
	
	float mask = clamp(pow(.95 * (r + g + .25 * b), 2.0) + .5, .0, 1.0);
	
	vec3 foamTexel = texture(foamDetailTex, .1 * posAmbient.xy + .05 * normal.xy - .1 * vec2(scroll, .1 * cos(posAmbient.x))).xyz;
	
	float alpha = clamp(1.0 - (1.0 - .95 * foamTexel.b * mask ) / posAmbient.w, .0, 1.0);
	
	vec3 turbColor = mix(vec3(1.0), waterCol, .25);
	float turbAlpha2 = max(u_water.turbAlpha * mask * posAmbient.w *(1.0 - alpha), .0);
	
	foamTexel = mix(waterCol, foamTexel, .95 * alpha);
	
	vec3 finalColor = foamTexel * alpha + turbColor * turbAlpha2;
	float finalAlpha = max(alpha, turbAlpha2);
	
	fragmentOutput(posAmbient.xyz, 1.0, normal, finalColor, .0, .0, finalAlpha);
}
