#version 150
/// BEGIN AUTOGENERATED HEADER
#define CONC(a,b) a##b

#define IF(c, t, e) CONC(IF_, c)(t, e)

#define IF_UNDEF(t, e) e
#define IF_0(t, e) t
#define IF_1(t, e) t
#define IF_2(t, e) t
#define IF_3(t, e) t
#define IF_4(t, e) t
#define IF_5(t, e) t
#define IF_6(t, e) t
#define IF_7(t, e) t
#define IF_8(t, e) t
#define IF_9(t, e) t
#define IF_10(t, e) t
#define IF_11(t, e) t
#define IF_12(t, e) t
#define IF_13(t, e) t
#define IF_14(t, e) t
#define IF_15(t, e) t
#define IF_16(t, e) t
// Workaround for intel HD:
#define IF_00(t, e) t
#ifdef UG_COMPILE_SPIRV
	#define gl_VertexID gl_VertexIndex

	#define LAYOUT_SAMPLER2(s, b) layout(set = s, binding = b)
	#define LAYOUT_SAMPLER(s, b) layout(set = s, binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, set = s, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(push_constant, std140)
	#define LAYOUT_STORAGE(s, b) layout(std140, set = s, binding = b) readonly restrict buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) IF(loc, layout (location = loc) mod in type name, const type name = defaultValue)
		
	#define INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)

	#define OUTPUT(loc, type, name) IF(loc, layout (location = loc) out type name, type name)
	
	#define OUTPUT_MOD(loc, mod, type, name) IF(loc, layout (location = loc) mod out type name, type name)
	
	#define WINDING ccw

	#define LOCATION(loc) layout(location = loc) 
#else
	#extension GL_ARB_separate_shader_objects : require
	#extension GL_ARB_explicit_attrib_location : require
	#extension GL_ARB_shading_language_420pack : require

#ifdef USE_SAMPLER2
	#define LAYOUT_SAMPLER2(s, b)
#else
	#define LAYOUT_SAMPLER2(s, b) layout(binding = b)
#endif

	#define LAYOUT_SAMPLER(s, b) layout(binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(std140, binding = 2)
	#define LAYOUT_STORAGE(s, b) layout(std140, binding = b) buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) mod in type name
		
	#define INPUT(loc, type, name, defaultValue) in type name

	#define OUTPUT(loc, type, name) out type name
	
	#define OUTPUT_MOD(loc, mod, type, name) mod out type name
	
	#define WINDING ccw

	#define LOCATION(loc)
#endif
/// END AUTOGENERATED HEADER

LAYOUT_SAMPLER(2, 25) uniform sampler2D normalTex;
LAYOUT_SAMPLER(1, 28) uniform sampler2D foamDetailTex;

LAYOUT_UBO(0, 10) uniform View {
	mat4 projView;
	mat4 projViewInverse;
	mat4 proj;
	mat4 projInverse;
	mat4 view;
	mat4 viewInverse;
	vec3 camPos;
	float lodFactor;
	float near;
	float far;
} u_view;

LAYOUT_UBO(2, 14) uniform Water {
	vec2 fragCoordScale;
	vec2 fragCoordOfs;

	float time;

	float fadeOutStart;
	float fadeOutEnd;
} u_water;

INPUT(POS_LOC, vec4, posAmbient, vec4(1.0)); // ambient = length!
INPUT_MOD(TC_LOC, centroid, vec3, texCoordAlpha, vec3(1.0));

vec3 rgbToNormal(vec3 rgb);
void fragmentOutput(vec3 pos, float ambient, vec3 normal, vec3 albedo, float metalness, float glossiness, float alpha);

vec3 getNormal(vec2 uv) {
	vec4 col = texture(normalTex, uv);
	return vec3(u_view.viewInverse * vec4(rgbToNormal(col.rgb), .0));
}

const float PI = 3.14159;

float Pn(float f, float x, float seed) { return .5 * (1.0 + sin(2.0 * PI * (1.0 / f) * (x + 3.33 * seed))); }

const float animWaveExtendDur = 5.0;
const float animWaveRetractDur = 10.0;
const float animPause = 5.0;
const float animDurTotal = animWaveExtendDur + animWaveRetractDur + animPause;

vec4 CreateAnimatedWave(float t, vec3 normal) {
	float animRelDur0 = animWaveExtendDur / animDurTotal;
	float animRelDur1 = animWaveRetractDur / animDurTotal;
	
	float animRelStart1 = animRelDur0;
	float animRelStart2 = animRelStart1 + animRelDur1;
	
	float animTime = t / animDurTotal;
	float timeParam = fract(animTime);
	float animIdx = animTime - timeParam;
	
	float t0 = fract(clamp(timeParam / animRelDur0, .0, 1.0));
	float t1 = fract(clamp((timeParam - animRelDur0) / animRelDur1, .0, 1.0));
	
	float animU0 = timeParam < animRelStart1 ? .5 * (Pn(4.0, t0, .0) - 1.0) : timeParam < animRelStart2 ? - .5 * (1.0 - cos(PI * t1)) : .0;
	float animU1 = timeParam < animRelStart1 ? sin(.5 * PI * t0) : timeParam < animRelStart2 ? 1.0 - .5 * (1.0 - cos(PI * t1)) : .0;
	
	float maxUoffset = .1;
	float uOffset0 = mix(Pn(10.0, posAmbient.w, animIdx), Pn(7.0, posAmbient.w, animIdx), .25);
	float uOffset1 = mix(uOffset0, Pn(3.0, posAmbient.w, animIdx), .25);
	
	float uOffsetAbs = 1.0 - pow(clamp(sin(PI * texCoordAlpha.y), .0, 1.0), 1.0 / 4.0);
	
	float uMax = 1.0 + maxUoffset * (uOffset1 - 1.0) - uOffsetAbs;
	float uMin = .0 + maxUoffset * uOffset0;
	uMin *= (1.0 - uOffsetAbs);
	
	float u = texCoordAlpha.x + .5 * (normal.x + normal.y);
	u = (u - uMin) / (uMax - uMin);
	
	const float e = 4.0;
	float foamU = 1.0 / (1.0 - animU0) * (u + (1.0 - animU1) / pow(animU1, e) * pow(u, e) - animU0);
	
	vec4 result = texture(foamDetailTex, vec2(foamU, .05 * posAmbient.w));
	
	result.a = (animU1 == .0 || foamU >= 1.0 || foamU <= .0 || timeParam >= animRelStart2) ? .0 : 1.0;
	result.a *= clamp(1.0 - (1.0 - .95 * result.g) / clamp(u, .0, 1.0) , .0, 1.0);
	result.a *= clamp(1.0 - t1, .0, 1.0);
	
	return result;
}

void main() {
	vec3 viewVec = u_view.viewInverse[3].xyz - posAmbient.xyz;
	float viewDist = length(viewVec);
	float fadeOutAlpha = clamp((u_water.fadeOutStart -  viewDist) / (u_water.fadeOutEnd - u_water.fadeOutStart), .0, 1.0);
	
	vec2 texCoord = gl_FragCoord.xy * u_water.fragCoordScale + u_water.fragCoordOfs + 1e-6 * texCoordAlpha.xy;
	vec3 normal = getNormal(texCoord);
	
	float localTime = u_water.time + .75 * animDurTotal *
		(Pn(200.0, posAmbient.x + u_water.time, .0) + Pn(200.0, posAmbient.y + u_water.time, .0) +
		 Pn(1000.0, posAmbient.x + 2.0 * u_water.time, .0) + Pn(1000.0, posAmbient.y + 2.0 * u_water.time, .0));
	
	vec4 waveColor0 = CreateAnimatedWave(localTime, normal);
	vec4 waveColor1 = CreateAnimatedWave(localTime - .5 * animDurTotal, normal);
	
	float alpha = waveColor0.a + (1.0 - waveColor0.a) * waveColor1.a;
	vec3 color = (waveColor0.rgb * waveColor0.a + (1.0 - waveColor0.a) * waveColor1.rgb * waveColor1.a) / alpha;
	
	alpha *= fadeOutAlpha;
	
	if (alpha < .01) discard;

	fragmentOutput(posAmbient.xyz, 1.0, normal, color, .0, .0, alpha);
}
