#version 150
/// BEGIN AUTOGENERATED HEADER
#define CONC(a,b) a##b

#define IF(c, t, e) CONC(IF_, c)(t, e)

#define IF_UNDEF(t, e) e
#define IF_0(t, e) t
#define IF_1(t, e) t
#define IF_2(t, e) t
#define IF_3(t, e) t
#define IF_4(t, e) t
#define IF_5(t, e) t
#define IF_6(t, e) t
#define IF_7(t, e) t
#define IF_8(t, e) t
#define IF_9(t, e) t
#define IF_10(t, e) t
#define IF_11(t, e) t
#define IF_12(t, e) t
#define IF_13(t, e) t
#define IF_14(t, e) t
#define IF_15(t, e) t
#define IF_16(t, e) t
// Workaround for intel HD:
#define IF_00(t, e) t
#ifdef UG_COMPILE_SPIRV
	#define gl_VertexID gl_VertexIndex

	#define LAYOUT_SAMPLER2(s, b) layout(set = s, binding = b)
	#define LAYOUT_SAMPLER(s, b) layout(set = s, binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, set = s, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(push_constant, std140)
	#define LAYOUT_STORAGE(s, b) layout(std140, set = s, binding = b) readonly restrict buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) IF(loc, layout (location = loc) mod in type name, const type name = defaultValue)
		
	#define INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)

	#define OUTPUT(loc, type, name) IF(loc, layout (location = loc) out type name, type name)
	
	#define OUTPUT_MOD(loc, mod, type, name) IF(loc, layout (location = loc) mod out type name, type name)
	
	#define WINDING ccw

	#define LOCATION(loc) layout(location = loc) 
#else
	#extension GL_ARB_separate_shader_objects : require
	#extension GL_ARB_explicit_attrib_location : require
	#extension GL_ARB_shading_language_420pack : require

#ifdef USE_SAMPLER2
	#define LAYOUT_SAMPLER2(s, b)
#else
	#define LAYOUT_SAMPLER2(s, b) layout(binding = b)
#endif

	#define LAYOUT_SAMPLER(s, b) layout(binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(std140, binding = 2)
	#define LAYOUT_STORAGE(s, b) layout(std140, binding = b) buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) mod in type name
		
	#define INPUT(loc, type, name, defaultValue) in type name

	#define OUTPUT(loc, type, name) out type name
	
	#define OUTPUT_MOD(loc, mod, type, name) mod out type name
	
	#define WINDING ccw

	#define LOCATION(loc)
#endif
/// END AUTOGENERATED HEADER

LAYOUT_SAMPLER2(2, 23) uniform sampler2D colorTex;
LAYOUT_SAMPLER2(2, 26) uniform sampler2D waterDepthTex;
LAYOUT_SAMPLER2(1, 27) uniform sampler2D depthColorTex;

LAYOUT_UBO(0, 10) uniform View {
	mat4 projView;
	mat4 projViewInverse;
	mat4 proj;
	mat4 projInverse;
	mat4 view;
	mat4 viewInverse;
	vec3 camPos;
	float lodFactor;
	float near;
	float far;
} u_view;

LAYOUT_UBO(0, 6) uniform Light {
	vec3 lightDir;
	float lightScale;
	mat4 lightTransf;
	mat4 lightInvTransf;
	float ambientScale;
} u_light;

LAYOUT_UBO(2, 14) uniform Water {
	vec2 fragCoordScale;
	vec2 fragCoordOfs;

	vec2 fragCoordReflScale;
	vec2 fragCoordReflOfs;

	vec2 nearFar;
	float fovY;

	float roughness;
	float particleDensity;
	float extinctionCoeff;
} u_water;

INPUT(POS_LOC, vec4, posAmbient, vec4(1.0));

#define MULTI_SAMPLE

const float PI = 3.14159;
const float halfPi = 1.5707963;

vec4 getLight0(vec3 dir, float lod);
vec4 getLight1(vec3 dir, float lod);
vec3 applyFog(vec3 color);
float compShadow(vec3 vpos);
vec3 rgbToNormal(vec3 rgb);
void fragmentOutputCustomColor(vec4 color);

// water_common.fs
vec3 getPosFromDepth(float depth);
vec3 getNormal(vec2 uv);
float getFresnelTerm(float ti);
void calcReflection(vec3 viewDir, vec2 maxXangles, vec2 maxYangles, vec2 tcOffset, float reflLod, inout vec3 normal, inout vec3 color);

void main() {
	vec3 vpos = posAmbient.xyz;

	vec3 viewVec = u_view.viewInverse[3].xyz - vpos;
	float len1 = inversesqrt(dot(viewVec, viewVec));
	vec3 viewDir = viewVec * len1;
	
	float totalPosD = abs(fwidth(vpos.x)) + abs(fwidth(vpos.y));
	float lodFactor = log(totalPosD + 1.0) / log(10.0);
	lodFactor += u_water.roughness * 2.0; // TODO max lod?
	float reflLod = clamp(lodFactor, .0, 6.0);
	
	///
	vec2 groundTc = gl_FragCoord.xy * u_water.fragCoordScale + u_water.fragCoordOfs;
	
	vec3 groundColor = texture(colorTex, groundTc).rgb;
	
	float groundDepthZ = texture(waterDepthTex, groundTc).x;
	vec3 waterPos = getPosFromDepth(gl_FragCoord.z);
	
	vec3 groundPos = getPosFromDepth(groundDepthZ);
	
    float groundZ = length(u_view.viewInverse[3].xyz - groundPos);
	float waterZ = length(u_view.viewInverse[3].xyz - waterPos);
	///
	
	///
	float groundSurfaceDepth = max(waterPos.z - groundPos.z, .0);
	float lightGroundTransm = exp(-groundSurfaceDepth * u_water.extinctionCoeff);
	float lightGroundAtten = 1.0 - lightGroundTransm;
	
	float underWaterDist = max(groundZ - waterZ, .0);
	if (groundZ < waterZ - 4.0) underWaterDist = 20.0;
	float groundViewTransm = exp(-underWaterDist * u_water.extinctionCoeff);
	float groundViewAtten = 1.0 - groundViewTransm;
	///
	
	vec3 viewYaxis = normalize(vec3(viewDir.xy, .0));
	
	vec3 estimatedShorePos = waterPos - underWaterDist * viewYaxis;
	vec3 shoreToEye = normalize(u_view.viewInverse[3].xyz - estimatedShorePos);
	float shoreAngle = acos(dot(viewDir, shoreToEye));
	
	float viewAngle = acos(dot(viewDir, vec3(0, 0, 1)));
	
	float maxAngle = shoreAngle;//mix(shoreAngle, .5 * u_water.fovY, clamp((u_view.viewInverse[3].z - waterPos.z - 100.0) / 500.0, .0, 1.0));
	
	vec2 maxXangles = vec2(-maxAngle, maxAngle);
	vec2 maxYangles = vec2(-maxAngle, halfPi + viewAngle);

#ifdef MULTI_SAMPLE
	vec3 n0 = vec3(.0, .0, 1.0);
	vec3 c0 = vec3(1.0);
	calcReflection(viewDir, maxXangles, maxYangles, vec2(.0), reflLod, n0, c0);
	
	float sampleOffset = 1.0;
	
	vec3 nx0 = vec3(.0, .0, 1.0);
	vec3 cx0 = vec3(1.0);
	calcReflection(viewDir, maxXangles, maxYangles, sampleOffset * vec2(-1.0, .0), reflLod, nx0, cx0);
	vec3 nx1 = vec3(.0, .0, 1.0);
	vec3 cx1 = vec3(1.0);
	calcReflection(viewDir, maxXangles, maxYangles, sampleOffset * vec2(1.0, .0), reflLod, nx1, cx1);
	
	vec3 ny0 = vec3(.0, .0, 1.0);
	vec3 cy0 = vec3(1.0);
	calcReflection(viewDir, maxXangles, maxYangles, sampleOffset * vec2(.0, -1.0), reflLod, ny0, cy0);
	vec3 ny1 = vec3(.0, .0, 1.0);
	vec3 cy1 = vec3(1.0);
	calcReflection(viewDir, maxXangles, maxYangles, sampleOffset * vec2(.0, 1.0), reflLod, ny1, cy1);
	
	vec3 normal = n0;
	vec3 reflCol = (4 * c0 + cx0 + cx1 + cy0 + cy1) / 8.0;
#else
	vec3 normal = vec3(.0, .0, 1.0);
	vec3 reflCol = vec3(1.0);
	
	calcReflection(viewDir, maxXangles, maxYangles, vec2(.0), reflLod, normal, reflCol);
#endif
	
	float nDotR = max(dot(normal, viewDir), .0);
	
	float theta = acos(nDotR);
	float specRefl = getFresnelTerm(theta);
	
	/// water color
	const float numLevels = 16.0;
	
	float normalFactor = 1.0 - length(normal.xy);
	
	float depthF = .5 * (groundViewAtten + lightGroundAtten) * normalFactor;
	float levelf = depthF * (numLevels - 1);
	float df = fract(levelf);
	float level0 = levelf - df;
	float level1 = level0 + 1;
	
	vec3 waterCol0 = pow(texture(depthColorTex, vec2((level0 + .5) / numLevels, .0)).rgb, vec3(2.2));
	vec3 waterCol1 = pow(texture(depthColorTex, vec2((level1 + .5) / numLevels, .0)).rgb, vec3(2.2));
	vec3 waterCol = mix(waterCol0, waterCol1, df);
	
	vec3 baseWaterCol = pow(texture(depthColorTex, vec2(1.0, .0)).rgb, vec3(2.2));
	///
	
	int viewSamples = 1;
	float step = underWaterDist / viewSamples;
	
	float shadow = .0;
	vec3 dir = normalize(vpos - u_view.viewInverse[3].xyz);
	
	float testDist = .0;
	float extSum = .0;
	
	for (int i = 0; i < viewSamples; i++) {
		vec3 testPos = vpos + dir * testDist;
		
		float extinction = exp(-testDist * u_water.extinctionCoeff);
		extSum += extinction;
		
		shadow += compShadow(testPos) * extinction;
		
		testDist += step;
	}
	
	shadow /= extSum;
	
	float maxLod = 6.0;
	vec3 diffLight0 = getLight0(vec3(.0, .0, 1.0), maxLod).rgb;
	vec3 diffLight1 = getLight1(vec3(.0, .0, 1.0), maxLod).rgb;
	
	vec3 diffLight = u_light.lightScale * (diffLight0 + shadow * (diffLight1 - diffLight0)) * baseWaterCol;
	diffLight *= pow(groundViewAtten, .25); // TODO HACK
	
	vec3 groundColorPart = lightGroundTransm * groundColor * waterCol * groundViewTransm * waterCol;
	vec3 refracedPart = diffLight + groundColorPart;
	
	vec3 col = mix(refracedPart, reflCol, specRefl);
	// float alpha = clamp(groundSurfaceDepth * 4, 0.0, 1.0);
	float alpha = 1.0;
	
	fragmentOutputCustomColor(vec4(applyFog(col), alpha));
}
