#version 150
/// BEGIN AUTOGENERATED HEADER
#define CONC(a,b) a##b

#define IF(c, t, e) CONC(IF_, c)(t, e)

#define IF_UNDEF(t, e) e
#define IF_0(t, e) t
#define IF_1(t, e) t
#define IF_2(t, e) t
#define IF_3(t, e) t
#define IF_4(t, e) t
#define IF_5(t, e) t
#define IF_6(t, e) t
#define IF_7(t, e) t
#define IF_8(t, e) t
#define IF_9(t, e) t
#define IF_10(t, e) t
#define IF_11(t, e) t
#define IF_12(t, e) t
#define IF_13(t, e) t
#define IF_14(t, e) t
#define IF_15(t, e) t
#define IF_16(t, e) t
// Workaround for intel HD:
#define IF_00(t, e) t
#ifdef UG_COMPILE_SPIRV
	#define gl_VertexID gl_VertexIndex

	#define LAYOUT_SAMPLER2(s, b) layout(set = s, binding = b)
	#define LAYOUT_SAMPLER(s, b) layout(set = s, binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, set = s, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(push_constant, std140)
	#define LAYOUT_STORAGE(s, b) layout(std140, set = s, binding = b) readonly restrict buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) IF(loc, layout (location = loc) mod in type name, const type name = defaultValue)
		
	#define INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)

	#define OUTPUT(loc, type, name) IF(loc, layout (location = loc) out type name, type name)
	
	#define OUTPUT_MOD(loc, mod, type, name) IF(loc, layout (location = loc) mod out type name, type name)
	
	#define WINDING ccw

	#define LOCATION(loc) layout(location = loc) 
#else
	#extension GL_ARB_separate_shader_objects : require
	#extension GL_ARB_explicit_attrib_location : require
	#extension GL_ARB_shading_language_420pack : require

#ifdef USE_SAMPLER2
	#define LAYOUT_SAMPLER2(s, b)
#else
	#define LAYOUT_SAMPLER2(s, b) layout(binding = b)
#endif

	#define LAYOUT_SAMPLER(s, b) layout(binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(std140, binding = 2)
	#define LAYOUT_STORAGE(s, b) layout(std140, binding = b) buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) mod in type name
		
	#define INPUT(loc, type, name, defaultValue) in type name

	#define OUTPUT(loc, type, name) out type name
	
	#define OUTPUT_MOD(loc, mod, type, name) mod out type name
	
	#define WINDING ccw

	#define LOCATION(loc)
#endif
/// END AUTOGENERATED HEADER

LAYOUT_SAMPLER(1, 25) uniform sampler2D normalTex;

LAYOUT_UBO(2, 15) uniform WaterExtra {
	float speed;
	float normalScale;
	bool invertWeights;
} u_water;

INPUT(POS_LOC, vec4, posAmbient, vec4(1.0));
INPUT_MOD(TC_LOC, centroid, vec3, texCoordAlpha, vec3(1.0));

void fragmentOutputCustomNormal(vec4 normal);
vec3 decodeNormalScale(vec2 color, float scale);

vec2 rotate(vec2 pos, float angle) {
	float c = cos(angle);
	float s = sin(angle);
	return vec2(c*pos.x - s*pos.y, s*pos.x + c*pos.y);
}

vec3 combineNormal(vec3 n0, vec3 n1) {
	return vec3(n0.xy * n1.z + n1.xy * n0.z, n0.z * n1.z);
}

void main() {
	const float PI_THIRD = 1.04719755;
	float waterDepth = texCoordAlpha.y;
	
	vec3 normal = vec3(.0, .0, 1.0);
	
	float s = 2.0;
	float sum = .0;
	for (int i = 0; i < 6; ++i) {	
		vec2 tc = posAmbient.xy / (10.0 * s);
		tc += rotate(vec2(u_water.speed, .0), PI_THIRD * i);
		
		normal = combineNormal(normal, decodeNormalScale(texture(normalTex, tc).rg, u_water.invertWeights ? 1.0 / s : s));
	
		sum += u_water.invertWeights ? 1.0 / s : s;
		s *= 1.5;
	}
	
	float depthScale = .5 * (log(waterDepth + 5.0) - log(4.0)) / log(2.0);
	
	normal = normalize(vec3(u_water.normalScale * depthScale * (1.0 / sum) * normal.xy, normal.z));
	
	fragmentOutputCustomNormal(vec4(normal, 1.0));
}
