#version 150
/// BEGIN AUTOGENERATED HEADER
#define CONC(a,b) a##b

#define IF(c, t, e) CONC(IF_, c)(t, e)

#define IF_UNDEF(t, e) e
#define IF_0(t, e) t
#define IF_1(t, e) t
#define IF_2(t, e) t
#define IF_3(t, e) t
#define IF_4(t, e) t
#define IF_5(t, e) t
#define IF_6(t, e) t
#define IF_7(t, e) t
#define IF_8(t, e) t
#define IF_9(t, e) t
#define IF_10(t, e) t
#define IF_11(t, e) t
#define IF_12(t, e) t
#define IF_13(t, e) t
#define IF_14(t, e) t
#define IF_15(t, e) t
#define IF_16(t, e) t
// Workaround for intel HD:
#define IF_00(t, e) t
#ifdef UG_COMPILE_SPIRV
	#define gl_VertexID gl_VertexIndex

	#define LAYOUT_SAMPLER2(s, b) layout(set = s, binding = b)
	#define LAYOUT_SAMPLER(s, b) layout(set = s, binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, set = s, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(push_constant, std140)
	#define LAYOUT_STORAGE(s, b) layout(std140, set = s, binding = b) readonly restrict buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) IF(loc, layout (location = loc) mod in type name, const type name = defaultValue)
		
	#define INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)

	#define OUTPUT(loc, type, name) IF(loc, layout (location = loc) out type name, type name)
	
	#define OUTPUT_MOD(loc, mod, type, name) IF(loc, layout (location = loc) mod out type name, type name)
	
	#define WINDING ccw

	#define LOCATION(loc) layout(location = loc) 
#else
	#extension GL_ARB_separate_shader_objects : require
	#extension GL_ARB_explicit_attrib_location : require
	#extension GL_ARB_shading_language_420pack : require

#ifdef USE_SAMPLER2
	#define LAYOUT_SAMPLER2(s, b)
#else
	#define LAYOUT_SAMPLER2(s, b) layout(binding = b)
#endif

	#define LAYOUT_SAMPLER(s, b) layout(binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(std140, binding = 2)
	#define LAYOUT_STORAGE(s, b) layout(std140, binding = b) buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) mod in type name
		
	#define INPUT(loc, type, name, defaultValue) in type name

	#define OUTPUT(loc, type, name) out type name
	
	#define OUTPUT_MOD(loc, mod, type, name) mod out type name
	
	#define WINDING ccw

	#define LOCATION(loc)
#endif
/// END AUTOGENERATED HEADER

LAYOUT_UBO(0, 10) uniform View {
	mat4 projView;
	mat4 projViewInverse;
	mat4 proj;
	mat4 projInverse;
	mat4 view;
	mat4 viewInverse;
	vec3 camPos;
	float lodFactor;
	float near;
	float far;
} u_view;

LAYOUT_PUSH_CONSTANT() uniform PushConstant {
	vec4 color_;
} u_const;

INPUT(POS_LOC, vec4, posAmbient, vec4(1.0));

const float halfPi = 1.5707963;

vec4 getColor(vec4 posAmbient, vec4 color);
void fragmentOutput(vec3 pos, float ambient, vec3 normal, vec3 albedo, float metalness, float glossiness, float alpha);

// water_common.fs
float getFresnelTerm(float ti);
void calcReflection(vec3 viewDir, vec2 maxXangles, vec2 maxYangles, vec2 tcOffset, float reflLod, inout vec3 normal, inout vec3 color);

void main() {
	vec4 col = getColor(posAmbient, u_const.color_);

	vec3 vpos = posAmbient.xyz;
	
	float reflLod = 2.0 * clamp(.5 * (abs(fwidth(vpos.x)) + abs(fwidth(vpos.y))), .0, 1.0);
	
	vec3 viewVec = u_view.viewInverse[3].xyz - vpos;
	float len1 = inversesqrt(dot(viewVec, viewVec));
	vec3 viewDir = viewVec * len1;
	
	vec3 normal = vec3(.0, .0, 1.0);
	vec3 reflCol = vec3(1.0);
	
	calcReflection(viewDir, vec2(-halfPi, halfPi), vec2(-halfPi, halfPi), vec2(.0), .0, normal, reflCol);
	
	float nDotR = max(dot(normal, viewDir), .0);
	
	float theta = acos(nDotR);
	float specRefl = getFresnelTerm(theta);

	float maxTransp = col.a;

	float alpha = 1.0 - (1.0 - maxTransp) * (1.0 - specRefl);

	fragmentOutput(posAmbient.xyz, posAmbient.w, normal, col.rgb, .0, 1.0, alpha);
}
