#version 150
/// BEGIN AUTOGENERATED HEADER
#define CONC(a,b) a##b

#define IF(c, t, e) CONC(IF_, c)(t, e)

#define IF_UNDEF(t, e) e
#define IF_0(t, e) t
#define IF_1(t, e) t
#define IF_2(t, e) t
#define IF_3(t, e) t
#define IF_4(t, e) t
#define IF_5(t, e) t
#define IF_6(t, e) t
#define IF_7(t, e) t
#define IF_8(t, e) t
#define IF_9(t, e) t
#define IF_10(t, e) t
#define IF_11(t, e) t
#define IF_12(t, e) t
#define IF_13(t, e) t
#define IF_14(t, e) t
#define IF_15(t, e) t
#define IF_16(t, e) t
// Workaround for intel HD:
#define IF_00(t, e) t
#ifdef UG_COMPILE_SPIRV
	#define gl_VertexID gl_VertexIndex

	#define LAYOUT_SAMPLER2(s, b) layout(set = s, binding = b)
	#define LAYOUT_SAMPLER(s, b) layout(set = s, binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, set = s, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(push_constant, std140)
	#define LAYOUT_STORAGE(s, b) layout(std140, set = s, binding = b) readonly restrict buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) IF(loc, layout (location = loc) mod in type name, const type name = defaultValue)
		
	#define INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)

	#define OUTPUT(loc, type, name) IF(loc, layout (location = loc) out type name, type name)
	
	#define OUTPUT_MOD(loc, mod, type, name) IF(loc, layout (location = loc) mod out type name, type name)
	
	#define WINDING ccw

	#define LOCATION(loc) layout(location = loc) 
#else
	#extension GL_ARB_separate_shader_objects : require
	#extension GL_ARB_explicit_attrib_location : require
	#extension GL_ARB_shading_language_420pack : require

#ifdef USE_SAMPLER2
	#define LAYOUT_SAMPLER2(s, b)
#else
	#define LAYOUT_SAMPLER2(s, b) layout(binding = b)
#endif

	#define LAYOUT_SAMPLER(s, b) layout(binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(std140, binding = 2)
	#define LAYOUT_STORAGE(s, b) layout(std140, binding = b) buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) mod in type name
		
	#define INPUT(loc, type, name, defaultValue) in type name

	#define OUTPUT(loc, type, name) out type name
	
	#define OUTPUT_MOD(loc, mod, type, name) mod out type name
	
	#define WINDING ccw

	#define LOCATION(loc)
#endif
/// END AUTOGENERATED HEADER

LAYOUT_SAMPLER2(2, 25) uniform sampler2D normalTex;
LAYOUT_SAMPLER2(2, 28)  uniform sampler2D reflTex;

LAYOUT_UBO(0, 10) uniform View {
	mat4 projView;
	mat4 projViewInverse;
	mat4 proj;
	mat4 projInverse;
	mat4 view;
	mat4 viewInverse;
	vec3 camPos;
	float lodFactor;
	float near;
	float far;
} u_view;

LAYOUT_UBO(2, 14) uniform Water {
	vec2 fragCoordScale;
	vec2 fragCoordOfs;

	vec2 fragCoordReflScale;
	vec2 fragCoordReflOfs;

	vec2 nearFar;
	float fovY;

	float roughness;
	float particleDensity;
	float extinctionCoeff;
} u_water;

vec3 rgbToNormal(vec3 rgb);

const float PI = 3.14159;
const float halfPi = 1.5707963;

vec3 getPosFromDepth(float depth) {
	vec2 fragCoord = gl_FragCoord.xy * u_water.fragCoordScale;
#ifdef INVERT_FRAMEBUFFER_READ_Y
	fragCoord.y = 1.0 - fragCoord.y;
#endif

	float z = depth * 2.0 - 1.0;
	vec2 tc = fragCoord + u_water.fragCoordOfs;

	vec4 clipSpacePosition = vec4(tc * 2.0 - 1.0, z, 1.0);
	
	vec4 worldSpacePosition = u_view.projViewInverse * clipSpacePosition;
	worldSpacePosition /= worldSpacePosition.w;
	
	return worldSpacePosition.xyz;
}

vec3 getNormal(vec2 uv) {
	vec4 col = texture(normalTex, uv);
	vec3 nrml = vec3(u_view.viewInverse * vec4(rgbToNormal(col.rgb), .0));
	if (nrml.z < .8) nrml = vec3(.0, .0, 1.0);
	return nrml;
}

float getFresnelTerm(float ti) {
	const float ni = 1.0; // air
	const float nt = 1.333; // water
	float tt = asin(ni / nt * sin(ti));
	
	float rs = sin(ti - tt) / sin(ti + tt);
	float rp = tan(ti - tt) / tan(ti + tt);
	
	return .5 * (rs * rs + rp * rp);
}

void calcReflection(vec3 viewDir, vec2 maxXangles, vec2 maxYangles, vec2 tcOffset, float reflLod, inout vec3 normal, inout vec3 color) {
	vec2 texCoord = (gl_FragCoord.xy + tcOffset) * u_water.fragCoordScale + u_water.fragCoordOfs;
	normal = getNormal(texCoord);
	
	vec2 tcBase = (gl_FragCoord.xy + tcOffset) * u_water.fragCoordReflScale + u_water.fragCoordReflOfs;
	
	vec3 viewYaxis = normalize(vec3(viewDir.xy, .0));
	vec3 viewXaxis = cross(vec3(.0, .0, 1.0), viewYaxis);
	
	float yAngle = asin(dot(normal, viewYaxis));
	float xAngle = asin(dot(normal, viewXaxis));
	
	float xFactor = 2.0;
	float yFactor = 2.0;
	
	xAngle = xFactor * xAngle;
	if (xAngle < maxXangles.x) xAngle = maxXangles.x - (xAngle - maxXangles.x);
	if (xAngle > maxXangles.y) xAngle = maxXangles.y - (xAngle - maxXangles.y);
	
	yAngle = yFactor * yAngle;
	if (yAngle < maxYangles.x) yAngle = maxYangles.x - (yAngle - maxYangles.x);
	if (yAngle > maxYangles.y) yAngle = maxYangles.y - (yAngle - maxYangles.y);
	
	vec2 normalOffset = vec2(xAngle / u_water.fovY, yAngle / u_water.fovY);
#ifdef INVERT_FRAMEBUFFER_READ_Y
	normalOffset.y = -normalOffset.y;
#endif

	vec2 tcRefl = tcBase + normalOffset;
	
	if (tcRefl.x < .0) tcRefl.x = -tcRefl.x;
	if (tcRefl.x > 1.0) tcRefl.x = 1.0 - (tcRefl.x - 1.0);
	
	if (tcRefl.y < .0) tcRefl.y = -tcRefl.y;
	if (tcRefl.y > 1.0) tcRefl.y = 1.0 - (tcRefl.y - 1.0);
	
	color = textureLod(reflTex, tcRefl, reflLod).rgb;
}
