#!/bin/sh

# Usage: change template.txt and run ./replace.sh
files=$(find ./ -name '*.fs' -or -name '*.gs' -or -name '*.vs' -or -name '*.tese' -or -name '*.tesc')
for file in $files
do
	echo "Processing ${file}"
	lead='^\/\/\/ BEGIN AUTOGENERATED HEADER$'
	tail='^\/\/\/ END AUTOGENERATED HEADER$'
	output=$(sed -e "/$lead/,/$tail/{ /$lead/{p; r template.txt
			}; /$tail/p; d }"  ${file})
			
	echo "$output" > ${file}
done
