#version 150
/// BEGIN AUTOGENERATED HEADER
#define CONC(a,b) a##b

#define IF(c, t, e) CONC(IF_, c)(t, e)

#define IF_UNDEF(t, e) e
#define IF_0(t, e) t
#define IF_1(t, e) t
#define IF_2(t, e) t
#define IF_3(t, e) t
#define IF_4(t, e) t
#define IF_5(t, e) t
#define IF_6(t, e) t
#define IF_7(t, e) t
#define IF_8(t, e) t
#define IF_9(t, e) t
#define IF_10(t, e) t
#define IF_11(t, e) t
#define IF_12(t, e) t
#define IF_13(t, e) t
#define IF_14(t, e) t
#define IF_15(t, e) t
#define IF_16(t, e) t
// Workaround for intel HD:
#define IF_00(t, e) t
#ifdef UG_COMPILE_SPIRV
	#define gl_VertexID gl_VertexIndex

	#define LAYOUT_SAMPLER2(s, b) layout(set = s, binding = b)
	#define LAYOUT_SAMPLER(s, b) layout(set = s, binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, set = s, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(push_constant, std140)
	#define LAYOUT_STORAGE(s, b) layout(std140, set = s, binding = b) readonly restrict buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) IF(loc, layout (location = loc) mod in type name, const type name = defaultValue)
		
	#define INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)

	#define OUTPUT(loc, type, name) IF(loc, layout (location = loc) out type name, type name)
	
	#define OUTPUT_MOD(loc, mod, type, name) IF(loc, layout (location = loc) mod out type name, type name)
	
	#define WINDING ccw

	#define LOCATION(loc) layout(location = loc) 
#else
	#extension GL_ARB_separate_shader_objects : require
	#extension GL_ARB_explicit_attrib_location : require
	#extension GL_ARB_shading_language_420pack : require

#ifdef USE_SAMPLER2
	#define LAYOUT_SAMPLER2(s, b)
#else
	#define LAYOUT_SAMPLER2(s, b) layout(binding = b)
#endif

	#define LAYOUT_SAMPLER(s, b) layout(binding = b)
	#define LAYOUT_UBO(s, b) layout(std140, binding = b)
	#define LAYOUT_PUSH_CONSTANT() layout(std140, binding = 2)
	#define LAYOUT_STORAGE(s, b) layout(std140, binding = b) buffer

	#define VERTEX_INPUT(loc, type, name, defaultValue) IF(loc, layout (location = loc) in type name, const type name = defaultValue)
		
	#define INPUT_MOD(loc, mod, type, name, defaultValue) mod in type name
		
	#define INPUT(loc, type, name, defaultValue) in type name

	#define OUTPUT(loc, type, name) out type name
	
	#define OUTPUT_MOD(loc, mod, type, name) mod out type name
	
	#define WINDING ccw

	#define LOCATION(loc)
#endif
/// END AUTOGENERATED HEADER

LAYOUT_UBO(0, 10) uniform View {
	mat4 projView;
	mat4 projViewInverse;
	mat4 proj;
	mat4 projInverse;
	mat4 view;
	mat4 viewInverse;
	vec3 camPos;
	float lodFactor;
	float near;
	float far;
} u_view;

LAYOUT_UBO(1, 4) uniform VMaterial {
    vec4 color;

	vec2 fadeOutRanges[16];
	vec2 smoothLodRange;
} u_vmat;

VERTEX_INPUT(ATTR_POS_LOC, vec4, attrPosition, vec4(1.0));
VERTEX_INPUT(ATTR_NRML_LOC, vec3, attrNormal, vec3(1.0));
VERTEX_INPUT(ATTR_TC_LOC, vec2, attrTexCoord, vec2(1.0));
VERTEX_INPUT(ATTR_TNGT_LOC, vec4, attrTangent, vec4(1.0));
VERTEX_INPUT(ATTR_SMOOTHLOD_POS_LOC, vec3, attrSmoothLodPosition, vec3(1.0));

VERTEX_INPUT(INSTATTR_MDL_LOC, mat4, instAttrModel, mat4());
VERTEX_INPUT(INSTATTR_BBOX_LOC, vec3, instAttrBbox[2], vec3(1.0));

OUTPUT(POS_LOC, vec4, posAmbient);
OUTPUT(NRML_LOC, vec3, normal_);
OUTPUT(TNGT_LOC, vec3, tangent_);
OUTPUT(BINORM_LOC, vec3, binormal_);
OUTPUT(COL_LOC, vec4, color);
OUTPUT_MOD(TC_LOC, centroid, vec3, texCoordAlpha);
OUTPUT_MOD(MATIDX_LOC, flat, int, matIndex);

float calcDistToBox(vec3 p, vec3 box[2]);
float compFadeOutAlpha(float distance, vec2 range);
void calcFogFactor(vec3 pos);
void getBufTexInstAttrsColor(inout vec4 color);

void main() {
	float distToCam = calcDistToBox(u_view.viewInverse[3].xyz, instAttrBbox);

	vec2 smoothLodRange = u_vmat.smoothLodRange * u_view.lodFactor;

	if (smoothLodRange == vec2(.0)) {
		posAmbient = instAttrModel * attrPosition;
	} else {
		float lodParam = clamp((distToCam - smoothLodRange.x) / (smoothLodRange.y - smoothLodRange.x), .0, 1.0);
		posAmbient = instAttrModel * mix(vec4(attrPosition.xyz, 1.0), vec4(attrSmoothLodPosition, 1.0), lodParam);
		posAmbient.w = attrPosition.w;
	}
	
	float alpha = compFadeOutAlpha(distToCam, u_vmat.fadeOutRanges[0] * vec2(u_view.lodFactor, 1.0 / u_view.lodFactor));

	gl_Position = u_view.projView * vec4(posAmbient.xyz, 1.0);
#ifdef RESCALE_Z_POS
	gl_Position.z = (.5 * gl_Position.z + .5 * gl_Position.w);
#endif
#ifdef INVERT_Y
	gl_Position.y = -gl_Position.y;
#endif

	normal_ = vec3(instAttrModel * vec4(attrNormal, .0));
	tangent_ = vec3(instAttrModel * vec4(vec3(attrTangent), .0));
	binormal_ = cross(normal_, tangent_) * attrTangent.w;
	
	texCoordAlpha = vec3(attrTexCoord, alpha);
	
	matIndex = 0;
	
	calcFogFactor(posAmbient.xyz);

	color = u_vmat.color;

	getBufTexInstAttrsColor(color);
}
